// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/notifications-api/internal/ent/announcement"
	"github.com/bengobox/notifications-api/internal/ent/predicate"
)

// AnnouncementUpdate is the builder for updating Announcement entities.
type AnnouncementUpdate struct {
	config
	hooks     []Hook
	mutation  *AnnouncementMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the AnnouncementUpdate builder.
func (_u *AnnouncementUpdate) Where(ps ...predicate.Announcement) *AnnouncementUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *AnnouncementUpdate) SetTitle(v string) *AnnouncementUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *AnnouncementUpdate) SetNillableTitle(v *string) *AnnouncementUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *AnnouncementUpdate) SetSummary(v string) *AnnouncementUpdate {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *AnnouncementUpdate) SetNillableSummary(v *string) *AnnouncementUpdate {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetHighlights sets the "highlights" field.
func (_u *AnnouncementUpdate) SetHighlights(v []string) *AnnouncementUpdate {
	_u.mutation.SetHighlights(v)
	return _u
}

// AppendHighlights appends value to the "highlights" field.
func (_u *AnnouncementUpdate) AppendHighlights(v []string) *AnnouncementUpdate {
	_u.mutation.AppendHighlights(v)
	return _u
}

// ClearHighlights clears the value of the "highlights" field.
func (_u *AnnouncementUpdate) ClearHighlights() *AnnouncementUpdate {
	_u.mutation.ClearHighlights()
	return _u
}

// SetCtaLabel sets the "cta_label" field.
func (_u *AnnouncementUpdate) SetCtaLabel(v string) *AnnouncementUpdate {
	_u.mutation.SetCtaLabel(v)
	return _u
}

// SetNillableCtaLabel sets the "cta_label" field if the given value is not nil.
func (_u *AnnouncementUpdate) SetNillableCtaLabel(v *string) *AnnouncementUpdate {
	if v != nil {
		_u.SetCtaLabel(*v)
	}
	return _u
}

// ClearCtaLabel clears the value of the "cta_label" field.
func (_u *AnnouncementUpdate) ClearCtaLabel() *AnnouncementUpdate {
	_u.mutation.ClearCtaLabel()
	return _u
}

// SetCtaURL sets the "cta_url" field.
func (_u *AnnouncementUpdate) SetCtaURL(v string) *AnnouncementUpdate {
	_u.mutation.SetCtaURL(v)
	return _u
}

// SetNillableCtaURL sets the "cta_url" field if the given value is not nil.
func (_u *AnnouncementUpdate) SetNillableCtaURL(v *string) *AnnouncementUpdate {
	if v != nil {
		_u.SetCtaURL(*v)
	}
	return _u
}

// ClearCtaURL clears the value of the "cta_url" field.
func (_u *AnnouncementUpdate) ClearCtaURL() *AnnouncementUpdate {
	_u.mutation.ClearCtaURL()
	return _u
}

// SetServices sets the "services" field.
func (_u *AnnouncementUpdate) SetServices(v []string) *AnnouncementUpdate {
	_u.mutation.SetServices(v)
	return _u
}

// AppendServices appends value to the "services" field.
func (_u *AnnouncementUpdate) AppendServices(v []string) *AnnouncementUpdate {
	_u.mutation.AppendServices(v)
	return _u
}

// ClearServices clears the value of the "services" field.
func (_u *AnnouncementUpdate) ClearServices() *AnnouncementUpdate {
	_u.mutation.ClearServices()
	return _u
}

// SetAudience sets the "audience" field.
func (_u *AnnouncementUpdate) SetAudience(v announcement.Audience) *AnnouncementUpdate {
	_u.mutation.SetAudience(v)
	return _u
}

// SetNillableAudience sets the "audience" field if the given value is not nil.
func (_u *AnnouncementUpdate) SetNillableAudience(v *announcement.Audience) *AnnouncementUpdate {
	if v != nil {
		_u.SetAudience(*v)
	}
	return _u
}

// SetTone sets the "tone" field.
func (_u *AnnouncementUpdate) SetTone(v announcement.Tone) *AnnouncementUpdate {
	_u.mutation.SetTone(v)
	return _u
}

// SetNillableTone sets the "tone" field if the given value is not nil.
func (_u *AnnouncementUpdate) SetNillableTone(v *announcement.Tone) *AnnouncementUpdate {
	if v != nil {
		_u.SetTone(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *AnnouncementUpdate) SetPriority(v int) *AnnouncementUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *AnnouncementUpdate) SetNillablePriority(v *int) *AnnouncementUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *AnnouncementUpdate) AddPriority(v int) *AnnouncementUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetDismissible sets the "dismissible" field.
func (_u *AnnouncementUpdate) SetDismissible(v bool) *AnnouncementUpdate {
	_u.mutation.SetDismissible(v)
	return _u
}

// SetNillableDismissible sets the "dismissible" field if the given value is not nil.
func (_u *AnnouncementUpdate) SetNillableDismissible(v *bool) *AnnouncementUpdate {
	if v != nil {
		_u.SetDismissible(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *AnnouncementUpdate) SetIsActive(v bool) *AnnouncementUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *AnnouncementUpdate) SetNillableIsActive(v *bool) *AnnouncementUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *AnnouncementUpdate) SetStartsAt(v time.Time) *AnnouncementUpdate {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *AnnouncementUpdate) SetNillableStartsAt(v *time.Time) *AnnouncementUpdate {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// SetEndsAt sets the "ends_at" field.
func (_u *AnnouncementUpdate) SetEndsAt(v time.Time) *AnnouncementUpdate {
	_u.mutation.SetEndsAt(v)
	return _u
}

// SetNillableEndsAt sets the "ends_at" field if the given value is not nil.
func (_u *AnnouncementUpdate) SetNillableEndsAt(v *time.Time) *AnnouncementUpdate {
	if v != nil {
		_u.SetEndsAt(*v)
	}
	return _u
}

// ClearEndsAt clears the value of the "ends_at" field.
func (_u *AnnouncementUpdate) ClearEndsAt() *AnnouncementUpdate {
	_u.mutation.ClearEndsAt()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *AnnouncementUpdate) SetMetadata(v map[string]interface{}) *AnnouncementUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *AnnouncementUpdate) ClearMetadata() *AnnouncementUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *AnnouncementUpdate) SetCreatedBy(v string) *AnnouncementUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *AnnouncementUpdate) SetNillableCreatedBy(v *string) *AnnouncementUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *AnnouncementUpdate) ClearCreatedBy() *AnnouncementUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AnnouncementUpdate) SetUpdatedAt(v time.Time) *AnnouncementUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AnnouncementMutation object of the builder.
func (_u *AnnouncementUpdate) Mutation() *AnnouncementMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AnnouncementUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AnnouncementUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AnnouncementUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AnnouncementUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AnnouncementUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := announcement.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AnnouncementUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := announcement.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Announcement.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Summary(); ok {
		if err := announcement.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "Announcement.summary": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Audience(); ok {
		if err := announcement.AudienceValidator(v); err != nil {
			return &ValidationError{Name: "audience", err: fmt.Errorf(`ent: validator failed for field "Announcement.audience": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Tone(); ok {
		if err := announcement.ToneValidator(v); err != nil {
			return &ValidationError{Name: "tone", err: fmt.Errorf(`ent: validator failed for field "Announcement.tone": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *AnnouncementUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AnnouncementUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *AnnouncementUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(announcement.Table, announcement.Columns, sqlgraph.NewFieldSpec(announcement.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(announcement.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(announcement.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.Highlights(); ok {
		_spec.SetField(announcement.FieldHighlights, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedHighlights(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, announcement.FieldHighlights, value)
		})
	}
	if _u.mutation.HighlightsCleared() {
		_spec.ClearField(announcement.FieldHighlights, field.TypeJSON)
	}
	if value, ok := _u.mutation.CtaLabel(); ok {
		_spec.SetField(announcement.FieldCtaLabel, field.TypeString, value)
	}
	if _u.mutation.CtaLabelCleared() {
		_spec.ClearField(announcement.FieldCtaLabel, field.TypeString)
	}
	if value, ok := _u.mutation.CtaURL(); ok {
		_spec.SetField(announcement.FieldCtaURL, field.TypeString, value)
	}
	if _u.mutation.CtaURLCleared() {
		_spec.ClearField(announcement.FieldCtaURL, field.TypeString)
	}
	if value, ok := _u.mutation.Services(); ok {
		_spec.SetField(announcement.FieldServices, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedServices(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, announcement.FieldServices, value)
		})
	}
	if _u.mutation.ServicesCleared() {
		_spec.ClearField(announcement.FieldServices, field.TypeJSON)
	}
	if value, ok := _u.mutation.Audience(); ok {
		_spec.SetField(announcement.FieldAudience, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Tone(); ok {
		_spec.SetField(announcement.FieldTone, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(announcement.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(announcement.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Dismissible(); ok {
		_spec.SetField(announcement.FieldDismissible, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(announcement.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(announcement.FieldStartsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndsAt(); ok {
		_spec.SetField(announcement.FieldEndsAt, field.TypeTime, value)
	}
	if _u.mutation.EndsAtCleared() {
		_spec.ClearField(announcement.FieldEndsAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(announcement.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(announcement.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(announcement.FieldCreatedBy, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(announcement.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(announcement.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{announcement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AnnouncementUpdateOne is the builder for updating a single Announcement entity.
type AnnouncementUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *AnnouncementMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetTitle sets the "title" field.
func (_u *AnnouncementUpdateOne) SetTitle(v string) *AnnouncementUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *AnnouncementUpdateOne) SetNillableTitle(v *string) *AnnouncementUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *AnnouncementUpdateOne) SetSummary(v string) *AnnouncementUpdateOne {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *AnnouncementUpdateOne) SetNillableSummary(v *string) *AnnouncementUpdateOne {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetHighlights sets the "highlights" field.
func (_u *AnnouncementUpdateOne) SetHighlights(v []string) *AnnouncementUpdateOne {
	_u.mutation.SetHighlights(v)
	return _u
}

// AppendHighlights appends value to the "highlights" field.
func (_u *AnnouncementUpdateOne) AppendHighlights(v []string) *AnnouncementUpdateOne {
	_u.mutation.AppendHighlights(v)
	return _u
}

// ClearHighlights clears the value of the "highlights" field.
func (_u *AnnouncementUpdateOne) ClearHighlights() *AnnouncementUpdateOne {
	_u.mutation.ClearHighlights()
	return _u
}

// SetCtaLabel sets the "cta_label" field.
func (_u *AnnouncementUpdateOne) SetCtaLabel(v string) *AnnouncementUpdateOne {
	_u.mutation.SetCtaLabel(v)
	return _u
}

// SetNillableCtaLabel sets the "cta_label" field if the given value is not nil.
func (_u *AnnouncementUpdateOne) SetNillableCtaLabel(v *string) *AnnouncementUpdateOne {
	if v != nil {
		_u.SetCtaLabel(*v)
	}
	return _u
}

// ClearCtaLabel clears the value of the "cta_label" field.
func (_u *AnnouncementUpdateOne) ClearCtaLabel() *AnnouncementUpdateOne {
	_u.mutation.ClearCtaLabel()
	return _u
}

// SetCtaURL sets the "cta_url" field.
func (_u *AnnouncementUpdateOne) SetCtaURL(v string) *AnnouncementUpdateOne {
	_u.mutation.SetCtaURL(v)
	return _u
}

// SetNillableCtaURL sets the "cta_url" field if the given value is not nil.
func (_u *AnnouncementUpdateOne) SetNillableCtaURL(v *string) *AnnouncementUpdateOne {
	if v != nil {
		_u.SetCtaURL(*v)
	}
	return _u
}

// ClearCtaURL clears the value of the "cta_url" field.
func (_u *AnnouncementUpdateOne) ClearCtaURL() *AnnouncementUpdateOne {
	_u.mutation.ClearCtaURL()
	return _u
}

// SetServices sets the "services" field.
func (_u *AnnouncementUpdateOne) SetServices(v []string) *AnnouncementUpdateOne {
	_u.mutation.SetServices(v)
	return _u
}

// AppendServices appends value to the "services" field.
func (_u *AnnouncementUpdateOne) AppendServices(v []string) *AnnouncementUpdateOne {
	_u.mutation.AppendServices(v)
	return _u
}

// ClearServices clears the value of the "services" field.
func (_u *AnnouncementUpdateOne) ClearServices() *AnnouncementUpdateOne {
	_u.mutation.ClearServices()
	return _u
}

// SetAudience sets the "audience" field.
func (_u *AnnouncementUpdateOne) SetAudience(v announcement.Audience) *AnnouncementUpdateOne {
	_u.mutation.SetAudience(v)
	return _u
}

// SetNillableAudience sets the "audience" field if the given value is not nil.
func (_u *AnnouncementUpdateOne) SetNillableAudience(v *announcement.Audience) *AnnouncementUpdateOne {
	if v != nil {
		_u.SetAudience(*v)
	}
	return _u
}

// SetTone sets the "tone" field.
func (_u *AnnouncementUpdateOne) SetTone(v announcement.Tone) *AnnouncementUpdateOne {
	_u.mutation.SetTone(v)
	return _u
}

// SetNillableTone sets the "tone" field if the given value is not nil.
func (_u *AnnouncementUpdateOne) SetNillableTone(v *announcement.Tone) *AnnouncementUpdateOne {
	if v != nil {
		_u.SetTone(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *AnnouncementUpdateOne) SetPriority(v int) *AnnouncementUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *AnnouncementUpdateOne) SetNillablePriority(v *int) *AnnouncementUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *AnnouncementUpdateOne) AddPriority(v int) *AnnouncementUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetDismissible sets the "dismissible" field.
func (_u *AnnouncementUpdateOne) SetDismissible(v bool) *AnnouncementUpdateOne {
	_u.mutation.SetDismissible(v)
	return _u
}

// SetNillableDismissible sets the "dismissible" field if the given value is not nil.
func (_u *AnnouncementUpdateOne) SetNillableDismissible(v *bool) *AnnouncementUpdateOne {
	if v != nil {
		_u.SetDismissible(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *AnnouncementUpdateOne) SetIsActive(v bool) *AnnouncementUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *AnnouncementUpdateOne) SetNillableIsActive(v *bool) *AnnouncementUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *AnnouncementUpdateOne) SetStartsAt(v time.Time) *AnnouncementUpdateOne {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *AnnouncementUpdateOne) SetNillableStartsAt(v *time.Time) *AnnouncementUpdateOne {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// SetEndsAt sets the "ends_at" field.
func (_u *AnnouncementUpdateOne) SetEndsAt(v time.Time) *AnnouncementUpdateOne {
	_u.mutation.SetEndsAt(v)
	return _u
}

// SetNillableEndsAt sets the "ends_at" field if the given value is not nil.
func (_u *AnnouncementUpdateOne) SetNillableEndsAt(v *time.Time) *AnnouncementUpdateOne {
	if v != nil {
		_u.SetEndsAt(*v)
	}
	return _u
}

// ClearEndsAt clears the value of the "ends_at" field.
func (_u *AnnouncementUpdateOne) ClearEndsAt() *AnnouncementUpdateOne {
	_u.mutation.ClearEndsAt()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *AnnouncementUpdateOne) SetMetadata(v map[string]interface{}) *AnnouncementUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *AnnouncementUpdateOne) ClearMetadata() *AnnouncementUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *AnnouncementUpdateOne) SetCreatedBy(v string) *AnnouncementUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *AnnouncementUpdateOne) SetNillableCreatedBy(v *string) *AnnouncementUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *AnnouncementUpdateOne) ClearCreatedBy() *AnnouncementUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AnnouncementUpdateOne) SetUpdatedAt(v time.Time) *AnnouncementUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AnnouncementMutation object of the builder.
func (_u *AnnouncementUpdateOne) Mutation() *AnnouncementMutation {
	return _u.mutation
}

// Where appends a list predicates to the AnnouncementUpdate builder.
func (_u *AnnouncementUpdateOne) Where(ps ...predicate.Announcement) *AnnouncementUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AnnouncementUpdateOne) Select(field string, fields ...string) *AnnouncementUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Announcement entity.
func (_u *AnnouncementUpdateOne) Save(ctx context.Context) (*Announcement, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AnnouncementUpdateOne) SaveX(ctx context.Context) *Announcement {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AnnouncementUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AnnouncementUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AnnouncementUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := announcement.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AnnouncementUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := announcement.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Announcement.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Summary(); ok {
		if err := announcement.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "Announcement.summary": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Audience(); ok {
		if err := announcement.AudienceValidator(v); err != nil {
			return &ValidationError{Name: "audience", err: fmt.Errorf(`ent: validator failed for field "Announcement.audience": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Tone(); ok {
		if err := announcement.ToneValidator(v); err != nil {
			return &ValidationError{Name: "tone", err: fmt.Errorf(`ent: validator failed for field "Announcement.tone": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *AnnouncementUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AnnouncementUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *AnnouncementUpdateOne) sqlSave(ctx context.Context) (_node *Announcement, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(announcement.Table, announcement.Columns, sqlgraph.NewFieldSpec(announcement.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Announcement.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, announcement.FieldID)
		for _, f := range fields {
			if !announcement.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != announcement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(announcement.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(announcement.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.Highlights(); ok {
		_spec.SetField(announcement.FieldHighlights, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedHighlights(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, announcement.FieldHighlights, value)
		})
	}
	if _u.mutation.HighlightsCleared() {
		_spec.ClearField(announcement.FieldHighlights, field.TypeJSON)
	}
	if value, ok := _u.mutation.CtaLabel(); ok {
		_spec.SetField(announcement.FieldCtaLabel, field.TypeString, value)
	}
	if _u.mutation.CtaLabelCleared() {
		_spec.ClearField(announcement.FieldCtaLabel, field.TypeString)
	}
	if value, ok := _u.mutation.CtaURL(); ok {
		_spec.SetField(announcement.FieldCtaURL, field.TypeString, value)
	}
	if _u.mutation.CtaURLCleared() {
		_spec.ClearField(announcement.FieldCtaURL, field.TypeString)
	}
	if value, ok := _u.mutation.Services(); ok {
		_spec.SetField(announcement.FieldServices, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedServices(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, announcement.FieldServices, value)
		})
	}
	if _u.mutation.ServicesCleared() {
		_spec.ClearField(announcement.FieldServices, field.TypeJSON)
	}
	if value, ok := _u.mutation.Audience(); ok {
		_spec.SetField(announcement.FieldAudience, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Tone(); ok {
		_spec.SetField(announcement.FieldTone, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(announcement.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(announcement.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Dismissible(); ok {
		_spec.SetField(announcement.FieldDismissible, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(announcement.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(announcement.FieldStartsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndsAt(); ok {
		_spec.SetField(announcement.FieldEndsAt, field.TypeTime, value)
	}
	if _u.mutation.EndsAtCleared() {
		_spec.ClearField(announcement.FieldEndsAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(announcement.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(announcement.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(announcement.FieldCreatedBy, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(announcement.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(announcement.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Announcement{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{announcement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
