// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/notifications-api/internal/ent/broadcast"
	"github.com/bengobox/notifications-api/internal/ent/predicate"
	"github.com/google/uuid"
)

// BroadcastUpdate is the builder for updating Broadcast entities.
type BroadcastUpdate struct {
	config
	hooks     []Hook
	mutation  *BroadcastMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the BroadcastUpdate builder.
func (_u *BroadcastUpdate) Where(ps ...predicate.Broadcast) *BroadcastUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKind sets the "kind" field.
func (_u *BroadcastUpdate) SetKind(v broadcast.Kind) *BroadcastUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *BroadcastUpdate) SetNillableKind(v *broadcast.Kind) *BroadcastUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetClass sets the "class" field.
func (_u *BroadcastUpdate) SetClass(v broadcast.Class) *BroadcastUpdate {
	_u.mutation.SetClass(v)
	return _u
}

// SetNillableClass sets the "class" field if the given value is not nil.
func (_u *BroadcastUpdate) SetNillableClass(v *broadcast.Class) *BroadcastUpdate {
	if v != nil {
		_u.SetClass(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *BroadcastUpdate) SetStatus(v broadcast.Status) *BroadcastUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BroadcastUpdate) SetNillableStatus(v *broadcast.Status) *BroadcastUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *BroadcastUpdate) SetTitle(v string) *BroadcastUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *BroadcastUpdate) SetNillableTitle(v *string) *BroadcastUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetChannels sets the "channels" field.
func (_u *BroadcastUpdate) SetChannels(v []string) *BroadcastUpdate {
	_u.mutation.SetChannels(v)
	return _u
}

// AppendChannels appends value to the "channels" field.
func (_u *BroadcastUpdate) AppendChannels(v []string) *BroadcastUpdate {
	_u.mutation.AppendChannels(v)
	return _u
}

// SetContent sets the "content" field.
func (_u *BroadcastUpdate) SetContent(v map[string]interface{}) *BroadcastUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetAudience sets the "audience" field.
func (_u *BroadcastUpdate) SetAudience(v map[string]interface{}) *BroadcastUpdate {
	_u.mutation.SetAudience(v)
	return _u
}

// SetSendAt sets the "send_at" field.
func (_u *BroadcastUpdate) SetSendAt(v time.Time) *BroadcastUpdate {
	_u.mutation.SetSendAt(v)
	return _u
}

// SetNillableSendAt sets the "send_at" field if the given value is not nil.
func (_u *BroadcastUpdate) SetNillableSendAt(v *time.Time) *BroadcastUpdate {
	if v != nil {
		_u.SetSendAt(*v)
	}
	return _u
}

// ClearSendAt clears the value of the "send_at" field.
func (_u *BroadcastUpdate) ClearSendAt() *BroadcastUpdate {
	_u.mutation.ClearSendAt()
	return _u
}

// SetOccasionID sets the "occasion_id" field.
func (_u *BroadcastUpdate) SetOccasionID(v uuid.UUID) *BroadcastUpdate {
	_u.mutation.SetOccasionID(v)
	return _u
}

// SetNillableOccasionID sets the "occasion_id" field if the given value is not nil.
func (_u *BroadcastUpdate) SetNillableOccasionID(v *uuid.UUID) *BroadcastUpdate {
	if v != nil {
		_u.SetOccasionID(*v)
	}
	return _u
}

// ClearOccasionID clears the value of the "occasion_id" field.
func (_u *BroadcastUpdate) ClearOccasionID() *BroadcastUpdate {
	_u.mutation.ClearOccasionID()
	return _u
}

// SetOccasionYear sets the "occasion_year" field.
func (_u *BroadcastUpdate) SetOccasionYear(v int) *BroadcastUpdate {
	_u.mutation.ResetOccasionYear()
	_u.mutation.SetOccasionYear(v)
	return _u
}

// SetNillableOccasionYear sets the "occasion_year" field if the given value is not nil.
func (_u *BroadcastUpdate) SetNillableOccasionYear(v *int) *BroadcastUpdate {
	if v != nil {
		_u.SetOccasionYear(*v)
	}
	return _u
}

// AddOccasionYear adds value to the "occasion_year" field.
func (_u *BroadcastUpdate) AddOccasionYear(v int) *BroadcastUpdate {
	_u.mutation.AddOccasionYear(v)
	return _u
}

// ClearOccasionYear clears the value of the "occasion_year" field.
func (_u *BroadcastUpdate) ClearOccasionYear() *BroadcastUpdate {
	_u.mutation.ClearOccasionYear()
	return _u
}

// SetRequestedBy sets the "requested_by" field.
func (_u *BroadcastUpdate) SetRequestedBy(v string) *BroadcastUpdate {
	_u.mutation.SetRequestedBy(v)
	return _u
}

// SetNillableRequestedBy sets the "requested_by" field if the given value is not nil.
func (_u *BroadcastUpdate) SetNillableRequestedBy(v *string) *BroadcastUpdate {
	if v != nil {
		_u.SetRequestedBy(*v)
	}
	return _u
}

// ClearRequestedBy clears the value of the "requested_by" field.
func (_u *BroadcastUpdate) ClearRequestedBy() *BroadcastUpdate {
	_u.mutation.ClearRequestedBy()
	return _u
}

// SetApprovedBy sets the "approved_by" field.
func (_u *BroadcastUpdate) SetApprovedBy(v string) *BroadcastUpdate {
	_u.mutation.SetApprovedBy(v)
	return _u
}

// SetNillableApprovedBy sets the "approved_by" field if the given value is not nil.
func (_u *BroadcastUpdate) SetNillableApprovedBy(v *string) *BroadcastUpdate {
	if v != nil {
		_u.SetApprovedBy(*v)
	}
	return _u
}

// ClearApprovedBy clears the value of the "approved_by" field.
func (_u *BroadcastUpdate) ClearApprovedBy() *BroadcastUpdate {
	_u.mutation.ClearApprovedBy()
	return _u
}

// SetApprovedAt sets the "approved_at" field.
func (_u *BroadcastUpdate) SetApprovedAt(v time.Time) *BroadcastUpdate {
	_u.mutation.SetApprovedAt(v)
	return _u
}

// SetNillableApprovedAt sets the "approved_at" field if the given value is not nil.
func (_u *BroadcastUpdate) SetNillableApprovedAt(v *time.Time) *BroadcastUpdate {
	if v != nil {
		_u.SetApprovedAt(*v)
	}
	return _u
}

// ClearApprovedAt clears the value of the "approved_at" field.
func (_u *BroadcastUpdate) ClearApprovedAt() *BroadcastUpdate {
	_u.mutation.ClearApprovedAt()
	return _u
}

// SetTargetCount sets the "target_count" field.
func (_u *BroadcastUpdate) SetTargetCount(v int) *BroadcastUpdate {
	_u.mutation.ResetTargetCount()
	_u.mutation.SetTargetCount(v)
	return _u
}

// SetNillableTargetCount sets the "target_count" field if the given value is not nil.
func (_u *BroadcastUpdate) SetNillableTargetCount(v *int) *BroadcastUpdate {
	if v != nil {
		_u.SetTargetCount(*v)
	}
	return _u
}

// AddTargetCount adds value to the "target_count" field.
func (_u *BroadcastUpdate) AddTargetCount(v int) *BroadcastUpdate {
	_u.mutation.AddTargetCount(v)
	return _u
}

// SetSentCount sets the "sent_count" field.
func (_u *BroadcastUpdate) SetSentCount(v int) *BroadcastUpdate {
	_u.mutation.ResetSentCount()
	_u.mutation.SetSentCount(v)
	return _u
}

// SetNillableSentCount sets the "sent_count" field if the given value is not nil.
func (_u *BroadcastUpdate) SetNillableSentCount(v *int) *BroadcastUpdate {
	if v != nil {
		_u.SetSentCount(*v)
	}
	return _u
}

// AddSentCount adds value to the "sent_count" field.
func (_u *BroadcastUpdate) AddSentCount(v int) *BroadcastUpdate {
	_u.mutation.AddSentCount(v)
	return _u
}

// SetFailedCount sets the "failed_count" field.
func (_u *BroadcastUpdate) SetFailedCount(v int) *BroadcastUpdate {
	_u.mutation.ResetFailedCount()
	_u.mutation.SetFailedCount(v)
	return _u
}

// SetNillableFailedCount sets the "failed_count" field if the given value is not nil.
func (_u *BroadcastUpdate) SetNillableFailedCount(v *int) *BroadcastUpdate {
	if v != nil {
		_u.SetFailedCount(*v)
	}
	return _u
}

// AddFailedCount adds value to the "failed_count" field.
func (_u *BroadcastUpdate) AddFailedCount(v int) *BroadcastUpdate {
	_u.mutation.AddFailedCount(v)
	return _u
}

// SetSkippedCount sets the "skipped_count" field.
func (_u *BroadcastUpdate) SetSkippedCount(v int) *BroadcastUpdate {
	_u.mutation.ResetSkippedCount()
	_u.mutation.SetSkippedCount(v)
	return _u
}

// SetNillableSkippedCount sets the "skipped_count" field if the given value is not nil.
func (_u *BroadcastUpdate) SetNillableSkippedCount(v *int) *BroadcastUpdate {
	if v != nil {
		_u.SetSkippedCount(*v)
	}
	return _u
}

// AddSkippedCount adds value to the "skipped_count" field.
func (_u *BroadcastUpdate) AddSkippedCount(v int) *BroadcastUpdate {
	_u.mutation.AddSkippedCount(v)
	return _u
}

// SetSuppressedCount sets the "suppressed_count" field.
func (_u *BroadcastUpdate) SetSuppressedCount(v int) *BroadcastUpdate {
	_u.mutation.ResetSuppressedCount()
	_u.mutation.SetSuppressedCount(v)
	return _u
}

// SetNillableSuppressedCount sets the "suppressed_count" field if the given value is not nil.
func (_u *BroadcastUpdate) SetNillableSuppressedCount(v *int) *BroadcastUpdate {
	if v != nil {
		_u.SetSuppressedCount(*v)
	}
	return _u
}

// AddSuppressedCount adds value to the "suppressed_count" field.
func (_u *BroadcastUpdate) AddSuppressedCount(v int) *BroadcastUpdate {
	_u.mutation.AddSuppressedCount(v)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *BroadcastUpdate) SetMetadata(v map[string]interface{}) *BroadcastUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *BroadcastUpdate) ClearMetadata() *BroadcastUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *BroadcastUpdate) SetCompletedAt(v time.Time) *BroadcastUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *BroadcastUpdate) SetNillableCompletedAt(v *time.Time) *BroadcastUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *BroadcastUpdate) ClearCompletedAt() *BroadcastUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BroadcastUpdate) SetUpdatedAt(v time.Time) *BroadcastUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the BroadcastMutation object of the builder.
func (_u *BroadcastUpdate) Mutation() *BroadcastMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BroadcastUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BroadcastUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BroadcastUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BroadcastUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BroadcastUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := broadcast.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BroadcastUpdate) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := broadcast.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Broadcast.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Class(); ok {
		if err := broadcast.ClassValidator(v); err != nil {
			return &ValidationError{Name: "class", err: fmt.Errorf(`ent: validator failed for field "Broadcast.class": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := broadcast.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Broadcast.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := broadcast.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Broadcast.title": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *BroadcastUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *BroadcastUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *BroadcastUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(broadcast.Table, broadcast.Columns, sqlgraph.NewFieldSpec(broadcast.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(broadcast.FieldTenantID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(broadcast.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Class(); ok {
		_spec.SetField(broadcast.FieldClass, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(broadcast.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(broadcast.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Channels(); ok {
		_spec.SetField(broadcast.FieldChannels, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedChannels(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, broadcast.FieldChannels, value)
		})
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(broadcast.FieldContent, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Audience(); ok {
		_spec.SetField(broadcast.FieldAudience, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.SendAt(); ok {
		_spec.SetField(broadcast.FieldSendAt, field.TypeTime, value)
	}
	if _u.mutation.SendAtCleared() {
		_spec.ClearField(broadcast.FieldSendAt, field.TypeTime)
	}
	if value, ok := _u.mutation.OccasionID(); ok {
		_spec.SetField(broadcast.FieldOccasionID, field.TypeUUID, value)
	}
	if _u.mutation.OccasionIDCleared() {
		_spec.ClearField(broadcast.FieldOccasionID, field.TypeUUID)
	}
	if value, ok := _u.mutation.OccasionYear(); ok {
		_spec.SetField(broadcast.FieldOccasionYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOccasionYear(); ok {
		_spec.AddField(broadcast.FieldOccasionYear, field.TypeInt, value)
	}
	if _u.mutation.OccasionYearCleared() {
		_spec.ClearField(broadcast.FieldOccasionYear, field.TypeInt)
	}
	if value, ok := _u.mutation.RequestedBy(); ok {
		_spec.SetField(broadcast.FieldRequestedBy, field.TypeString, value)
	}
	if _u.mutation.RequestedByCleared() {
		_spec.ClearField(broadcast.FieldRequestedBy, field.TypeString)
	}
	if value, ok := _u.mutation.ApprovedBy(); ok {
		_spec.SetField(broadcast.FieldApprovedBy, field.TypeString, value)
	}
	if _u.mutation.ApprovedByCleared() {
		_spec.ClearField(broadcast.FieldApprovedBy, field.TypeString)
	}
	if value, ok := _u.mutation.ApprovedAt(); ok {
		_spec.SetField(broadcast.FieldApprovedAt, field.TypeTime, value)
	}
	if _u.mutation.ApprovedAtCleared() {
		_spec.ClearField(broadcast.FieldApprovedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.TargetCount(); ok {
		_spec.SetField(broadcast.FieldTargetCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTargetCount(); ok {
		_spec.AddField(broadcast.FieldTargetCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SentCount(); ok {
		_spec.SetField(broadcast.FieldSentCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSentCount(); ok {
		_spec.AddField(broadcast.FieldSentCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FailedCount(); ok {
		_spec.SetField(broadcast.FieldFailedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFailedCount(); ok {
		_spec.AddField(broadcast.FieldFailedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SkippedCount(); ok {
		_spec.SetField(broadcast.FieldSkippedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSkippedCount(); ok {
		_spec.AddField(broadcast.FieldSkippedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SuppressedCount(); ok {
		_spec.SetField(broadcast.FieldSuppressedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSuppressedCount(); ok {
		_spec.AddField(broadcast.FieldSuppressedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(broadcast.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(broadcast.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(broadcast.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(broadcast.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(broadcast.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{broadcast.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BroadcastUpdateOne is the builder for updating a single Broadcast entity.
type BroadcastUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *BroadcastMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetKind sets the "kind" field.
func (_u *BroadcastUpdateOne) SetKind(v broadcast.Kind) *BroadcastUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *BroadcastUpdateOne) SetNillableKind(v *broadcast.Kind) *BroadcastUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetClass sets the "class" field.
func (_u *BroadcastUpdateOne) SetClass(v broadcast.Class) *BroadcastUpdateOne {
	_u.mutation.SetClass(v)
	return _u
}

// SetNillableClass sets the "class" field if the given value is not nil.
func (_u *BroadcastUpdateOne) SetNillableClass(v *broadcast.Class) *BroadcastUpdateOne {
	if v != nil {
		_u.SetClass(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *BroadcastUpdateOne) SetStatus(v broadcast.Status) *BroadcastUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BroadcastUpdateOne) SetNillableStatus(v *broadcast.Status) *BroadcastUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *BroadcastUpdateOne) SetTitle(v string) *BroadcastUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *BroadcastUpdateOne) SetNillableTitle(v *string) *BroadcastUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetChannels sets the "channels" field.
func (_u *BroadcastUpdateOne) SetChannels(v []string) *BroadcastUpdateOne {
	_u.mutation.SetChannels(v)
	return _u
}

// AppendChannels appends value to the "channels" field.
func (_u *BroadcastUpdateOne) AppendChannels(v []string) *BroadcastUpdateOne {
	_u.mutation.AppendChannels(v)
	return _u
}

// SetContent sets the "content" field.
func (_u *BroadcastUpdateOne) SetContent(v map[string]interface{}) *BroadcastUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetAudience sets the "audience" field.
func (_u *BroadcastUpdateOne) SetAudience(v map[string]interface{}) *BroadcastUpdateOne {
	_u.mutation.SetAudience(v)
	return _u
}

// SetSendAt sets the "send_at" field.
func (_u *BroadcastUpdateOne) SetSendAt(v time.Time) *BroadcastUpdateOne {
	_u.mutation.SetSendAt(v)
	return _u
}

// SetNillableSendAt sets the "send_at" field if the given value is not nil.
func (_u *BroadcastUpdateOne) SetNillableSendAt(v *time.Time) *BroadcastUpdateOne {
	if v != nil {
		_u.SetSendAt(*v)
	}
	return _u
}

// ClearSendAt clears the value of the "send_at" field.
func (_u *BroadcastUpdateOne) ClearSendAt() *BroadcastUpdateOne {
	_u.mutation.ClearSendAt()
	return _u
}

// SetOccasionID sets the "occasion_id" field.
func (_u *BroadcastUpdateOne) SetOccasionID(v uuid.UUID) *BroadcastUpdateOne {
	_u.mutation.SetOccasionID(v)
	return _u
}

// SetNillableOccasionID sets the "occasion_id" field if the given value is not nil.
func (_u *BroadcastUpdateOne) SetNillableOccasionID(v *uuid.UUID) *BroadcastUpdateOne {
	if v != nil {
		_u.SetOccasionID(*v)
	}
	return _u
}

// ClearOccasionID clears the value of the "occasion_id" field.
func (_u *BroadcastUpdateOne) ClearOccasionID() *BroadcastUpdateOne {
	_u.mutation.ClearOccasionID()
	return _u
}

// SetOccasionYear sets the "occasion_year" field.
func (_u *BroadcastUpdateOne) SetOccasionYear(v int) *BroadcastUpdateOne {
	_u.mutation.ResetOccasionYear()
	_u.mutation.SetOccasionYear(v)
	return _u
}

// SetNillableOccasionYear sets the "occasion_year" field if the given value is not nil.
func (_u *BroadcastUpdateOne) SetNillableOccasionYear(v *int) *BroadcastUpdateOne {
	if v != nil {
		_u.SetOccasionYear(*v)
	}
	return _u
}

// AddOccasionYear adds value to the "occasion_year" field.
func (_u *BroadcastUpdateOne) AddOccasionYear(v int) *BroadcastUpdateOne {
	_u.mutation.AddOccasionYear(v)
	return _u
}

// ClearOccasionYear clears the value of the "occasion_year" field.
func (_u *BroadcastUpdateOne) ClearOccasionYear() *BroadcastUpdateOne {
	_u.mutation.ClearOccasionYear()
	return _u
}

// SetRequestedBy sets the "requested_by" field.
func (_u *BroadcastUpdateOne) SetRequestedBy(v string) *BroadcastUpdateOne {
	_u.mutation.SetRequestedBy(v)
	return _u
}

// SetNillableRequestedBy sets the "requested_by" field if the given value is not nil.
func (_u *BroadcastUpdateOne) SetNillableRequestedBy(v *string) *BroadcastUpdateOne {
	if v != nil {
		_u.SetRequestedBy(*v)
	}
	return _u
}

// ClearRequestedBy clears the value of the "requested_by" field.
func (_u *BroadcastUpdateOne) ClearRequestedBy() *BroadcastUpdateOne {
	_u.mutation.ClearRequestedBy()
	return _u
}

// SetApprovedBy sets the "approved_by" field.
func (_u *BroadcastUpdateOne) SetApprovedBy(v string) *BroadcastUpdateOne {
	_u.mutation.SetApprovedBy(v)
	return _u
}

// SetNillableApprovedBy sets the "approved_by" field if the given value is not nil.
func (_u *BroadcastUpdateOne) SetNillableApprovedBy(v *string) *BroadcastUpdateOne {
	if v != nil {
		_u.SetApprovedBy(*v)
	}
	return _u
}

// ClearApprovedBy clears the value of the "approved_by" field.
func (_u *BroadcastUpdateOne) ClearApprovedBy() *BroadcastUpdateOne {
	_u.mutation.ClearApprovedBy()
	return _u
}

// SetApprovedAt sets the "approved_at" field.
func (_u *BroadcastUpdateOne) SetApprovedAt(v time.Time) *BroadcastUpdateOne {
	_u.mutation.SetApprovedAt(v)
	return _u
}

// SetNillableApprovedAt sets the "approved_at" field if the given value is not nil.
func (_u *BroadcastUpdateOne) SetNillableApprovedAt(v *time.Time) *BroadcastUpdateOne {
	if v != nil {
		_u.SetApprovedAt(*v)
	}
	return _u
}

// ClearApprovedAt clears the value of the "approved_at" field.
func (_u *BroadcastUpdateOne) ClearApprovedAt() *BroadcastUpdateOne {
	_u.mutation.ClearApprovedAt()
	return _u
}

// SetTargetCount sets the "target_count" field.
func (_u *BroadcastUpdateOne) SetTargetCount(v int) *BroadcastUpdateOne {
	_u.mutation.ResetTargetCount()
	_u.mutation.SetTargetCount(v)
	return _u
}

// SetNillableTargetCount sets the "target_count" field if the given value is not nil.
func (_u *BroadcastUpdateOne) SetNillableTargetCount(v *int) *BroadcastUpdateOne {
	if v != nil {
		_u.SetTargetCount(*v)
	}
	return _u
}

// AddTargetCount adds value to the "target_count" field.
func (_u *BroadcastUpdateOne) AddTargetCount(v int) *BroadcastUpdateOne {
	_u.mutation.AddTargetCount(v)
	return _u
}

// SetSentCount sets the "sent_count" field.
func (_u *BroadcastUpdateOne) SetSentCount(v int) *BroadcastUpdateOne {
	_u.mutation.ResetSentCount()
	_u.mutation.SetSentCount(v)
	return _u
}

// SetNillableSentCount sets the "sent_count" field if the given value is not nil.
func (_u *BroadcastUpdateOne) SetNillableSentCount(v *int) *BroadcastUpdateOne {
	if v != nil {
		_u.SetSentCount(*v)
	}
	return _u
}

// AddSentCount adds value to the "sent_count" field.
func (_u *BroadcastUpdateOne) AddSentCount(v int) *BroadcastUpdateOne {
	_u.mutation.AddSentCount(v)
	return _u
}

// SetFailedCount sets the "failed_count" field.
func (_u *BroadcastUpdateOne) SetFailedCount(v int) *BroadcastUpdateOne {
	_u.mutation.ResetFailedCount()
	_u.mutation.SetFailedCount(v)
	return _u
}

// SetNillableFailedCount sets the "failed_count" field if the given value is not nil.
func (_u *BroadcastUpdateOne) SetNillableFailedCount(v *int) *BroadcastUpdateOne {
	if v != nil {
		_u.SetFailedCount(*v)
	}
	return _u
}

// AddFailedCount adds value to the "failed_count" field.
func (_u *BroadcastUpdateOne) AddFailedCount(v int) *BroadcastUpdateOne {
	_u.mutation.AddFailedCount(v)
	return _u
}

// SetSkippedCount sets the "skipped_count" field.
func (_u *BroadcastUpdateOne) SetSkippedCount(v int) *BroadcastUpdateOne {
	_u.mutation.ResetSkippedCount()
	_u.mutation.SetSkippedCount(v)
	return _u
}

// SetNillableSkippedCount sets the "skipped_count" field if the given value is not nil.
func (_u *BroadcastUpdateOne) SetNillableSkippedCount(v *int) *BroadcastUpdateOne {
	if v != nil {
		_u.SetSkippedCount(*v)
	}
	return _u
}

// AddSkippedCount adds value to the "skipped_count" field.
func (_u *BroadcastUpdateOne) AddSkippedCount(v int) *BroadcastUpdateOne {
	_u.mutation.AddSkippedCount(v)
	return _u
}

// SetSuppressedCount sets the "suppressed_count" field.
func (_u *BroadcastUpdateOne) SetSuppressedCount(v int) *BroadcastUpdateOne {
	_u.mutation.ResetSuppressedCount()
	_u.mutation.SetSuppressedCount(v)
	return _u
}

// SetNillableSuppressedCount sets the "suppressed_count" field if the given value is not nil.
func (_u *BroadcastUpdateOne) SetNillableSuppressedCount(v *int) *BroadcastUpdateOne {
	if v != nil {
		_u.SetSuppressedCount(*v)
	}
	return _u
}

// AddSuppressedCount adds value to the "suppressed_count" field.
func (_u *BroadcastUpdateOne) AddSuppressedCount(v int) *BroadcastUpdateOne {
	_u.mutation.AddSuppressedCount(v)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *BroadcastUpdateOne) SetMetadata(v map[string]interface{}) *BroadcastUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *BroadcastUpdateOne) ClearMetadata() *BroadcastUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *BroadcastUpdateOne) SetCompletedAt(v time.Time) *BroadcastUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *BroadcastUpdateOne) SetNillableCompletedAt(v *time.Time) *BroadcastUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *BroadcastUpdateOne) ClearCompletedAt() *BroadcastUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BroadcastUpdateOne) SetUpdatedAt(v time.Time) *BroadcastUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the BroadcastMutation object of the builder.
func (_u *BroadcastUpdateOne) Mutation() *BroadcastMutation {
	return _u.mutation
}

// Where appends a list predicates to the BroadcastUpdate builder.
func (_u *BroadcastUpdateOne) Where(ps ...predicate.Broadcast) *BroadcastUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BroadcastUpdateOne) Select(field string, fields ...string) *BroadcastUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Broadcast entity.
func (_u *BroadcastUpdateOne) Save(ctx context.Context) (*Broadcast, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BroadcastUpdateOne) SaveX(ctx context.Context) *Broadcast {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BroadcastUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BroadcastUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BroadcastUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := broadcast.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BroadcastUpdateOne) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := broadcast.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Broadcast.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Class(); ok {
		if err := broadcast.ClassValidator(v); err != nil {
			return &ValidationError{Name: "class", err: fmt.Errorf(`ent: validator failed for field "Broadcast.class": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := broadcast.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Broadcast.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := broadcast.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Broadcast.title": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *BroadcastUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *BroadcastUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *BroadcastUpdateOne) sqlSave(ctx context.Context) (_node *Broadcast, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(broadcast.Table, broadcast.Columns, sqlgraph.NewFieldSpec(broadcast.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Broadcast.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, broadcast.FieldID)
		for _, f := range fields {
			if !broadcast.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != broadcast.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(broadcast.FieldTenantID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(broadcast.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Class(); ok {
		_spec.SetField(broadcast.FieldClass, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(broadcast.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(broadcast.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Channels(); ok {
		_spec.SetField(broadcast.FieldChannels, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedChannels(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, broadcast.FieldChannels, value)
		})
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(broadcast.FieldContent, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Audience(); ok {
		_spec.SetField(broadcast.FieldAudience, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.SendAt(); ok {
		_spec.SetField(broadcast.FieldSendAt, field.TypeTime, value)
	}
	if _u.mutation.SendAtCleared() {
		_spec.ClearField(broadcast.FieldSendAt, field.TypeTime)
	}
	if value, ok := _u.mutation.OccasionID(); ok {
		_spec.SetField(broadcast.FieldOccasionID, field.TypeUUID, value)
	}
	if _u.mutation.OccasionIDCleared() {
		_spec.ClearField(broadcast.FieldOccasionID, field.TypeUUID)
	}
	if value, ok := _u.mutation.OccasionYear(); ok {
		_spec.SetField(broadcast.FieldOccasionYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOccasionYear(); ok {
		_spec.AddField(broadcast.FieldOccasionYear, field.TypeInt, value)
	}
	if _u.mutation.OccasionYearCleared() {
		_spec.ClearField(broadcast.FieldOccasionYear, field.TypeInt)
	}
	if value, ok := _u.mutation.RequestedBy(); ok {
		_spec.SetField(broadcast.FieldRequestedBy, field.TypeString, value)
	}
	if _u.mutation.RequestedByCleared() {
		_spec.ClearField(broadcast.FieldRequestedBy, field.TypeString)
	}
	if value, ok := _u.mutation.ApprovedBy(); ok {
		_spec.SetField(broadcast.FieldApprovedBy, field.TypeString, value)
	}
	if _u.mutation.ApprovedByCleared() {
		_spec.ClearField(broadcast.FieldApprovedBy, field.TypeString)
	}
	if value, ok := _u.mutation.ApprovedAt(); ok {
		_spec.SetField(broadcast.FieldApprovedAt, field.TypeTime, value)
	}
	if _u.mutation.ApprovedAtCleared() {
		_spec.ClearField(broadcast.FieldApprovedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.TargetCount(); ok {
		_spec.SetField(broadcast.FieldTargetCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTargetCount(); ok {
		_spec.AddField(broadcast.FieldTargetCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SentCount(); ok {
		_spec.SetField(broadcast.FieldSentCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSentCount(); ok {
		_spec.AddField(broadcast.FieldSentCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FailedCount(); ok {
		_spec.SetField(broadcast.FieldFailedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFailedCount(); ok {
		_spec.AddField(broadcast.FieldFailedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SkippedCount(); ok {
		_spec.SetField(broadcast.FieldSkippedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSkippedCount(); ok {
		_spec.AddField(broadcast.FieldSkippedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SuppressedCount(); ok {
		_spec.SetField(broadcast.FieldSuppressedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSuppressedCount(); ok {
		_spec.AddField(broadcast.FieldSuppressedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(broadcast.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(broadcast.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(broadcast.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(broadcast.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(broadcast.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Broadcast{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{broadcast.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
