// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/notifications-api/internal/ent/broadcast"
	"github.com/google/uuid"
)

// BroadcastCreate is the builder for creating a Broadcast entity.
type BroadcastCreate struct {
	config
	mutation *BroadcastMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetScope sets the "scope" field.
func (_c *BroadcastCreate) SetScope(v broadcast.Scope) *BroadcastCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *BroadcastCreate) SetTenantID(v uuid.UUID) *BroadcastCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *BroadcastCreate) SetNillableTenantID(v *uuid.UUID) *BroadcastCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetKind sets the "kind" field.
func (_c *BroadcastCreate) SetKind(v broadcast.Kind) *BroadcastCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_c *BroadcastCreate) SetNillableKind(v *broadcast.Kind) *BroadcastCreate {
	if v != nil {
		_c.SetKind(*v)
	}
	return _c
}

// SetClass sets the "class" field.
func (_c *BroadcastCreate) SetClass(v broadcast.Class) *BroadcastCreate {
	_c.mutation.SetClass(v)
	return _c
}

// SetNillableClass sets the "class" field if the given value is not nil.
func (_c *BroadcastCreate) SetNillableClass(v *broadcast.Class) *BroadcastCreate {
	if v != nil {
		_c.SetClass(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *BroadcastCreate) SetStatus(v broadcast.Status) *BroadcastCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *BroadcastCreate) SetNillableStatus(v *broadcast.Status) *BroadcastCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *BroadcastCreate) SetTitle(v string) *BroadcastCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetChannels sets the "channels" field.
func (_c *BroadcastCreate) SetChannels(v []string) *BroadcastCreate {
	_c.mutation.SetChannels(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *BroadcastCreate) SetContent(v map[string]interface{}) *BroadcastCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetAudience sets the "audience" field.
func (_c *BroadcastCreate) SetAudience(v map[string]interface{}) *BroadcastCreate {
	_c.mutation.SetAudience(v)
	return _c
}

// SetSendAt sets the "send_at" field.
func (_c *BroadcastCreate) SetSendAt(v time.Time) *BroadcastCreate {
	_c.mutation.SetSendAt(v)
	return _c
}

// SetNillableSendAt sets the "send_at" field if the given value is not nil.
func (_c *BroadcastCreate) SetNillableSendAt(v *time.Time) *BroadcastCreate {
	if v != nil {
		_c.SetSendAt(*v)
	}
	return _c
}

// SetOccasionID sets the "occasion_id" field.
func (_c *BroadcastCreate) SetOccasionID(v uuid.UUID) *BroadcastCreate {
	_c.mutation.SetOccasionID(v)
	return _c
}

// SetNillableOccasionID sets the "occasion_id" field if the given value is not nil.
func (_c *BroadcastCreate) SetNillableOccasionID(v *uuid.UUID) *BroadcastCreate {
	if v != nil {
		_c.SetOccasionID(*v)
	}
	return _c
}

// SetOccasionYear sets the "occasion_year" field.
func (_c *BroadcastCreate) SetOccasionYear(v int) *BroadcastCreate {
	_c.mutation.SetOccasionYear(v)
	return _c
}

// SetNillableOccasionYear sets the "occasion_year" field if the given value is not nil.
func (_c *BroadcastCreate) SetNillableOccasionYear(v *int) *BroadcastCreate {
	if v != nil {
		_c.SetOccasionYear(*v)
	}
	return _c
}

// SetRequestedBy sets the "requested_by" field.
func (_c *BroadcastCreate) SetRequestedBy(v string) *BroadcastCreate {
	_c.mutation.SetRequestedBy(v)
	return _c
}

// SetNillableRequestedBy sets the "requested_by" field if the given value is not nil.
func (_c *BroadcastCreate) SetNillableRequestedBy(v *string) *BroadcastCreate {
	if v != nil {
		_c.SetRequestedBy(*v)
	}
	return _c
}

// SetApprovedBy sets the "approved_by" field.
func (_c *BroadcastCreate) SetApprovedBy(v string) *BroadcastCreate {
	_c.mutation.SetApprovedBy(v)
	return _c
}

// SetNillableApprovedBy sets the "approved_by" field if the given value is not nil.
func (_c *BroadcastCreate) SetNillableApprovedBy(v *string) *BroadcastCreate {
	if v != nil {
		_c.SetApprovedBy(*v)
	}
	return _c
}

// SetApprovedAt sets the "approved_at" field.
func (_c *BroadcastCreate) SetApprovedAt(v time.Time) *BroadcastCreate {
	_c.mutation.SetApprovedAt(v)
	return _c
}

// SetNillableApprovedAt sets the "approved_at" field if the given value is not nil.
func (_c *BroadcastCreate) SetNillableApprovedAt(v *time.Time) *BroadcastCreate {
	if v != nil {
		_c.SetApprovedAt(*v)
	}
	return _c
}

// SetTargetCount sets the "target_count" field.
func (_c *BroadcastCreate) SetTargetCount(v int) *BroadcastCreate {
	_c.mutation.SetTargetCount(v)
	return _c
}

// SetNillableTargetCount sets the "target_count" field if the given value is not nil.
func (_c *BroadcastCreate) SetNillableTargetCount(v *int) *BroadcastCreate {
	if v != nil {
		_c.SetTargetCount(*v)
	}
	return _c
}

// SetSentCount sets the "sent_count" field.
func (_c *BroadcastCreate) SetSentCount(v int) *BroadcastCreate {
	_c.mutation.SetSentCount(v)
	return _c
}

// SetNillableSentCount sets the "sent_count" field if the given value is not nil.
func (_c *BroadcastCreate) SetNillableSentCount(v *int) *BroadcastCreate {
	if v != nil {
		_c.SetSentCount(*v)
	}
	return _c
}

// SetFailedCount sets the "failed_count" field.
func (_c *BroadcastCreate) SetFailedCount(v int) *BroadcastCreate {
	_c.mutation.SetFailedCount(v)
	return _c
}

// SetNillableFailedCount sets the "failed_count" field if the given value is not nil.
func (_c *BroadcastCreate) SetNillableFailedCount(v *int) *BroadcastCreate {
	if v != nil {
		_c.SetFailedCount(*v)
	}
	return _c
}

// SetSkippedCount sets the "skipped_count" field.
func (_c *BroadcastCreate) SetSkippedCount(v int) *BroadcastCreate {
	_c.mutation.SetSkippedCount(v)
	return _c
}

// SetNillableSkippedCount sets the "skipped_count" field if the given value is not nil.
func (_c *BroadcastCreate) SetNillableSkippedCount(v *int) *BroadcastCreate {
	if v != nil {
		_c.SetSkippedCount(*v)
	}
	return _c
}

// SetSuppressedCount sets the "suppressed_count" field.
func (_c *BroadcastCreate) SetSuppressedCount(v int) *BroadcastCreate {
	_c.mutation.SetSuppressedCount(v)
	return _c
}

// SetNillableSuppressedCount sets the "suppressed_count" field if the given value is not nil.
func (_c *BroadcastCreate) SetNillableSuppressedCount(v *int) *BroadcastCreate {
	if v != nil {
		_c.SetSuppressedCount(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *BroadcastCreate) SetMetadata(v map[string]interface{}) *BroadcastCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *BroadcastCreate) SetCompletedAt(v time.Time) *BroadcastCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *BroadcastCreate) SetNillableCompletedAt(v *time.Time) *BroadcastCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *BroadcastCreate) SetCreatedAt(v time.Time) *BroadcastCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BroadcastCreate) SetNillableCreatedAt(v *time.Time) *BroadcastCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BroadcastCreate) SetUpdatedAt(v time.Time) *BroadcastCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BroadcastCreate) SetNillableUpdatedAt(v *time.Time) *BroadcastCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *BroadcastCreate) SetID(v uuid.UUID) *BroadcastCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *BroadcastCreate) SetNillableID(v *uuid.UUID) *BroadcastCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the BroadcastMutation object of the builder.
func (_c *BroadcastCreate) Mutation() *BroadcastMutation {
	return _c.mutation
}

// Save creates the Broadcast in the database.
func (_c *BroadcastCreate) Save(ctx context.Context) (*Broadcast, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BroadcastCreate) SaveX(ctx context.Context) *Broadcast {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BroadcastCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BroadcastCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BroadcastCreate) defaults() {
	if _, ok := _c.mutation.Kind(); !ok {
		v := broadcast.DefaultKind
		_c.mutation.SetKind(v)
	}
	if _, ok := _c.mutation.Class(); !ok {
		v := broadcast.DefaultClass
		_c.mutation.SetClass(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := broadcast.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.TargetCount(); !ok {
		v := broadcast.DefaultTargetCount
		_c.mutation.SetTargetCount(v)
	}
	if _, ok := _c.mutation.SentCount(); !ok {
		v := broadcast.DefaultSentCount
		_c.mutation.SetSentCount(v)
	}
	if _, ok := _c.mutation.FailedCount(); !ok {
		v := broadcast.DefaultFailedCount
		_c.mutation.SetFailedCount(v)
	}
	if _, ok := _c.mutation.SkippedCount(); !ok {
		v := broadcast.DefaultSkippedCount
		_c.mutation.SetSkippedCount(v)
	}
	if _, ok := _c.mutation.SuppressedCount(); !ok {
		v := broadcast.DefaultSuppressedCount
		_c.mutation.SetSuppressedCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := broadcast.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := broadcast.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := broadcast.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BroadcastCreate) check() error {
	if _, ok := _c.mutation.Scope(); !ok {
		return &ValidationError{Name: "scope", err: errors.New(`ent: missing required field "Broadcast.scope"`)}
	}
	if v, ok := _c.mutation.Scope(); ok {
		if err := broadcast.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "Broadcast.scope": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "Broadcast.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := broadcast.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Broadcast.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Class(); !ok {
		return &ValidationError{Name: "class", err: errors.New(`ent: missing required field "Broadcast.class"`)}
	}
	if v, ok := _c.mutation.Class(); ok {
		if err := broadcast.ClassValidator(v); err != nil {
			return &ValidationError{Name: "class", err: fmt.Errorf(`ent: validator failed for field "Broadcast.class": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Broadcast.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := broadcast.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Broadcast.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Broadcast.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := broadcast.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Broadcast.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Channels(); !ok {
		return &ValidationError{Name: "channels", err: errors.New(`ent: missing required field "Broadcast.channels"`)}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Broadcast.content"`)}
	}
	if _, ok := _c.mutation.Audience(); !ok {
		return &ValidationError{Name: "audience", err: errors.New(`ent: missing required field "Broadcast.audience"`)}
	}
	if _, ok := _c.mutation.TargetCount(); !ok {
		return &ValidationError{Name: "target_count", err: errors.New(`ent: missing required field "Broadcast.target_count"`)}
	}
	if _, ok := _c.mutation.SentCount(); !ok {
		return &ValidationError{Name: "sent_count", err: errors.New(`ent: missing required field "Broadcast.sent_count"`)}
	}
	if _, ok := _c.mutation.FailedCount(); !ok {
		return &ValidationError{Name: "failed_count", err: errors.New(`ent: missing required field "Broadcast.failed_count"`)}
	}
	if _, ok := _c.mutation.SkippedCount(); !ok {
		return &ValidationError{Name: "skipped_count", err: errors.New(`ent: missing required field "Broadcast.skipped_count"`)}
	}
	if _, ok := _c.mutation.SuppressedCount(); !ok {
		return &ValidationError{Name: "suppressed_count", err: errors.New(`ent: missing required field "Broadcast.suppressed_count"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Broadcast.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Broadcast.updated_at"`)}
	}
	return nil
}

func (_c *BroadcastCreate) sqlSave(ctx context.Context) (*Broadcast, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BroadcastCreate) createSpec() (*Broadcast, *sqlgraph.CreateSpec) {
	var (
		_node = &Broadcast{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(broadcast.Table, sqlgraph.NewFieldSpec(broadcast.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(broadcast.FieldScope, field.TypeEnum, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(broadcast.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(broadcast.FieldKind, field.TypeEnum, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Class(); ok {
		_spec.SetField(broadcast.FieldClass, field.TypeEnum, value)
		_node.Class = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(broadcast.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(broadcast.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Channels(); ok {
		_spec.SetField(broadcast.FieldChannels, field.TypeJSON, value)
		_node.Channels = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(broadcast.FieldContent, field.TypeJSON, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Audience(); ok {
		_spec.SetField(broadcast.FieldAudience, field.TypeJSON, value)
		_node.Audience = value
	}
	if value, ok := _c.mutation.SendAt(); ok {
		_spec.SetField(broadcast.FieldSendAt, field.TypeTime, value)
		_node.SendAt = &value
	}
	if value, ok := _c.mutation.OccasionID(); ok {
		_spec.SetField(broadcast.FieldOccasionID, field.TypeUUID, value)
		_node.OccasionID = &value
	}
	if value, ok := _c.mutation.OccasionYear(); ok {
		_spec.SetField(broadcast.FieldOccasionYear, field.TypeInt, value)
		_node.OccasionYear = &value
	}
	if value, ok := _c.mutation.RequestedBy(); ok {
		_spec.SetField(broadcast.FieldRequestedBy, field.TypeString, value)
		_node.RequestedBy = value
	}
	if value, ok := _c.mutation.ApprovedBy(); ok {
		_spec.SetField(broadcast.FieldApprovedBy, field.TypeString, value)
		_node.ApprovedBy = value
	}
	if value, ok := _c.mutation.ApprovedAt(); ok {
		_spec.SetField(broadcast.FieldApprovedAt, field.TypeTime, value)
		_node.ApprovedAt = &value
	}
	if value, ok := _c.mutation.TargetCount(); ok {
		_spec.SetField(broadcast.FieldTargetCount, field.TypeInt, value)
		_node.TargetCount = value
	}
	if value, ok := _c.mutation.SentCount(); ok {
		_spec.SetField(broadcast.FieldSentCount, field.TypeInt, value)
		_node.SentCount = value
	}
	if value, ok := _c.mutation.FailedCount(); ok {
		_spec.SetField(broadcast.FieldFailedCount, field.TypeInt, value)
		_node.FailedCount = value
	}
	if value, ok := _c.mutation.SkippedCount(); ok {
		_spec.SetField(broadcast.FieldSkippedCount, field.TypeInt, value)
		_node.SkippedCount = value
	}
	if value, ok := _c.mutation.SuppressedCount(); ok {
		_spec.SetField(broadcast.FieldSuppressedCount, field.TypeInt, value)
		_node.SuppressedCount = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(broadcast.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(broadcast.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(broadcast.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(broadcast.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Broadcast.Create().
//		SetScope(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BroadcastUpsert) {
//			SetScope(v+v).
//		}).
//		Exec(ctx)
func (_c *BroadcastCreate) OnConflict(opts ...sql.ConflictOption) *BroadcastUpsertOne {
	_c.conflict = opts
	return &BroadcastUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Broadcast.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BroadcastCreate) OnConflictColumns(columns ...string) *BroadcastUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BroadcastUpsertOne{
		create: _c,
	}
}

type (
	// BroadcastUpsertOne is the builder for "upsert"-ing
	//  one Broadcast node.
	BroadcastUpsertOne struct {
		create *BroadcastCreate
	}

	// BroadcastUpsert is the "OnConflict" setter.
	BroadcastUpsert struct {
		*sql.UpdateSet
	}
)

// SetKind sets the "kind" field.
func (u *BroadcastUpsert) SetKind(v broadcast.Kind) *BroadcastUpsert {
	u.Set(broadcast.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *BroadcastUpsert) UpdateKind() *BroadcastUpsert {
	u.SetExcluded(broadcast.FieldKind)
	return u
}

// SetClass sets the "class" field.
func (u *BroadcastUpsert) SetClass(v broadcast.Class) *BroadcastUpsert {
	u.Set(broadcast.FieldClass, v)
	return u
}

// UpdateClass sets the "class" field to the value that was provided on create.
func (u *BroadcastUpsert) UpdateClass() *BroadcastUpsert {
	u.SetExcluded(broadcast.FieldClass)
	return u
}

// SetStatus sets the "status" field.
func (u *BroadcastUpsert) SetStatus(v broadcast.Status) *BroadcastUpsert {
	u.Set(broadcast.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *BroadcastUpsert) UpdateStatus() *BroadcastUpsert {
	u.SetExcluded(broadcast.FieldStatus)
	return u
}

// SetTitle sets the "title" field.
func (u *BroadcastUpsert) SetTitle(v string) *BroadcastUpsert {
	u.Set(broadcast.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *BroadcastUpsert) UpdateTitle() *BroadcastUpsert {
	u.SetExcluded(broadcast.FieldTitle)
	return u
}

// SetChannels sets the "channels" field.
func (u *BroadcastUpsert) SetChannels(v []string) *BroadcastUpsert {
	u.Set(broadcast.FieldChannels, v)
	return u
}

// UpdateChannels sets the "channels" field to the value that was provided on create.
func (u *BroadcastUpsert) UpdateChannels() *BroadcastUpsert {
	u.SetExcluded(broadcast.FieldChannels)
	return u
}

// SetContent sets the "content" field.
func (u *BroadcastUpsert) SetContent(v map[string]interface{}) *BroadcastUpsert {
	u.Set(broadcast.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *BroadcastUpsert) UpdateContent() *BroadcastUpsert {
	u.SetExcluded(broadcast.FieldContent)
	return u
}

// SetAudience sets the "audience" field.
func (u *BroadcastUpsert) SetAudience(v map[string]interface{}) *BroadcastUpsert {
	u.Set(broadcast.FieldAudience, v)
	return u
}

// UpdateAudience sets the "audience" field to the value that was provided on create.
func (u *BroadcastUpsert) UpdateAudience() *BroadcastUpsert {
	u.SetExcluded(broadcast.FieldAudience)
	return u
}

// SetSendAt sets the "send_at" field.
func (u *BroadcastUpsert) SetSendAt(v time.Time) *BroadcastUpsert {
	u.Set(broadcast.FieldSendAt, v)
	return u
}

// UpdateSendAt sets the "send_at" field to the value that was provided on create.
func (u *BroadcastUpsert) UpdateSendAt() *BroadcastUpsert {
	u.SetExcluded(broadcast.FieldSendAt)
	return u
}

// ClearSendAt clears the value of the "send_at" field.
func (u *BroadcastUpsert) ClearSendAt() *BroadcastUpsert {
	u.SetNull(broadcast.FieldSendAt)
	return u
}

// SetOccasionID sets the "occasion_id" field.
func (u *BroadcastUpsert) SetOccasionID(v uuid.UUID) *BroadcastUpsert {
	u.Set(broadcast.FieldOccasionID, v)
	return u
}

// UpdateOccasionID sets the "occasion_id" field to the value that was provided on create.
func (u *BroadcastUpsert) UpdateOccasionID() *BroadcastUpsert {
	u.SetExcluded(broadcast.FieldOccasionID)
	return u
}

// ClearOccasionID clears the value of the "occasion_id" field.
func (u *BroadcastUpsert) ClearOccasionID() *BroadcastUpsert {
	u.SetNull(broadcast.FieldOccasionID)
	return u
}

// SetOccasionYear sets the "occasion_year" field.
func (u *BroadcastUpsert) SetOccasionYear(v int) *BroadcastUpsert {
	u.Set(broadcast.FieldOccasionYear, v)
	return u
}

// UpdateOccasionYear sets the "occasion_year" field to the value that was provided on create.
func (u *BroadcastUpsert) UpdateOccasionYear() *BroadcastUpsert {
	u.SetExcluded(broadcast.FieldOccasionYear)
	return u
}

// AddOccasionYear adds v to the "occasion_year" field.
func (u *BroadcastUpsert) AddOccasionYear(v int) *BroadcastUpsert {
	u.Add(broadcast.FieldOccasionYear, v)
	return u
}

// ClearOccasionYear clears the value of the "occasion_year" field.
func (u *BroadcastUpsert) ClearOccasionYear() *BroadcastUpsert {
	u.SetNull(broadcast.FieldOccasionYear)
	return u
}

// SetRequestedBy sets the "requested_by" field.
func (u *BroadcastUpsert) SetRequestedBy(v string) *BroadcastUpsert {
	u.Set(broadcast.FieldRequestedBy, v)
	return u
}

// UpdateRequestedBy sets the "requested_by" field to the value that was provided on create.
func (u *BroadcastUpsert) UpdateRequestedBy() *BroadcastUpsert {
	u.SetExcluded(broadcast.FieldRequestedBy)
	return u
}

// ClearRequestedBy clears the value of the "requested_by" field.
func (u *BroadcastUpsert) ClearRequestedBy() *BroadcastUpsert {
	u.SetNull(broadcast.FieldRequestedBy)
	return u
}

// SetApprovedBy sets the "approved_by" field.
func (u *BroadcastUpsert) SetApprovedBy(v string) *BroadcastUpsert {
	u.Set(broadcast.FieldApprovedBy, v)
	return u
}

// UpdateApprovedBy sets the "approved_by" field to the value that was provided on create.
func (u *BroadcastUpsert) UpdateApprovedBy() *BroadcastUpsert {
	u.SetExcluded(broadcast.FieldApprovedBy)
	return u
}

// ClearApprovedBy clears the value of the "approved_by" field.
func (u *BroadcastUpsert) ClearApprovedBy() *BroadcastUpsert {
	u.SetNull(broadcast.FieldApprovedBy)
	return u
}

// SetApprovedAt sets the "approved_at" field.
func (u *BroadcastUpsert) SetApprovedAt(v time.Time) *BroadcastUpsert {
	u.Set(broadcast.FieldApprovedAt, v)
	return u
}

// UpdateApprovedAt sets the "approved_at" field to the value that was provided on create.
func (u *BroadcastUpsert) UpdateApprovedAt() *BroadcastUpsert {
	u.SetExcluded(broadcast.FieldApprovedAt)
	return u
}

// ClearApprovedAt clears the value of the "approved_at" field.
func (u *BroadcastUpsert) ClearApprovedAt() *BroadcastUpsert {
	u.SetNull(broadcast.FieldApprovedAt)
	return u
}

// SetTargetCount sets the "target_count" field.
func (u *BroadcastUpsert) SetTargetCount(v int) *BroadcastUpsert {
	u.Set(broadcast.FieldTargetCount, v)
	return u
}

// UpdateTargetCount sets the "target_count" field to the value that was provided on create.
func (u *BroadcastUpsert) UpdateTargetCount() *BroadcastUpsert {
	u.SetExcluded(broadcast.FieldTargetCount)
	return u
}

// AddTargetCount adds v to the "target_count" field.
func (u *BroadcastUpsert) AddTargetCount(v int) *BroadcastUpsert {
	u.Add(broadcast.FieldTargetCount, v)
	return u
}

// SetSentCount sets the "sent_count" field.
func (u *BroadcastUpsert) SetSentCount(v int) *BroadcastUpsert {
	u.Set(broadcast.FieldSentCount, v)
	return u
}

// UpdateSentCount sets the "sent_count" field to the value that was provided on create.
func (u *BroadcastUpsert) UpdateSentCount() *BroadcastUpsert {
	u.SetExcluded(broadcast.FieldSentCount)
	return u
}

// AddSentCount adds v to the "sent_count" field.
func (u *BroadcastUpsert) AddSentCount(v int) *BroadcastUpsert {
	u.Add(broadcast.FieldSentCount, v)
	return u
}

// SetFailedCount sets the "failed_count" field.
func (u *BroadcastUpsert) SetFailedCount(v int) *BroadcastUpsert {
	u.Set(broadcast.FieldFailedCount, v)
	return u
}

// UpdateFailedCount sets the "failed_count" field to the value that was provided on create.
func (u *BroadcastUpsert) UpdateFailedCount() *BroadcastUpsert {
	u.SetExcluded(broadcast.FieldFailedCount)
	return u
}

// AddFailedCount adds v to the "failed_count" field.
func (u *BroadcastUpsert) AddFailedCount(v int) *BroadcastUpsert {
	u.Add(broadcast.FieldFailedCount, v)
	return u
}

// SetSkippedCount sets the "skipped_count" field.
func (u *BroadcastUpsert) SetSkippedCount(v int) *BroadcastUpsert {
	u.Set(broadcast.FieldSkippedCount, v)
	return u
}

// UpdateSkippedCount sets the "skipped_count" field to the value that was provided on create.
func (u *BroadcastUpsert) UpdateSkippedCount() *BroadcastUpsert {
	u.SetExcluded(broadcast.FieldSkippedCount)
	return u
}

// AddSkippedCount adds v to the "skipped_count" field.
func (u *BroadcastUpsert) AddSkippedCount(v int) *BroadcastUpsert {
	u.Add(broadcast.FieldSkippedCount, v)
	return u
}

// SetSuppressedCount sets the "suppressed_count" field.
func (u *BroadcastUpsert) SetSuppressedCount(v int) *BroadcastUpsert {
	u.Set(broadcast.FieldSuppressedCount, v)
	return u
}

// UpdateSuppressedCount sets the "suppressed_count" field to the value that was provided on create.
func (u *BroadcastUpsert) UpdateSuppressedCount() *BroadcastUpsert {
	u.SetExcluded(broadcast.FieldSuppressedCount)
	return u
}

// AddSuppressedCount adds v to the "suppressed_count" field.
func (u *BroadcastUpsert) AddSuppressedCount(v int) *BroadcastUpsert {
	u.Add(broadcast.FieldSuppressedCount, v)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *BroadcastUpsert) SetMetadata(v map[string]interface{}) *BroadcastUpsert {
	u.Set(broadcast.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *BroadcastUpsert) UpdateMetadata() *BroadcastUpsert {
	u.SetExcluded(broadcast.FieldMetadata)
	return u
}

// ClearMetadata clears the value of the "metadata" field.
func (u *BroadcastUpsert) ClearMetadata() *BroadcastUpsert {
	u.SetNull(broadcast.FieldMetadata)
	return u
}

// SetCompletedAt sets the "completed_at" field.
func (u *BroadcastUpsert) SetCompletedAt(v time.Time) *BroadcastUpsert {
	u.Set(broadcast.FieldCompletedAt, v)
	return u
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *BroadcastUpsert) UpdateCompletedAt() *BroadcastUpsert {
	u.SetExcluded(broadcast.FieldCompletedAt)
	return u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *BroadcastUpsert) ClearCompletedAt() *BroadcastUpsert {
	u.SetNull(broadcast.FieldCompletedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BroadcastUpsert) SetUpdatedAt(v time.Time) *BroadcastUpsert {
	u.Set(broadcast.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BroadcastUpsert) UpdateUpdatedAt() *BroadcastUpsert {
	u.SetExcluded(broadcast.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Broadcast.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(broadcast.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *BroadcastUpsertOne) UpdateNewValues() *BroadcastUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(broadcast.FieldID)
		}
		if _, exists := u.create.mutation.Scope(); exists {
			s.SetIgnore(broadcast.FieldScope)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(broadcast.FieldTenantID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(broadcast.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Broadcast.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BroadcastUpsertOne) Ignore() *BroadcastUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BroadcastUpsertOne) DoNothing() *BroadcastUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BroadcastCreate.OnConflict
// documentation for more info.
func (u *BroadcastUpsertOne) Update(set func(*BroadcastUpsert)) *BroadcastUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BroadcastUpsert{UpdateSet: update})
	}))
	return u
}

// SetKind sets the "kind" field.
func (u *BroadcastUpsertOne) SetKind(v broadcast.Kind) *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *BroadcastUpsertOne) UpdateKind() *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateKind()
	})
}

// SetClass sets the "class" field.
func (u *BroadcastUpsertOne) SetClass(v broadcast.Class) *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetClass(v)
	})
}

// UpdateClass sets the "class" field to the value that was provided on create.
func (u *BroadcastUpsertOne) UpdateClass() *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateClass()
	})
}

// SetStatus sets the "status" field.
func (u *BroadcastUpsertOne) SetStatus(v broadcast.Status) *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *BroadcastUpsertOne) UpdateStatus() *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateStatus()
	})
}

// SetTitle sets the "title" field.
func (u *BroadcastUpsertOne) SetTitle(v string) *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *BroadcastUpsertOne) UpdateTitle() *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateTitle()
	})
}

// SetChannels sets the "channels" field.
func (u *BroadcastUpsertOne) SetChannels(v []string) *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetChannels(v)
	})
}

// UpdateChannels sets the "channels" field to the value that was provided on create.
func (u *BroadcastUpsertOne) UpdateChannels() *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateChannels()
	})
}

// SetContent sets the "content" field.
func (u *BroadcastUpsertOne) SetContent(v map[string]interface{}) *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *BroadcastUpsertOne) UpdateContent() *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateContent()
	})
}

// SetAudience sets the "audience" field.
func (u *BroadcastUpsertOne) SetAudience(v map[string]interface{}) *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetAudience(v)
	})
}

// UpdateAudience sets the "audience" field to the value that was provided on create.
func (u *BroadcastUpsertOne) UpdateAudience() *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateAudience()
	})
}

// SetSendAt sets the "send_at" field.
func (u *BroadcastUpsertOne) SetSendAt(v time.Time) *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetSendAt(v)
	})
}

// UpdateSendAt sets the "send_at" field to the value that was provided on create.
func (u *BroadcastUpsertOne) UpdateSendAt() *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateSendAt()
	})
}

// ClearSendAt clears the value of the "send_at" field.
func (u *BroadcastUpsertOne) ClearSendAt() *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.ClearSendAt()
	})
}

// SetOccasionID sets the "occasion_id" field.
func (u *BroadcastUpsertOne) SetOccasionID(v uuid.UUID) *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetOccasionID(v)
	})
}

// UpdateOccasionID sets the "occasion_id" field to the value that was provided on create.
func (u *BroadcastUpsertOne) UpdateOccasionID() *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateOccasionID()
	})
}

// ClearOccasionID clears the value of the "occasion_id" field.
func (u *BroadcastUpsertOne) ClearOccasionID() *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.ClearOccasionID()
	})
}

// SetOccasionYear sets the "occasion_year" field.
func (u *BroadcastUpsertOne) SetOccasionYear(v int) *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetOccasionYear(v)
	})
}

// AddOccasionYear adds v to the "occasion_year" field.
func (u *BroadcastUpsertOne) AddOccasionYear(v int) *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.AddOccasionYear(v)
	})
}

// UpdateOccasionYear sets the "occasion_year" field to the value that was provided on create.
func (u *BroadcastUpsertOne) UpdateOccasionYear() *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateOccasionYear()
	})
}

// ClearOccasionYear clears the value of the "occasion_year" field.
func (u *BroadcastUpsertOne) ClearOccasionYear() *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.ClearOccasionYear()
	})
}

// SetRequestedBy sets the "requested_by" field.
func (u *BroadcastUpsertOne) SetRequestedBy(v string) *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetRequestedBy(v)
	})
}

// UpdateRequestedBy sets the "requested_by" field to the value that was provided on create.
func (u *BroadcastUpsertOne) UpdateRequestedBy() *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateRequestedBy()
	})
}

// ClearRequestedBy clears the value of the "requested_by" field.
func (u *BroadcastUpsertOne) ClearRequestedBy() *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.ClearRequestedBy()
	})
}

// SetApprovedBy sets the "approved_by" field.
func (u *BroadcastUpsertOne) SetApprovedBy(v string) *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetApprovedBy(v)
	})
}

// UpdateApprovedBy sets the "approved_by" field to the value that was provided on create.
func (u *BroadcastUpsertOne) UpdateApprovedBy() *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateApprovedBy()
	})
}

// ClearApprovedBy clears the value of the "approved_by" field.
func (u *BroadcastUpsertOne) ClearApprovedBy() *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.ClearApprovedBy()
	})
}

// SetApprovedAt sets the "approved_at" field.
func (u *BroadcastUpsertOne) SetApprovedAt(v time.Time) *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetApprovedAt(v)
	})
}

// UpdateApprovedAt sets the "approved_at" field to the value that was provided on create.
func (u *BroadcastUpsertOne) UpdateApprovedAt() *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateApprovedAt()
	})
}

// ClearApprovedAt clears the value of the "approved_at" field.
func (u *BroadcastUpsertOne) ClearApprovedAt() *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.ClearApprovedAt()
	})
}

// SetTargetCount sets the "target_count" field.
func (u *BroadcastUpsertOne) SetTargetCount(v int) *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetTargetCount(v)
	})
}

// AddTargetCount adds v to the "target_count" field.
func (u *BroadcastUpsertOne) AddTargetCount(v int) *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.AddTargetCount(v)
	})
}

// UpdateTargetCount sets the "target_count" field to the value that was provided on create.
func (u *BroadcastUpsertOne) UpdateTargetCount() *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateTargetCount()
	})
}

// SetSentCount sets the "sent_count" field.
func (u *BroadcastUpsertOne) SetSentCount(v int) *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetSentCount(v)
	})
}

// AddSentCount adds v to the "sent_count" field.
func (u *BroadcastUpsertOne) AddSentCount(v int) *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.AddSentCount(v)
	})
}

// UpdateSentCount sets the "sent_count" field to the value that was provided on create.
func (u *BroadcastUpsertOne) UpdateSentCount() *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateSentCount()
	})
}

// SetFailedCount sets the "failed_count" field.
func (u *BroadcastUpsertOne) SetFailedCount(v int) *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetFailedCount(v)
	})
}

// AddFailedCount adds v to the "failed_count" field.
func (u *BroadcastUpsertOne) AddFailedCount(v int) *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.AddFailedCount(v)
	})
}

// UpdateFailedCount sets the "failed_count" field to the value that was provided on create.
func (u *BroadcastUpsertOne) UpdateFailedCount() *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateFailedCount()
	})
}

// SetSkippedCount sets the "skipped_count" field.
func (u *BroadcastUpsertOne) SetSkippedCount(v int) *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetSkippedCount(v)
	})
}

// AddSkippedCount adds v to the "skipped_count" field.
func (u *BroadcastUpsertOne) AddSkippedCount(v int) *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.AddSkippedCount(v)
	})
}

// UpdateSkippedCount sets the "skipped_count" field to the value that was provided on create.
func (u *BroadcastUpsertOne) UpdateSkippedCount() *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateSkippedCount()
	})
}

// SetSuppressedCount sets the "suppressed_count" field.
func (u *BroadcastUpsertOne) SetSuppressedCount(v int) *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetSuppressedCount(v)
	})
}

// AddSuppressedCount adds v to the "suppressed_count" field.
func (u *BroadcastUpsertOne) AddSuppressedCount(v int) *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.AddSuppressedCount(v)
	})
}

// UpdateSuppressedCount sets the "suppressed_count" field to the value that was provided on create.
func (u *BroadcastUpsertOne) UpdateSuppressedCount() *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateSuppressedCount()
	})
}

// SetMetadata sets the "metadata" field.
func (u *BroadcastUpsertOne) SetMetadata(v map[string]interface{}) *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *BroadcastUpsertOne) UpdateMetadata() *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *BroadcastUpsertOne) ClearMetadata() *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.ClearMetadata()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *BroadcastUpsertOne) SetCompletedAt(v time.Time) *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *BroadcastUpsertOne) UpdateCompletedAt() *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *BroadcastUpsertOne) ClearCompletedAt() *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.ClearCompletedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BroadcastUpsertOne) SetUpdatedAt(v time.Time) *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BroadcastUpsertOne) UpdateUpdatedAt() *BroadcastUpsertOne {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *BroadcastUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BroadcastCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BroadcastUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BroadcastUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: BroadcastUpsertOne.ID is not supported by MySQL driver. Use BroadcastUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BroadcastUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BroadcastCreateBulk is the builder for creating many Broadcast entities in bulk.
type BroadcastCreateBulk struct {
	config
	err      error
	builders []*BroadcastCreate
	conflict []sql.ConflictOption
}

// Save creates the Broadcast entities in the database.
func (_c *BroadcastCreateBulk) Save(ctx context.Context) ([]*Broadcast, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Broadcast, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BroadcastMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BroadcastCreateBulk) SaveX(ctx context.Context) []*Broadcast {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BroadcastCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BroadcastCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Broadcast.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BroadcastUpsert) {
//			SetScope(v+v).
//		}).
//		Exec(ctx)
func (_c *BroadcastCreateBulk) OnConflict(opts ...sql.ConflictOption) *BroadcastUpsertBulk {
	_c.conflict = opts
	return &BroadcastUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Broadcast.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BroadcastCreateBulk) OnConflictColumns(columns ...string) *BroadcastUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BroadcastUpsertBulk{
		create: _c,
	}
}

// BroadcastUpsertBulk is the builder for "upsert"-ing
// a bulk of Broadcast nodes.
type BroadcastUpsertBulk struct {
	create *BroadcastCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Broadcast.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(broadcast.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *BroadcastUpsertBulk) UpdateNewValues() *BroadcastUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(broadcast.FieldID)
			}
			if _, exists := b.mutation.Scope(); exists {
				s.SetIgnore(broadcast.FieldScope)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(broadcast.FieldTenantID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(broadcast.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Broadcast.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BroadcastUpsertBulk) Ignore() *BroadcastUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BroadcastUpsertBulk) DoNothing() *BroadcastUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BroadcastCreateBulk.OnConflict
// documentation for more info.
func (u *BroadcastUpsertBulk) Update(set func(*BroadcastUpsert)) *BroadcastUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BroadcastUpsert{UpdateSet: update})
	}))
	return u
}

// SetKind sets the "kind" field.
func (u *BroadcastUpsertBulk) SetKind(v broadcast.Kind) *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *BroadcastUpsertBulk) UpdateKind() *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateKind()
	})
}

// SetClass sets the "class" field.
func (u *BroadcastUpsertBulk) SetClass(v broadcast.Class) *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetClass(v)
	})
}

// UpdateClass sets the "class" field to the value that was provided on create.
func (u *BroadcastUpsertBulk) UpdateClass() *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateClass()
	})
}

// SetStatus sets the "status" field.
func (u *BroadcastUpsertBulk) SetStatus(v broadcast.Status) *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *BroadcastUpsertBulk) UpdateStatus() *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateStatus()
	})
}

// SetTitle sets the "title" field.
func (u *BroadcastUpsertBulk) SetTitle(v string) *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *BroadcastUpsertBulk) UpdateTitle() *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateTitle()
	})
}

// SetChannels sets the "channels" field.
func (u *BroadcastUpsertBulk) SetChannels(v []string) *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetChannels(v)
	})
}

// UpdateChannels sets the "channels" field to the value that was provided on create.
func (u *BroadcastUpsertBulk) UpdateChannels() *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateChannels()
	})
}

// SetContent sets the "content" field.
func (u *BroadcastUpsertBulk) SetContent(v map[string]interface{}) *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *BroadcastUpsertBulk) UpdateContent() *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateContent()
	})
}

// SetAudience sets the "audience" field.
func (u *BroadcastUpsertBulk) SetAudience(v map[string]interface{}) *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetAudience(v)
	})
}

// UpdateAudience sets the "audience" field to the value that was provided on create.
func (u *BroadcastUpsertBulk) UpdateAudience() *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateAudience()
	})
}

// SetSendAt sets the "send_at" field.
func (u *BroadcastUpsertBulk) SetSendAt(v time.Time) *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetSendAt(v)
	})
}

// UpdateSendAt sets the "send_at" field to the value that was provided on create.
func (u *BroadcastUpsertBulk) UpdateSendAt() *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateSendAt()
	})
}

// ClearSendAt clears the value of the "send_at" field.
func (u *BroadcastUpsertBulk) ClearSendAt() *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.ClearSendAt()
	})
}

// SetOccasionID sets the "occasion_id" field.
func (u *BroadcastUpsertBulk) SetOccasionID(v uuid.UUID) *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetOccasionID(v)
	})
}

// UpdateOccasionID sets the "occasion_id" field to the value that was provided on create.
func (u *BroadcastUpsertBulk) UpdateOccasionID() *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateOccasionID()
	})
}

// ClearOccasionID clears the value of the "occasion_id" field.
func (u *BroadcastUpsertBulk) ClearOccasionID() *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.ClearOccasionID()
	})
}

// SetOccasionYear sets the "occasion_year" field.
func (u *BroadcastUpsertBulk) SetOccasionYear(v int) *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetOccasionYear(v)
	})
}

// AddOccasionYear adds v to the "occasion_year" field.
func (u *BroadcastUpsertBulk) AddOccasionYear(v int) *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.AddOccasionYear(v)
	})
}

// UpdateOccasionYear sets the "occasion_year" field to the value that was provided on create.
func (u *BroadcastUpsertBulk) UpdateOccasionYear() *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateOccasionYear()
	})
}

// ClearOccasionYear clears the value of the "occasion_year" field.
func (u *BroadcastUpsertBulk) ClearOccasionYear() *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.ClearOccasionYear()
	})
}

// SetRequestedBy sets the "requested_by" field.
func (u *BroadcastUpsertBulk) SetRequestedBy(v string) *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetRequestedBy(v)
	})
}

// UpdateRequestedBy sets the "requested_by" field to the value that was provided on create.
func (u *BroadcastUpsertBulk) UpdateRequestedBy() *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateRequestedBy()
	})
}

// ClearRequestedBy clears the value of the "requested_by" field.
func (u *BroadcastUpsertBulk) ClearRequestedBy() *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.ClearRequestedBy()
	})
}

// SetApprovedBy sets the "approved_by" field.
func (u *BroadcastUpsertBulk) SetApprovedBy(v string) *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetApprovedBy(v)
	})
}

// UpdateApprovedBy sets the "approved_by" field to the value that was provided on create.
func (u *BroadcastUpsertBulk) UpdateApprovedBy() *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateApprovedBy()
	})
}

// ClearApprovedBy clears the value of the "approved_by" field.
func (u *BroadcastUpsertBulk) ClearApprovedBy() *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.ClearApprovedBy()
	})
}

// SetApprovedAt sets the "approved_at" field.
func (u *BroadcastUpsertBulk) SetApprovedAt(v time.Time) *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetApprovedAt(v)
	})
}

// UpdateApprovedAt sets the "approved_at" field to the value that was provided on create.
func (u *BroadcastUpsertBulk) UpdateApprovedAt() *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateApprovedAt()
	})
}

// ClearApprovedAt clears the value of the "approved_at" field.
func (u *BroadcastUpsertBulk) ClearApprovedAt() *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.ClearApprovedAt()
	})
}

// SetTargetCount sets the "target_count" field.
func (u *BroadcastUpsertBulk) SetTargetCount(v int) *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetTargetCount(v)
	})
}

// AddTargetCount adds v to the "target_count" field.
func (u *BroadcastUpsertBulk) AddTargetCount(v int) *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.AddTargetCount(v)
	})
}

// UpdateTargetCount sets the "target_count" field to the value that was provided on create.
func (u *BroadcastUpsertBulk) UpdateTargetCount() *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateTargetCount()
	})
}

// SetSentCount sets the "sent_count" field.
func (u *BroadcastUpsertBulk) SetSentCount(v int) *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetSentCount(v)
	})
}

// AddSentCount adds v to the "sent_count" field.
func (u *BroadcastUpsertBulk) AddSentCount(v int) *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.AddSentCount(v)
	})
}

// UpdateSentCount sets the "sent_count" field to the value that was provided on create.
func (u *BroadcastUpsertBulk) UpdateSentCount() *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateSentCount()
	})
}

// SetFailedCount sets the "failed_count" field.
func (u *BroadcastUpsertBulk) SetFailedCount(v int) *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetFailedCount(v)
	})
}

// AddFailedCount adds v to the "failed_count" field.
func (u *BroadcastUpsertBulk) AddFailedCount(v int) *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.AddFailedCount(v)
	})
}

// UpdateFailedCount sets the "failed_count" field to the value that was provided on create.
func (u *BroadcastUpsertBulk) UpdateFailedCount() *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateFailedCount()
	})
}

// SetSkippedCount sets the "skipped_count" field.
func (u *BroadcastUpsertBulk) SetSkippedCount(v int) *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetSkippedCount(v)
	})
}

// AddSkippedCount adds v to the "skipped_count" field.
func (u *BroadcastUpsertBulk) AddSkippedCount(v int) *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.AddSkippedCount(v)
	})
}

// UpdateSkippedCount sets the "skipped_count" field to the value that was provided on create.
func (u *BroadcastUpsertBulk) UpdateSkippedCount() *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateSkippedCount()
	})
}

// SetSuppressedCount sets the "suppressed_count" field.
func (u *BroadcastUpsertBulk) SetSuppressedCount(v int) *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetSuppressedCount(v)
	})
}

// AddSuppressedCount adds v to the "suppressed_count" field.
func (u *BroadcastUpsertBulk) AddSuppressedCount(v int) *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.AddSuppressedCount(v)
	})
}

// UpdateSuppressedCount sets the "suppressed_count" field to the value that was provided on create.
func (u *BroadcastUpsertBulk) UpdateSuppressedCount() *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateSuppressedCount()
	})
}

// SetMetadata sets the "metadata" field.
func (u *BroadcastUpsertBulk) SetMetadata(v map[string]interface{}) *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *BroadcastUpsertBulk) UpdateMetadata() *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *BroadcastUpsertBulk) ClearMetadata() *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.ClearMetadata()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *BroadcastUpsertBulk) SetCompletedAt(v time.Time) *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *BroadcastUpsertBulk) UpdateCompletedAt() *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *BroadcastUpsertBulk) ClearCompletedAt() *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.ClearCompletedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BroadcastUpsertBulk) SetUpdatedAt(v time.Time) *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BroadcastUpsertBulk) UpdateUpdatedAt() *BroadcastUpsertBulk {
	return u.Update(func(s *BroadcastUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *BroadcastUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BroadcastCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BroadcastCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BroadcastUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
