// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/notifications-api/internal/ent/notificationpermission"
	"github.com/bengobox/notifications-api/internal/ent/notificationrole"
	"github.com/bengobox/notifications-api/internal/ent/notificationrolepermission"
	"github.com/google/uuid"
)

// NotificationRolePermissionCreate is the builder for creating a NotificationRolePermission entity.
type NotificationRolePermissionCreate struct {
	config
	mutation *NotificationRolePermissionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRoleID sets the "role_id" field.
func (_c *NotificationRolePermissionCreate) SetRoleID(v uuid.UUID) *NotificationRolePermissionCreate {
	_c.mutation.SetRoleID(v)
	return _c
}

// SetPermissionID sets the "permission_id" field.
func (_c *NotificationRolePermissionCreate) SetPermissionID(v uuid.UUID) *NotificationRolePermissionCreate {
	_c.mutation.SetPermissionID(v)
	return _c
}

// SetRole sets the "role" edge to the NotificationRole entity.
func (_c *NotificationRolePermissionCreate) SetRole(v *NotificationRole) *NotificationRolePermissionCreate {
	return _c.SetRoleID(v.ID)
}

// SetPermission sets the "permission" edge to the NotificationPermission entity.
func (_c *NotificationRolePermissionCreate) SetPermission(v *NotificationPermission) *NotificationRolePermissionCreate {
	return _c.SetPermissionID(v.ID)
}

// Mutation returns the NotificationRolePermissionMutation object of the builder.
func (_c *NotificationRolePermissionCreate) Mutation() *NotificationRolePermissionMutation {
	return _c.mutation
}

// Save creates the NotificationRolePermission in the database.
func (_c *NotificationRolePermissionCreate) Save(ctx context.Context) (*NotificationRolePermission, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NotificationRolePermissionCreate) SaveX(ctx context.Context) *NotificationRolePermission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationRolePermissionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationRolePermissionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NotificationRolePermissionCreate) check() error {
	if _, ok := _c.mutation.RoleID(); !ok {
		return &ValidationError{Name: "role_id", err: errors.New(`ent: missing required field "NotificationRolePermission.role_id"`)}
	}
	if _, ok := _c.mutation.PermissionID(); !ok {
		return &ValidationError{Name: "permission_id", err: errors.New(`ent: missing required field "NotificationRolePermission.permission_id"`)}
	}
	if len(_c.mutation.RoleIDs()) == 0 {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required edge "NotificationRolePermission.role"`)}
	}
	if len(_c.mutation.PermissionIDs()) == 0 {
		return &ValidationError{Name: "permission", err: errors.New(`ent: missing required edge "NotificationRolePermission.permission"`)}
	}
	return nil
}

func (_c *NotificationRolePermissionCreate) sqlSave(ctx context.Context) (*NotificationRolePermission, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NotificationRolePermissionCreate) createSpec() (*NotificationRolePermission, *sqlgraph.CreateSpec) {
	var (
		_node = &NotificationRolePermission{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(notificationrolepermission.Table, sqlgraph.NewFieldSpec(notificationrolepermission.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if nodes := _c.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   notificationrolepermission.RoleTable,
			Columns: []string{notificationrolepermission.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationrole.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RoleID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PermissionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   notificationrolepermission.PermissionTable,
			Columns: []string{notificationrolepermission.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationpermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PermissionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NotificationRolePermission.Create().
//		SetRoleID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NotificationRolePermissionUpsert) {
//			SetRoleID(v+v).
//		}).
//		Exec(ctx)
func (_c *NotificationRolePermissionCreate) OnConflict(opts ...sql.ConflictOption) *NotificationRolePermissionUpsertOne {
	_c.conflict = opts
	return &NotificationRolePermissionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NotificationRolePermission.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NotificationRolePermissionCreate) OnConflictColumns(columns ...string) *NotificationRolePermissionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NotificationRolePermissionUpsertOne{
		create: _c,
	}
}

type (
	// NotificationRolePermissionUpsertOne is the builder for "upsert"-ing
	//  one NotificationRolePermission node.
	NotificationRolePermissionUpsertOne struct {
		create *NotificationRolePermissionCreate
	}

	// NotificationRolePermissionUpsert is the "OnConflict" setter.
	NotificationRolePermissionUpsert struct {
		*sql.UpdateSet
	}
)

// SetRoleID sets the "role_id" field.
func (u *NotificationRolePermissionUpsert) SetRoleID(v uuid.UUID) *NotificationRolePermissionUpsert {
	u.Set(notificationrolepermission.FieldRoleID, v)
	return u
}

// UpdateRoleID sets the "role_id" field to the value that was provided on create.
func (u *NotificationRolePermissionUpsert) UpdateRoleID() *NotificationRolePermissionUpsert {
	u.SetExcluded(notificationrolepermission.FieldRoleID)
	return u
}

// SetPermissionID sets the "permission_id" field.
func (u *NotificationRolePermissionUpsert) SetPermissionID(v uuid.UUID) *NotificationRolePermissionUpsert {
	u.Set(notificationrolepermission.FieldPermissionID, v)
	return u
}

// UpdatePermissionID sets the "permission_id" field to the value that was provided on create.
func (u *NotificationRolePermissionUpsert) UpdatePermissionID() *NotificationRolePermissionUpsert {
	u.SetExcluded(notificationrolepermission.FieldPermissionID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.NotificationRolePermission.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *NotificationRolePermissionUpsertOne) UpdateNewValues() *NotificationRolePermissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NotificationRolePermission.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *NotificationRolePermissionUpsertOne) Ignore() *NotificationRolePermissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NotificationRolePermissionUpsertOne) DoNothing() *NotificationRolePermissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NotificationRolePermissionCreate.OnConflict
// documentation for more info.
func (u *NotificationRolePermissionUpsertOne) Update(set func(*NotificationRolePermissionUpsert)) *NotificationRolePermissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NotificationRolePermissionUpsert{UpdateSet: update})
	}))
	return u
}

// SetRoleID sets the "role_id" field.
func (u *NotificationRolePermissionUpsertOne) SetRoleID(v uuid.UUID) *NotificationRolePermissionUpsertOne {
	return u.Update(func(s *NotificationRolePermissionUpsert) {
		s.SetRoleID(v)
	})
}

// UpdateRoleID sets the "role_id" field to the value that was provided on create.
func (u *NotificationRolePermissionUpsertOne) UpdateRoleID() *NotificationRolePermissionUpsertOne {
	return u.Update(func(s *NotificationRolePermissionUpsert) {
		s.UpdateRoleID()
	})
}

// SetPermissionID sets the "permission_id" field.
func (u *NotificationRolePermissionUpsertOne) SetPermissionID(v uuid.UUID) *NotificationRolePermissionUpsertOne {
	return u.Update(func(s *NotificationRolePermissionUpsert) {
		s.SetPermissionID(v)
	})
}

// UpdatePermissionID sets the "permission_id" field to the value that was provided on create.
func (u *NotificationRolePermissionUpsertOne) UpdatePermissionID() *NotificationRolePermissionUpsertOne {
	return u.Update(func(s *NotificationRolePermissionUpsert) {
		s.UpdatePermissionID()
	})
}

// Exec executes the query.
func (u *NotificationRolePermissionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NotificationRolePermissionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NotificationRolePermissionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *NotificationRolePermissionUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *NotificationRolePermissionUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// NotificationRolePermissionCreateBulk is the builder for creating many NotificationRolePermission entities in bulk.
type NotificationRolePermissionCreateBulk struct {
	config
	err      error
	builders []*NotificationRolePermissionCreate
	conflict []sql.ConflictOption
}

// Save creates the NotificationRolePermission entities in the database.
func (_c *NotificationRolePermissionCreateBulk) Save(ctx context.Context) ([]*NotificationRolePermission, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NotificationRolePermission, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NotificationRolePermissionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NotificationRolePermissionCreateBulk) SaveX(ctx context.Context) []*NotificationRolePermission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationRolePermissionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationRolePermissionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NotificationRolePermission.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NotificationRolePermissionUpsert) {
//			SetRoleID(v+v).
//		}).
//		Exec(ctx)
func (_c *NotificationRolePermissionCreateBulk) OnConflict(opts ...sql.ConflictOption) *NotificationRolePermissionUpsertBulk {
	_c.conflict = opts
	return &NotificationRolePermissionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NotificationRolePermission.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NotificationRolePermissionCreateBulk) OnConflictColumns(columns ...string) *NotificationRolePermissionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NotificationRolePermissionUpsertBulk{
		create: _c,
	}
}

// NotificationRolePermissionUpsertBulk is the builder for "upsert"-ing
// a bulk of NotificationRolePermission nodes.
type NotificationRolePermissionUpsertBulk struct {
	create *NotificationRolePermissionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.NotificationRolePermission.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *NotificationRolePermissionUpsertBulk) UpdateNewValues() *NotificationRolePermissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NotificationRolePermission.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *NotificationRolePermissionUpsertBulk) Ignore() *NotificationRolePermissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NotificationRolePermissionUpsertBulk) DoNothing() *NotificationRolePermissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NotificationRolePermissionCreateBulk.OnConflict
// documentation for more info.
func (u *NotificationRolePermissionUpsertBulk) Update(set func(*NotificationRolePermissionUpsert)) *NotificationRolePermissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NotificationRolePermissionUpsert{UpdateSet: update})
	}))
	return u
}

// SetRoleID sets the "role_id" field.
func (u *NotificationRolePermissionUpsertBulk) SetRoleID(v uuid.UUID) *NotificationRolePermissionUpsertBulk {
	return u.Update(func(s *NotificationRolePermissionUpsert) {
		s.SetRoleID(v)
	})
}

// UpdateRoleID sets the "role_id" field to the value that was provided on create.
func (u *NotificationRolePermissionUpsertBulk) UpdateRoleID() *NotificationRolePermissionUpsertBulk {
	return u.Update(func(s *NotificationRolePermissionUpsert) {
		s.UpdateRoleID()
	})
}

// SetPermissionID sets the "permission_id" field.
func (u *NotificationRolePermissionUpsertBulk) SetPermissionID(v uuid.UUID) *NotificationRolePermissionUpsertBulk {
	return u.Update(func(s *NotificationRolePermissionUpsert) {
		s.SetPermissionID(v)
	})
}

// UpdatePermissionID sets the "permission_id" field to the value that was provided on create.
func (u *NotificationRolePermissionUpsertBulk) UpdatePermissionID() *NotificationRolePermissionUpsertBulk {
	return u.Update(func(s *NotificationRolePermissionUpsert) {
		s.UpdatePermissionID()
	})
}

// Exec executes the query.
func (u *NotificationRolePermissionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the NotificationRolePermissionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NotificationRolePermissionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NotificationRolePermissionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
