// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/notifications-api/internal/ent/notificationrolepermission"
	"github.com/bengobox/notifications-api/internal/ent/predicate"
)

// NotificationRolePermissionDelete is the builder for deleting a NotificationRolePermission entity.
type NotificationRolePermissionDelete struct {
	config
	hooks    []Hook
	mutation *NotificationRolePermissionMutation
}

// Where appends a list predicates to the NotificationRolePermissionDelete builder.
func (_d *NotificationRolePermissionDelete) Where(ps ...predicate.NotificationRolePermission) *NotificationRolePermissionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *NotificationRolePermissionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *NotificationRolePermissionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *NotificationRolePermissionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(notificationrolepermission.Table, sqlgraph.NewFieldSpec(notificationrolepermission.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// NotificationRolePermissionDeleteOne is the builder for deleting a single NotificationRolePermission entity.
type NotificationRolePermissionDeleteOne struct {
	_d *NotificationRolePermissionDelete
}

// Where appends a list predicates to the NotificationRolePermissionDelete builder.
func (_d *NotificationRolePermissionDeleteOne) Where(ps ...predicate.NotificationRolePermission) *NotificationRolePermissionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *NotificationRolePermissionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{notificationrolepermission.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *NotificationRolePermissionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
