// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/notifications-api/internal/ent/notificationpermission"
	"github.com/bengobox/notifications-api/internal/ent/notificationrole"
	"github.com/bengobox/notifications-api/internal/ent/notificationrolepermission"
	"github.com/bengobox/notifications-api/internal/ent/predicate"
	"github.com/google/uuid"
)

// NotificationRolePermissionUpdate is the builder for updating NotificationRolePermission entities.
type NotificationRolePermissionUpdate struct {
	config
	hooks     []Hook
	mutation  *NotificationRolePermissionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the NotificationRolePermissionUpdate builder.
func (_u *NotificationRolePermissionUpdate) Where(ps ...predicate.NotificationRolePermission) *NotificationRolePermissionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *NotificationRolePermissionUpdate) SetRoleID(v uuid.UUID) *NotificationRolePermissionUpdate {
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *NotificationRolePermissionUpdate) SetNillableRoleID(v *uuid.UUID) *NotificationRolePermissionUpdate {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// SetPermissionID sets the "permission_id" field.
func (_u *NotificationRolePermissionUpdate) SetPermissionID(v uuid.UUID) *NotificationRolePermissionUpdate {
	_u.mutation.SetPermissionID(v)
	return _u
}

// SetNillablePermissionID sets the "permission_id" field if the given value is not nil.
func (_u *NotificationRolePermissionUpdate) SetNillablePermissionID(v *uuid.UUID) *NotificationRolePermissionUpdate {
	if v != nil {
		_u.SetPermissionID(*v)
	}
	return _u
}

// SetRole sets the "role" edge to the NotificationRole entity.
func (_u *NotificationRolePermissionUpdate) SetRole(v *NotificationRole) *NotificationRolePermissionUpdate {
	return _u.SetRoleID(v.ID)
}

// SetPermission sets the "permission" edge to the NotificationPermission entity.
func (_u *NotificationRolePermissionUpdate) SetPermission(v *NotificationPermission) *NotificationRolePermissionUpdate {
	return _u.SetPermissionID(v.ID)
}

// Mutation returns the NotificationRolePermissionMutation object of the builder.
func (_u *NotificationRolePermissionUpdate) Mutation() *NotificationRolePermissionMutation {
	return _u.mutation
}

// ClearRole clears the "role" edge to the NotificationRole entity.
func (_u *NotificationRolePermissionUpdate) ClearRole() *NotificationRolePermissionUpdate {
	_u.mutation.ClearRole()
	return _u
}

// ClearPermission clears the "permission" edge to the NotificationPermission entity.
func (_u *NotificationRolePermissionUpdate) ClearPermission() *NotificationRolePermissionUpdate {
	_u.mutation.ClearPermission()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NotificationRolePermissionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationRolePermissionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NotificationRolePermissionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationRolePermissionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationRolePermissionUpdate) check() error {
	if _u.mutation.RoleCleared() && len(_u.mutation.RoleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NotificationRolePermission.role"`)
	}
	if _u.mutation.PermissionCleared() && len(_u.mutation.PermissionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NotificationRolePermission.permission"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *NotificationRolePermissionUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *NotificationRolePermissionUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *NotificationRolePermissionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notificationrolepermission.Table, notificationrolepermission.Columns, sqlgraph.NewFieldSpec(notificationrolepermission.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   notificationrolepermission.RoleTable,
			Columns: []string{notificationrolepermission.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationrole.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   notificationrolepermission.RoleTable,
			Columns: []string{notificationrolepermission.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationrole.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PermissionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   notificationrolepermission.PermissionTable,
			Columns: []string{notificationrolepermission.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationpermission.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PermissionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   notificationrolepermission.PermissionTable,
			Columns: []string{notificationrolepermission.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationpermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationrolepermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NotificationRolePermissionUpdateOne is the builder for updating a single NotificationRolePermission entity.
type NotificationRolePermissionUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *NotificationRolePermissionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetRoleID sets the "role_id" field.
func (_u *NotificationRolePermissionUpdateOne) SetRoleID(v uuid.UUID) *NotificationRolePermissionUpdateOne {
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *NotificationRolePermissionUpdateOne) SetNillableRoleID(v *uuid.UUID) *NotificationRolePermissionUpdateOne {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// SetPermissionID sets the "permission_id" field.
func (_u *NotificationRolePermissionUpdateOne) SetPermissionID(v uuid.UUID) *NotificationRolePermissionUpdateOne {
	_u.mutation.SetPermissionID(v)
	return _u
}

// SetNillablePermissionID sets the "permission_id" field if the given value is not nil.
func (_u *NotificationRolePermissionUpdateOne) SetNillablePermissionID(v *uuid.UUID) *NotificationRolePermissionUpdateOne {
	if v != nil {
		_u.SetPermissionID(*v)
	}
	return _u
}

// SetRole sets the "role" edge to the NotificationRole entity.
func (_u *NotificationRolePermissionUpdateOne) SetRole(v *NotificationRole) *NotificationRolePermissionUpdateOne {
	return _u.SetRoleID(v.ID)
}

// SetPermission sets the "permission" edge to the NotificationPermission entity.
func (_u *NotificationRolePermissionUpdateOne) SetPermission(v *NotificationPermission) *NotificationRolePermissionUpdateOne {
	return _u.SetPermissionID(v.ID)
}

// Mutation returns the NotificationRolePermissionMutation object of the builder.
func (_u *NotificationRolePermissionUpdateOne) Mutation() *NotificationRolePermissionMutation {
	return _u.mutation
}

// ClearRole clears the "role" edge to the NotificationRole entity.
func (_u *NotificationRolePermissionUpdateOne) ClearRole() *NotificationRolePermissionUpdateOne {
	_u.mutation.ClearRole()
	return _u
}

// ClearPermission clears the "permission" edge to the NotificationPermission entity.
func (_u *NotificationRolePermissionUpdateOne) ClearPermission() *NotificationRolePermissionUpdateOne {
	_u.mutation.ClearPermission()
	return _u
}

// Where appends a list predicates to the NotificationRolePermissionUpdate builder.
func (_u *NotificationRolePermissionUpdateOne) Where(ps ...predicate.NotificationRolePermission) *NotificationRolePermissionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NotificationRolePermissionUpdateOne) Select(field string, fields ...string) *NotificationRolePermissionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated NotificationRolePermission entity.
func (_u *NotificationRolePermissionUpdateOne) Save(ctx context.Context) (*NotificationRolePermission, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationRolePermissionUpdateOne) SaveX(ctx context.Context) *NotificationRolePermission {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NotificationRolePermissionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationRolePermissionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationRolePermissionUpdateOne) check() error {
	if _u.mutation.RoleCleared() && len(_u.mutation.RoleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NotificationRolePermission.role"`)
	}
	if _u.mutation.PermissionCleared() && len(_u.mutation.PermissionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NotificationRolePermission.permission"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *NotificationRolePermissionUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *NotificationRolePermissionUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *NotificationRolePermissionUpdateOne) sqlSave(ctx context.Context) (_node *NotificationRolePermission, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notificationrolepermission.Table, notificationrolepermission.Columns, sqlgraph.NewFieldSpec(notificationrolepermission.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NotificationRolePermission.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notificationrolepermission.FieldID)
		for _, f := range fields {
			if !notificationrolepermission.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notificationrolepermission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   notificationrolepermission.RoleTable,
			Columns: []string{notificationrolepermission.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationrole.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   notificationrolepermission.RoleTable,
			Columns: []string{notificationrolepermission.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationrole.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PermissionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   notificationrolepermission.PermissionTable,
			Columns: []string{notificationrolepermission.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationpermission.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PermissionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   notificationrolepermission.PermissionTable,
			Columns: []string{notificationrolepermission.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationpermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &NotificationRolePermission{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationrolepermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
