// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/notifications-api/internal/ent/notificationpermission"
	"github.com/bengobox/notifications-api/internal/ent/notificationrole"
	"github.com/bengobox/notifications-api/internal/ent/notificationrolepermission"
	"github.com/google/uuid"
)

// NotificationRolePermission is the model entity for the NotificationRolePermission schema.
type NotificationRolePermission struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Role identifier
	RoleID uuid.UUID `json:"role_id,omitempty"`
	// Permission identifier
	PermissionID uuid.UUID `json:"permission_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the NotificationRolePermissionQuery when eager-loading is set.
	Edges        NotificationRolePermissionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// NotificationRolePermissionEdges holds the relations/edges for other nodes in the graph.
type NotificationRolePermissionEdges struct {
	// Role holds the value of the role edge.
	Role *NotificationRole `json:"role,omitempty"`
	// Permission holds the value of the permission edge.
	Permission *NotificationPermission `json:"permission,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// RoleOrErr returns the Role value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NotificationRolePermissionEdges) RoleOrErr() (*NotificationRole, error) {
	if e.Role != nil {
		return e.Role, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: notificationrole.Label}
	}
	return nil, &NotLoadedError{edge: "role"}
}

// PermissionOrErr returns the Permission value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NotificationRolePermissionEdges) PermissionOrErr() (*NotificationPermission, error) {
	if e.Permission != nil {
		return e.Permission, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: notificationpermission.Label}
	}
	return nil, &NotLoadedError{edge: "permission"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NotificationRolePermission) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case notificationrolepermission.FieldID:
			values[i] = new(sql.NullInt64)
		case notificationrolepermission.FieldRoleID, notificationrolepermission.FieldPermissionID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NotificationRolePermission fields.
func (_m *NotificationRolePermission) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case notificationrolepermission.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case notificationrolepermission.FieldRoleID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field role_id", values[i])
			} else if value != nil {
				_m.RoleID = *value
			}
		case notificationrolepermission.FieldPermissionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field permission_id", values[i])
			} else if value != nil {
				_m.PermissionID = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the NotificationRolePermission.
// This includes values selected through modifiers, order, etc.
func (_m *NotificationRolePermission) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRole queries the "role" edge of the NotificationRolePermission entity.
func (_m *NotificationRolePermission) QueryRole() *NotificationRoleQuery {
	return NewNotificationRolePermissionClient(_m.config).QueryRole(_m)
}

// QueryPermission queries the "permission" edge of the NotificationRolePermission entity.
func (_m *NotificationRolePermission) QueryPermission() *NotificationPermissionQuery {
	return NewNotificationRolePermissionClient(_m.config).QueryPermission(_m)
}

// Update returns a builder for updating this NotificationRolePermission.
// Note that you need to call NotificationRolePermission.Unwrap() before calling this method if this NotificationRolePermission
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *NotificationRolePermission) Update() *NotificationRolePermissionUpdateOne {
	return NewNotificationRolePermissionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the NotificationRolePermission entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *NotificationRolePermission) Unwrap() *NotificationRolePermission {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: NotificationRolePermission is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *NotificationRolePermission) String() string {
	var builder strings.Builder
	builder.WriteString("NotificationRolePermission(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("role_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RoleID))
	builder.WriteString(", ")
	builder.WriteString("permission_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PermissionID))
	builder.WriteByte(')')
	return builder.String()
}

// NotificationRolePermissions is a parsable slice of NotificationRolePermission.
type NotificationRolePermissions []*NotificationRolePermission
