// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/notifications-api/internal/ent/occasion"
	"github.com/google/uuid"
)

// Occasion is the model entity for the Occasion schema.
type Occasion struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID *uuid.UUID `json:"tenant_id,omitempty"`
	// Stable slug, e.g. customer_service_week; a tenant row with a catalogue key customises it
	Key string `json:"key,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// ISO country the date belongs to; empty for worldwide
	Country string `json:"country,omitempty"`
	// fixed{month,day} | nth_weekday{month,weekday,n} | first_full_week{month} | easter_offset{days} | explicit{dates:{year:date}}
	Rule map[string]interface{} `json:"rule,omitempty"`
	// DurationDays holds the value of the "duration_days" field.
	DurationDays int `json:"duration_days,omitempty"`
	// How many days ahead the draft is prepared for approval
	LeadDays int `json:"lead_days,omitempty"`
	// Which day of the occasion to send on (0 = first day)
	SendOffsetDays int `json:"send_offset_days,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// variants, channels, audience, auto_send, send_time, whatsapp_template, last_variant
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Occasion) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case occasion.FieldTenantID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case occasion.FieldRule, occasion.FieldMetadata:
			values[i] = new([]byte)
		case occasion.FieldIsActive:
			values[i] = new(sql.NullBool)
		case occasion.FieldDurationDays, occasion.FieldLeadDays, occasion.FieldSendOffsetDays:
			values[i] = new(sql.NullInt64)
		case occasion.FieldKey, occasion.FieldName, occasion.FieldCountry:
			values[i] = new(sql.NullString)
		case occasion.FieldCreatedAt, occasion.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case occasion.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Occasion fields.
func (_m *Occasion) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case occasion.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case occasion.FieldTenantID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = new(uuid.UUID)
				*_m.TenantID = *value.S.(*uuid.UUID)
			}
		case occasion.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				_m.Key = value.String
			}
		case occasion.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case occasion.FieldCountry:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field country", values[i])
			} else if value.Valid {
				_m.Country = value.String
			}
		case occasion.FieldRule:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field rule", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Rule); err != nil {
					return fmt.Errorf("unmarshal field rule: %w", err)
				}
			}
		case occasion.FieldDurationDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_days", values[i])
			} else if value.Valid {
				_m.DurationDays = int(value.Int64)
			}
		case occasion.FieldLeadDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field lead_days", values[i])
			} else if value.Valid {
				_m.LeadDays = int(value.Int64)
			}
		case occasion.FieldSendOffsetDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field send_offset_days", values[i])
			} else if value.Valid {
				_m.SendOffsetDays = int(value.Int64)
			}
		case occasion.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case occasion.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case occasion.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case occasion.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Occasion.
// This includes values selected through modifiers, order, etc.
func (_m *Occasion) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Occasion.
// Note that you need to call Occasion.Unwrap() before calling this method if this Occasion
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Occasion) Update() *OccasionUpdateOne {
	return NewOccasionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Occasion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Occasion) Unwrap() *Occasion {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Occasion is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Occasion) String() string {
	var builder strings.Builder
	builder.WriteString("Occasion(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.TenantID; v != nil {
		builder.WriteString("tenant_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("key=")
	builder.WriteString(_m.Key)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("country=")
	builder.WriteString(_m.Country)
	builder.WriteString(", ")
	builder.WriteString("rule=")
	builder.WriteString(fmt.Sprintf("%v", _m.Rule))
	builder.WriteString(", ")
	builder.WriteString("duration_days=")
	builder.WriteString(fmt.Sprintf("%v", _m.DurationDays))
	builder.WriteString(", ")
	builder.WriteString("lead_days=")
	builder.WriteString(fmt.Sprintf("%v", _m.LeadDays))
	builder.WriteString(", ")
	builder.WriteString("send_offset_days=")
	builder.WriteString(fmt.Sprintf("%v", _m.SendOffsetDays))
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Occasions is a parsable slice of Occasion.
type Occasions []*Occasion
