// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/notifications-api/internal/ent/platformbilling"
	"github.com/bengobox/notifications-api/internal/ent/predicate"
)

// PlatformBillingDelete is the builder for deleting a PlatformBilling entity.
type PlatformBillingDelete struct {
	config
	hooks    []Hook
	mutation *PlatformBillingMutation
}

// Where appends a list predicates to the PlatformBillingDelete builder.
func (_d *PlatformBillingDelete) Where(ps ...predicate.PlatformBilling) *PlatformBillingDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PlatformBillingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PlatformBillingDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PlatformBillingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(platformbilling.Table, sqlgraph.NewFieldSpec(platformbilling.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PlatformBillingDeleteOne is the builder for deleting a single PlatformBilling entity.
type PlatformBillingDeleteOne struct {
	_d *PlatformBillingDelete
}

// Where appends a list predicates to the PlatformBillingDelete builder.
func (_d *PlatformBillingDeleteOne) Where(ps ...predicate.PlatformBilling) *PlatformBillingDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PlatformBillingDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{platformbilling.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PlatformBillingDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
