// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/notifications-api/internal/ent/platformbilling"
	"github.com/google/uuid"
)

// PlatformBillingCreate is the builder for creating a PlatformBilling entity.
type PlatformBillingCreate struct {
	config
	mutation *PlatformBillingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCostPerSms sets the "cost_per_sms" field.
func (_c *PlatformBillingCreate) SetCostPerSms(v float64) *PlatformBillingCreate {
	_c.mutation.SetCostPerSms(v)
	return _c
}

// SetNillableCostPerSms sets the "cost_per_sms" field if the given value is not nil.
func (_c *PlatformBillingCreate) SetNillableCostPerSms(v *float64) *PlatformBillingCreate {
	if v != nil {
		_c.SetCostPerSms(*v)
	}
	return _c
}

// SetCostPerWhatsapp sets the "cost_per_whatsapp" field.
func (_c *PlatformBillingCreate) SetCostPerWhatsapp(v float64) *PlatformBillingCreate {
	_c.mutation.SetCostPerWhatsapp(v)
	return _c
}

// SetNillableCostPerWhatsapp sets the "cost_per_whatsapp" field if the given value is not nil.
func (_c *PlatformBillingCreate) SetNillableCostPerWhatsapp(v *float64) *PlatformBillingCreate {
	if v != nil {
		_c.SetCostPerWhatsapp(*v)
	}
	return _c
}

// SetProviderCostPerSms sets the "provider_cost_per_sms" field.
func (_c *PlatformBillingCreate) SetProviderCostPerSms(v float64) *PlatformBillingCreate {
	_c.mutation.SetProviderCostPerSms(v)
	return _c
}

// SetNillableProviderCostPerSms sets the "provider_cost_per_sms" field if the given value is not nil.
func (_c *PlatformBillingCreate) SetNillableProviderCostPerSms(v *float64) *PlatformBillingCreate {
	if v != nil {
		_c.SetProviderCostPerSms(*v)
	}
	return _c
}

// SetProviderCostPerWhatsapp sets the "provider_cost_per_whatsapp" field.
func (_c *PlatformBillingCreate) SetProviderCostPerWhatsapp(v float64) *PlatformBillingCreate {
	_c.mutation.SetProviderCostPerWhatsapp(v)
	return _c
}

// SetNillableProviderCostPerWhatsapp sets the "provider_cost_per_whatsapp" field if the given value is not nil.
func (_c *PlatformBillingCreate) SetNillableProviderCostPerWhatsapp(v *float64) *PlatformBillingCreate {
	if v != nil {
		_c.SetProviderCostPerWhatsapp(*v)
	}
	return _c
}

// SetMinMarkupPercentage sets the "min_markup_percentage" field.
func (_c *PlatformBillingCreate) SetMinMarkupPercentage(v float64) *PlatformBillingCreate {
	_c.mutation.SetMinMarkupPercentage(v)
	return _c
}

// SetNillableMinMarkupPercentage sets the "min_markup_percentage" field if the given value is not nil.
func (_c *PlatformBillingCreate) SetNillableMinMarkupPercentage(v *float64) *PlatformBillingCreate {
	if v != nil {
		_c.SetMinMarkupPercentage(*v)
	}
	return _c
}

// SetMinTopupAmount sets the "min_topup_amount" field.
func (_c *PlatformBillingCreate) SetMinTopupAmount(v float64) *PlatformBillingCreate {
	_c.mutation.SetMinTopupAmount(v)
	return _c
}

// SetNillableMinTopupAmount sets the "min_topup_amount" field if the given value is not nil.
func (_c *PlatformBillingCreate) SetNillableMinTopupAmount(v *float64) *PlatformBillingCreate {
	if v != nil {
		_c.SetMinTopupAmount(*v)
	}
	return _c
}

// SetTreasuryGatewayID sets the "treasury_gateway_id" field.
func (_c *PlatformBillingCreate) SetTreasuryGatewayID(v uuid.UUID) *PlatformBillingCreate {
	_c.mutation.SetTreasuryGatewayID(v)
	return _c
}

// SetNillableTreasuryGatewayID sets the "treasury_gateway_id" field if the given value is not nil.
func (_c *PlatformBillingCreate) SetNillableTreasuryGatewayID(v *uuid.UUID) *PlatformBillingCreate {
	if v != nil {
		_c.SetTreasuryGatewayID(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PlatformBillingCreate) SetUpdatedAt(v time.Time) *PlatformBillingCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PlatformBillingCreate) SetNillableUpdatedAt(v *time.Time) *PlatformBillingCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PlatformBillingCreate) SetID(v uuid.UUID) *PlatformBillingCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PlatformBillingCreate) SetNillableID(v *uuid.UUID) *PlatformBillingCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the PlatformBillingMutation object of the builder.
func (_c *PlatformBillingCreate) Mutation() *PlatformBillingMutation {
	return _c.mutation
}

// Save creates the PlatformBilling in the database.
func (_c *PlatformBillingCreate) Save(ctx context.Context) (*PlatformBilling, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PlatformBillingCreate) SaveX(ctx context.Context) *PlatformBilling {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlatformBillingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlatformBillingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PlatformBillingCreate) defaults() {
	if _, ok := _c.mutation.CostPerSms(); !ok {
		v := platformbilling.DefaultCostPerSms
		_c.mutation.SetCostPerSms(v)
	}
	if _, ok := _c.mutation.CostPerWhatsapp(); !ok {
		v := platformbilling.DefaultCostPerWhatsapp
		_c.mutation.SetCostPerWhatsapp(v)
	}
	if _, ok := _c.mutation.ProviderCostPerSms(); !ok {
		v := platformbilling.DefaultProviderCostPerSms
		_c.mutation.SetProviderCostPerSms(v)
	}
	if _, ok := _c.mutation.ProviderCostPerWhatsapp(); !ok {
		v := platformbilling.DefaultProviderCostPerWhatsapp
		_c.mutation.SetProviderCostPerWhatsapp(v)
	}
	if _, ok := _c.mutation.MinMarkupPercentage(); !ok {
		v := platformbilling.DefaultMinMarkupPercentage
		_c.mutation.SetMinMarkupPercentage(v)
	}
	if _, ok := _c.mutation.MinTopupAmount(); !ok {
		v := platformbilling.DefaultMinTopupAmount
		_c.mutation.SetMinTopupAmount(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := platformbilling.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := platformbilling.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PlatformBillingCreate) check() error {
	if _, ok := _c.mutation.CostPerSms(); !ok {
		return &ValidationError{Name: "cost_per_sms", err: errors.New(`ent: missing required field "PlatformBilling.cost_per_sms"`)}
	}
	if _, ok := _c.mutation.CostPerWhatsapp(); !ok {
		return &ValidationError{Name: "cost_per_whatsapp", err: errors.New(`ent: missing required field "PlatformBilling.cost_per_whatsapp"`)}
	}
	if _, ok := _c.mutation.ProviderCostPerSms(); !ok {
		return &ValidationError{Name: "provider_cost_per_sms", err: errors.New(`ent: missing required field "PlatformBilling.provider_cost_per_sms"`)}
	}
	if _, ok := _c.mutation.ProviderCostPerWhatsapp(); !ok {
		return &ValidationError{Name: "provider_cost_per_whatsapp", err: errors.New(`ent: missing required field "PlatformBilling.provider_cost_per_whatsapp"`)}
	}
	if _, ok := _c.mutation.MinMarkupPercentage(); !ok {
		return &ValidationError{Name: "min_markup_percentage", err: errors.New(`ent: missing required field "PlatformBilling.min_markup_percentage"`)}
	}
	if _, ok := _c.mutation.MinTopupAmount(); !ok {
		return &ValidationError{Name: "min_topup_amount", err: errors.New(`ent: missing required field "PlatformBilling.min_topup_amount"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PlatformBilling.updated_at"`)}
	}
	return nil
}

func (_c *PlatformBillingCreate) sqlSave(ctx context.Context) (*PlatformBilling, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PlatformBillingCreate) createSpec() (*PlatformBilling, *sqlgraph.CreateSpec) {
	var (
		_node = &PlatformBilling{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(platformbilling.Table, sqlgraph.NewFieldSpec(platformbilling.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CostPerSms(); ok {
		_spec.SetField(platformbilling.FieldCostPerSms, field.TypeFloat64, value)
		_node.CostPerSms = value
	}
	if value, ok := _c.mutation.CostPerWhatsapp(); ok {
		_spec.SetField(platformbilling.FieldCostPerWhatsapp, field.TypeFloat64, value)
		_node.CostPerWhatsapp = value
	}
	if value, ok := _c.mutation.ProviderCostPerSms(); ok {
		_spec.SetField(platformbilling.FieldProviderCostPerSms, field.TypeFloat64, value)
		_node.ProviderCostPerSms = value
	}
	if value, ok := _c.mutation.ProviderCostPerWhatsapp(); ok {
		_spec.SetField(platformbilling.FieldProviderCostPerWhatsapp, field.TypeFloat64, value)
		_node.ProviderCostPerWhatsapp = value
	}
	if value, ok := _c.mutation.MinMarkupPercentage(); ok {
		_spec.SetField(platformbilling.FieldMinMarkupPercentage, field.TypeFloat64, value)
		_node.MinMarkupPercentage = value
	}
	if value, ok := _c.mutation.MinTopupAmount(); ok {
		_spec.SetField(platformbilling.FieldMinTopupAmount, field.TypeFloat64, value)
		_node.MinTopupAmount = value
	}
	if value, ok := _c.mutation.TreasuryGatewayID(); ok {
		_spec.SetField(platformbilling.FieldTreasuryGatewayID, field.TypeUUID, value)
		_node.TreasuryGatewayID = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(platformbilling.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PlatformBilling.Create().
//		SetCostPerSms(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PlatformBillingUpsert) {
//			SetCostPerSms(v+v).
//		}).
//		Exec(ctx)
func (_c *PlatformBillingCreate) OnConflict(opts ...sql.ConflictOption) *PlatformBillingUpsertOne {
	_c.conflict = opts
	return &PlatformBillingUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PlatformBilling.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PlatformBillingCreate) OnConflictColumns(columns ...string) *PlatformBillingUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PlatformBillingUpsertOne{
		create: _c,
	}
}

type (
	// PlatformBillingUpsertOne is the builder for "upsert"-ing
	//  one PlatformBilling node.
	PlatformBillingUpsertOne struct {
		create *PlatformBillingCreate
	}

	// PlatformBillingUpsert is the "OnConflict" setter.
	PlatformBillingUpsert struct {
		*sql.UpdateSet
	}
)

// SetCostPerSms sets the "cost_per_sms" field.
func (u *PlatformBillingUpsert) SetCostPerSms(v float64) *PlatformBillingUpsert {
	u.Set(platformbilling.FieldCostPerSms, v)
	return u
}

// UpdateCostPerSms sets the "cost_per_sms" field to the value that was provided on create.
func (u *PlatformBillingUpsert) UpdateCostPerSms() *PlatformBillingUpsert {
	u.SetExcluded(platformbilling.FieldCostPerSms)
	return u
}

// AddCostPerSms adds v to the "cost_per_sms" field.
func (u *PlatformBillingUpsert) AddCostPerSms(v float64) *PlatformBillingUpsert {
	u.Add(platformbilling.FieldCostPerSms, v)
	return u
}

// SetCostPerWhatsapp sets the "cost_per_whatsapp" field.
func (u *PlatformBillingUpsert) SetCostPerWhatsapp(v float64) *PlatformBillingUpsert {
	u.Set(platformbilling.FieldCostPerWhatsapp, v)
	return u
}

// UpdateCostPerWhatsapp sets the "cost_per_whatsapp" field to the value that was provided on create.
func (u *PlatformBillingUpsert) UpdateCostPerWhatsapp() *PlatformBillingUpsert {
	u.SetExcluded(platformbilling.FieldCostPerWhatsapp)
	return u
}

// AddCostPerWhatsapp adds v to the "cost_per_whatsapp" field.
func (u *PlatformBillingUpsert) AddCostPerWhatsapp(v float64) *PlatformBillingUpsert {
	u.Add(platformbilling.FieldCostPerWhatsapp, v)
	return u
}

// SetProviderCostPerSms sets the "provider_cost_per_sms" field.
func (u *PlatformBillingUpsert) SetProviderCostPerSms(v float64) *PlatformBillingUpsert {
	u.Set(platformbilling.FieldProviderCostPerSms, v)
	return u
}

// UpdateProviderCostPerSms sets the "provider_cost_per_sms" field to the value that was provided on create.
func (u *PlatformBillingUpsert) UpdateProviderCostPerSms() *PlatformBillingUpsert {
	u.SetExcluded(platformbilling.FieldProviderCostPerSms)
	return u
}

// AddProviderCostPerSms adds v to the "provider_cost_per_sms" field.
func (u *PlatformBillingUpsert) AddProviderCostPerSms(v float64) *PlatformBillingUpsert {
	u.Add(platformbilling.FieldProviderCostPerSms, v)
	return u
}

// SetProviderCostPerWhatsapp sets the "provider_cost_per_whatsapp" field.
func (u *PlatformBillingUpsert) SetProviderCostPerWhatsapp(v float64) *PlatformBillingUpsert {
	u.Set(platformbilling.FieldProviderCostPerWhatsapp, v)
	return u
}

// UpdateProviderCostPerWhatsapp sets the "provider_cost_per_whatsapp" field to the value that was provided on create.
func (u *PlatformBillingUpsert) UpdateProviderCostPerWhatsapp() *PlatformBillingUpsert {
	u.SetExcluded(platformbilling.FieldProviderCostPerWhatsapp)
	return u
}

// AddProviderCostPerWhatsapp adds v to the "provider_cost_per_whatsapp" field.
func (u *PlatformBillingUpsert) AddProviderCostPerWhatsapp(v float64) *PlatformBillingUpsert {
	u.Add(platformbilling.FieldProviderCostPerWhatsapp, v)
	return u
}

// SetMinMarkupPercentage sets the "min_markup_percentage" field.
func (u *PlatformBillingUpsert) SetMinMarkupPercentage(v float64) *PlatformBillingUpsert {
	u.Set(platformbilling.FieldMinMarkupPercentage, v)
	return u
}

// UpdateMinMarkupPercentage sets the "min_markup_percentage" field to the value that was provided on create.
func (u *PlatformBillingUpsert) UpdateMinMarkupPercentage() *PlatformBillingUpsert {
	u.SetExcluded(platformbilling.FieldMinMarkupPercentage)
	return u
}

// AddMinMarkupPercentage adds v to the "min_markup_percentage" field.
func (u *PlatformBillingUpsert) AddMinMarkupPercentage(v float64) *PlatformBillingUpsert {
	u.Add(platformbilling.FieldMinMarkupPercentage, v)
	return u
}

// SetMinTopupAmount sets the "min_topup_amount" field.
func (u *PlatformBillingUpsert) SetMinTopupAmount(v float64) *PlatformBillingUpsert {
	u.Set(platformbilling.FieldMinTopupAmount, v)
	return u
}

// UpdateMinTopupAmount sets the "min_topup_amount" field to the value that was provided on create.
func (u *PlatformBillingUpsert) UpdateMinTopupAmount() *PlatformBillingUpsert {
	u.SetExcluded(platformbilling.FieldMinTopupAmount)
	return u
}

// AddMinTopupAmount adds v to the "min_topup_amount" field.
func (u *PlatformBillingUpsert) AddMinTopupAmount(v float64) *PlatformBillingUpsert {
	u.Add(platformbilling.FieldMinTopupAmount, v)
	return u
}

// SetTreasuryGatewayID sets the "treasury_gateway_id" field.
func (u *PlatformBillingUpsert) SetTreasuryGatewayID(v uuid.UUID) *PlatformBillingUpsert {
	u.Set(platformbilling.FieldTreasuryGatewayID, v)
	return u
}

// UpdateTreasuryGatewayID sets the "treasury_gateway_id" field to the value that was provided on create.
func (u *PlatformBillingUpsert) UpdateTreasuryGatewayID() *PlatformBillingUpsert {
	u.SetExcluded(platformbilling.FieldTreasuryGatewayID)
	return u
}

// ClearTreasuryGatewayID clears the value of the "treasury_gateway_id" field.
func (u *PlatformBillingUpsert) ClearTreasuryGatewayID() *PlatformBillingUpsert {
	u.SetNull(platformbilling.FieldTreasuryGatewayID)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PlatformBillingUpsert) SetUpdatedAt(v time.Time) *PlatformBillingUpsert {
	u.Set(platformbilling.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PlatformBillingUpsert) UpdateUpdatedAt() *PlatformBillingUpsert {
	u.SetExcluded(platformbilling.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.PlatformBilling.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(platformbilling.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PlatformBillingUpsertOne) UpdateNewValues() *PlatformBillingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(platformbilling.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PlatformBilling.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PlatformBillingUpsertOne) Ignore() *PlatformBillingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PlatformBillingUpsertOne) DoNothing() *PlatformBillingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PlatformBillingCreate.OnConflict
// documentation for more info.
func (u *PlatformBillingUpsertOne) Update(set func(*PlatformBillingUpsert)) *PlatformBillingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PlatformBillingUpsert{UpdateSet: update})
	}))
	return u
}

// SetCostPerSms sets the "cost_per_sms" field.
func (u *PlatformBillingUpsertOne) SetCostPerSms(v float64) *PlatformBillingUpsertOne {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.SetCostPerSms(v)
	})
}

// AddCostPerSms adds v to the "cost_per_sms" field.
func (u *PlatformBillingUpsertOne) AddCostPerSms(v float64) *PlatformBillingUpsertOne {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.AddCostPerSms(v)
	})
}

// UpdateCostPerSms sets the "cost_per_sms" field to the value that was provided on create.
func (u *PlatformBillingUpsertOne) UpdateCostPerSms() *PlatformBillingUpsertOne {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.UpdateCostPerSms()
	})
}

// SetCostPerWhatsapp sets the "cost_per_whatsapp" field.
func (u *PlatformBillingUpsertOne) SetCostPerWhatsapp(v float64) *PlatformBillingUpsertOne {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.SetCostPerWhatsapp(v)
	})
}

// AddCostPerWhatsapp adds v to the "cost_per_whatsapp" field.
func (u *PlatformBillingUpsertOne) AddCostPerWhatsapp(v float64) *PlatformBillingUpsertOne {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.AddCostPerWhatsapp(v)
	})
}

// UpdateCostPerWhatsapp sets the "cost_per_whatsapp" field to the value that was provided on create.
func (u *PlatformBillingUpsertOne) UpdateCostPerWhatsapp() *PlatformBillingUpsertOne {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.UpdateCostPerWhatsapp()
	})
}

// SetProviderCostPerSms sets the "provider_cost_per_sms" field.
func (u *PlatformBillingUpsertOne) SetProviderCostPerSms(v float64) *PlatformBillingUpsertOne {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.SetProviderCostPerSms(v)
	})
}

// AddProviderCostPerSms adds v to the "provider_cost_per_sms" field.
func (u *PlatformBillingUpsertOne) AddProviderCostPerSms(v float64) *PlatformBillingUpsertOne {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.AddProviderCostPerSms(v)
	})
}

// UpdateProviderCostPerSms sets the "provider_cost_per_sms" field to the value that was provided on create.
func (u *PlatformBillingUpsertOne) UpdateProviderCostPerSms() *PlatformBillingUpsertOne {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.UpdateProviderCostPerSms()
	})
}

// SetProviderCostPerWhatsapp sets the "provider_cost_per_whatsapp" field.
func (u *PlatformBillingUpsertOne) SetProviderCostPerWhatsapp(v float64) *PlatformBillingUpsertOne {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.SetProviderCostPerWhatsapp(v)
	})
}

// AddProviderCostPerWhatsapp adds v to the "provider_cost_per_whatsapp" field.
func (u *PlatformBillingUpsertOne) AddProviderCostPerWhatsapp(v float64) *PlatformBillingUpsertOne {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.AddProviderCostPerWhatsapp(v)
	})
}

// UpdateProviderCostPerWhatsapp sets the "provider_cost_per_whatsapp" field to the value that was provided on create.
func (u *PlatformBillingUpsertOne) UpdateProviderCostPerWhatsapp() *PlatformBillingUpsertOne {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.UpdateProviderCostPerWhatsapp()
	})
}

// SetMinMarkupPercentage sets the "min_markup_percentage" field.
func (u *PlatformBillingUpsertOne) SetMinMarkupPercentage(v float64) *PlatformBillingUpsertOne {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.SetMinMarkupPercentage(v)
	})
}

// AddMinMarkupPercentage adds v to the "min_markup_percentage" field.
func (u *PlatformBillingUpsertOne) AddMinMarkupPercentage(v float64) *PlatformBillingUpsertOne {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.AddMinMarkupPercentage(v)
	})
}

// UpdateMinMarkupPercentage sets the "min_markup_percentage" field to the value that was provided on create.
func (u *PlatformBillingUpsertOne) UpdateMinMarkupPercentage() *PlatformBillingUpsertOne {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.UpdateMinMarkupPercentage()
	})
}

// SetMinTopupAmount sets the "min_topup_amount" field.
func (u *PlatformBillingUpsertOne) SetMinTopupAmount(v float64) *PlatformBillingUpsertOne {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.SetMinTopupAmount(v)
	})
}

// AddMinTopupAmount adds v to the "min_topup_amount" field.
func (u *PlatformBillingUpsertOne) AddMinTopupAmount(v float64) *PlatformBillingUpsertOne {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.AddMinTopupAmount(v)
	})
}

// UpdateMinTopupAmount sets the "min_topup_amount" field to the value that was provided on create.
func (u *PlatformBillingUpsertOne) UpdateMinTopupAmount() *PlatformBillingUpsertOne {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.UpdateMinTopupAmount()
	})
}

// SetTreasuryGatewayID sets the "treasury_gateway_id" field.
func (u *PlatformBillingUpsertOne) SetTreasuryGatewayID(v uuid.UUID) *PlatformBillingUpsertOne {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.SetTreasuryGatewayID(v)
	})
}

// UpdateTreasuryGatewayID sets the "treasury_gateway_id" field to the value that was provided on create.
func (u *PlatformBillingUpsertOne) UpdateTreasuryGatewayID() *PlatformBillingUpsertOne {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.UpdateTreasuryGatewayID()
	})
}

// ClearTreasuryGatewayID clears the value of the "treasury_gateway_id" field.
func (u *PlatformBillingUpsertOne) ClearTreasuryGatewayID() *PlatformBillingUpsertOne {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.ClearTreasuryGatewayID()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PlatformBillingUpsertOne) SetUpdatedAt(v time.Time) *PlatformBillingUpsertOne {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PlatformBillingUpsertOne) UpdateUpdatedAt() *PlatformBillingUpsertOne {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PlatformBillingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PlatformBillingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PlatformBillingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PlatformBillingUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: PlatformBillingUpsertOne.ID is not supported by MySQL driver. Use PlatformBillingUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PlatformBillingUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PlatformBillingCreateBulk is the builder for creating many PlatformBilling entities in bulk.
type PlatformBillingCreateBulk struct {
	config
	err      error
	builders []*PlatformBillingCreate
	conflict []sql.ConflictOption
}

// Save creates the PlatformBilling entities in the database.
func (_c *PlatformBillingCreateBulk) Save(ctx context.Context) ([]*PlatformBilling, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PlatformBilling, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PlatformBillingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PlatformBillingCreateBulk) SaveX(ctx context.Context) []*PlatformBilling {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlatformBillingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlatformBillingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PlatformBilling.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PlatformBillingUpsert) {
//			SetCostPerSms(v+v).
//		}).
//		Exec(ctx)
func (_c *PlatformBillingCreateBulk) OnConflict(opts ...sql.ConflictOption) *PlatformBillingUpsertBulk {
	_c.conflict = opts
	return &PlatformBillingUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PlatformBilling.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PlatformBillingCreateBulk) OnConflictColumns(columns ...string) *PlatformBillingUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PlatformBillingUpsertBulk{
		create: _c,
	}
}

// PlatformBillingUpsertBulk is the builder for "upsert"-ing
// a bulk of PlatformBilling nodes.
type PlatformBillingUpsertBulk struct {
	create *PlatformBillingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PlatformBilling.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(platformbilling.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PlatformBillingUpsertBulk) UpdateNewValues() *PlatformBillingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(platformbilling.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PlatformBilling.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PlatformBillingUpsertBulk) Ignore() *PlatformBillingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PlatformBillingUpsertBulk) DoNothing() *PlatformBillingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PlatformBillingCreateBulk.OnConflict
// documentation for more info.
func (u *PlatformBillingUpsertBulk) Update(set func(*PlatformBillingUpsert)) *PlatformBillingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PlatformBillingUpsert{UpdateSet: update})
	}))
	return u
}

// SetCostPerSms sets the "cost_per_sms" field.
func (u *PlatformBillingUpsertBulk) SetCostPerSms(v float64) *PlatformBillingUpsertBulk {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.SetCostPerSms(v)
	})
}

// AddCostPerSms adds v to the "cost_per_sms" field.
func (u *PlatformBillingUpsertBulk) AddCostPerSms(v float64) *PlatformBillingUpsertBulk {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.AddCostPerSms(v)
	})
}

// UpdateCostPerSms sets the "cost_per_sms" field to the value that was provided on create.
func (u *PlatformBillingUpsertBulk) UpdateCostPerSms() *PlatformBillingUpsertBulk {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.UpdateCostPerSms()
	})
}

// SetCostPerWhatsapp sets the "cost_per_whatsapp" field.
func (u *PlatformBillingUpsertBulk) SetCostPerWhatsapp(v float64) *PlatformBillingUpsertBulk {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.SetCostPerWhatsapp(v)
	})
}

// AddCostPerWhatsapp adds v to the "cost_per_whatsapp" field.
func (u *PlatformBillingUpsertBulk) AddCostPerWhatsapp(v float64) *PlatformBillingUpsertBulk {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.AddCostPerWhatsapp(v)
	})
}

// UpdateCostPerWhatsapp sets the "cost_per_whatsapp" field to the value that was provided on create.
func (u *PlatformBillingUpsertBulk) UpdateCostPerWhatsapp() *PlatformBillingUpsertBulk {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.UpdateCostPerWhatsapp()
	})
}

// SetProviderCostPerSms sets the "provider_cost_per_sms" field.
func (u *PlatformBillingUpsertBulk) SetProviderCostPerSms(v float64) *PlatformBillingUpsertBulk {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.SetProviderCostPerSms(v)
	})
}

// AddProviderCostPerSms adds v to the "provider_cost_per_sms" field.
func (u *PlatformBillingUpsertBulk) AddProviderCostPerSms(v float64) *PlatformBillingUpsertBulk {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.AddProviderCostPerSms(v)
	})
}

// UpdateProviderCostPerSms sets the "provider_cost_per_sms" field to the value that was provided on create.
func (u *PlatformBillingUpsertBulk) UpdateProviderCostPerSms() *PlatformBillingUpsertBulk {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.UpdateProviderCostPerSms()
	})
}

// SetProviderCostPerWhatsapp sets the "provider_cost_per_whatsapp" field.
func (u *PlatformBillingUpsertBulk) SetProviderCostPerWhatsapp(v float64) *PlatformBillingUpsertBulk {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.SetProviderCostPerWhatsapp(v)
	})
}

// AddProviderCostPerWhatsapp adds v to the "provider_cost_per_whatsapp" field.
func (u *PlatformBillingUpsertBulk) AddProviderCostPerWhatsapp(v float64) *PlatformBillingUpsertBulk {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.AddProviderCostPerWhatsapp(v)
	})
}

// UpdateProviderCostPerWhatsapp sets the "provider_cost_per_whatsapp" field to the value that was provided on create.
func (u *PlatformBillingUpsertBulk) UpdateProviderCostPerWhatsapp() *PlatformBillingUpsertBulk {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.UpdateProviderCostPerWhatsapp()
	})
}

// SetMinMarkupPercentage sets the "min_markup_percentage" field.
func (u *PlatformBillingUpsertBulk) SetMinMarkupPercentage(v float64) *PlatformBillingUpsertBulk {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.SetMinMarkupPercentage(v)
	})
}

// AddMinMarkupPercentage adds v to the "min_markup_percentage" field.
func (u *PlatformBillingUpsertBulk) AddMinMarkupPercentage(v float64) *PlatformBillingUpsertBulk {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.AddMinMarkupPercentage(v)
	})
}

// UpdateMinMarkupPercentage sets the "min_markup_percentage" field to the value that was provided on create.
func (u *PlatformBillingUpsertBulk) UpdateMinMarkupPercentage() *PlatformBillingUpsertBulk {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.UpdateMinMarkupPercentage()
	})
}

// SetMinTopupAmount sets the "min_topup_amount" field.
func (u *PlatformBillingUpsertBulk) SetMinTopupAmount(v float64) *PlatformBillingUpsertBulk {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.SetMinTopupAmount(v)
	})
}

// AddMinTopupAmount adds v to the "min_topup_amount" field.
func (u *PlatformBillingUpsertBulk) AddMinTopupAmount(v float64) *PlatformBillingUpsertBulk {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.AddMinTopupAmount(v)
	})
}

// UpdateMinTopupAmount sets the "min_topup_amount" field to the value that was provided on create.
func (u *PlatformBillingUpsertBulk) UpdateMinTopupAmount() *PlatformBillingUpsertBulk {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.UpdateMinTopupAmount()
	})
}

// SetTreasuryGatewayID sets the "treasury_gateway_id" field.
func (u *PlatformBillingUpsertBulk) SetTreasuryGatewayID(v uuid.UUID) *PlatformBillingUpsertBulk {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.SetTreasuryGatewayID(v)
	})
}

// UpdateTreasuryGatewayID sets the "treasury_gateway_id" field to the value that was provided on create.
func (u *PlatformBillingUpsertBulk) UpdateTreasuryGatewayID() *PlatformBillingUpsertBulk {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.UpdateTreasuryGatewayID()
	})
}

// ClearTreasuryGatewayID clears the value of the "treasury_gateway_id" field.
func (u *PlatformBillingUpsertBulk) ClearTreasuryGatewayID() *PlatformBillingUpsertBulk {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.ClearTreasuryGatewayID()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PlatformBillingUpsertBulk) SetUpdatedAt(v time.Time) *PlatformBillingUpsertBulk {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PlatformBillingUpsertBulk) UpdateUpdatedAt() *PlatformBillingUpsertBulk {
	return u.Update(func(s *PlatformBillingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PlatformBillingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PlatformBillingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PlatformBillingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PlatformBillingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
