// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/notifications-api/internal/ent/template"
	"github.com/google/uuid"
)

// TemplateCreate is the builder for creating a Template entity.
type TemplateCreate struct {
	config
	mutation *TemplateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *TemplateCreate) SetName(v string) *TemplateCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetChannel sets the "channel" field.
func (_c *TemplateCreate) SetChannel(v string) *TemplateCreate {
	_c.mutation.SetChannel(v)
	return _c
}

// SetCategory sets the "category" field.
func (_c *TemplateCreate) SetCategory(v string) *TemplateCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_c *TemplateCreate) SetNillableCategory(v *string) *TemplateCreate {
	if v != nil {
		_c.SetCategory(*v)
	}
	return _c
}

// SetTags sets the "tags" field.
func (_c *TemplateCreate) SetTags(v []string) *TemplateCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetFilePath sets the "file_path" field.
func (_c *TemplateCreate) SetFilePath(v string) *TemplateCreate {
	_c.mutation.SetFilePath(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *TemplateCreate) SetDescription(v string) *TemplateCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *TemplateCreate) SetNillableDescription(v *string) *TemplateCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetVariables sets the "variables" field.
func (_c *TemplateCreate) SetVariables(v []string) *TemplateCreate {
	_c.mutation.SetVariables(v)
	return _c
}

// SetMimeType sets the "mime_type" field.
func (_c *TemplateCreate) SetMimeType(v string) *TemplateCreate {
	_c.mutation.SetMimeType(v)
	return _c
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_c *TemplateCreate) SetNillableMimeType(v *string) *TemplateCreate {
	if v != nil {
		_c.SetMimeType(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *TemplateCreate) SetIsActive(v bool) *TemplateCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *TemplateCreate) SetNillableIsActive(v *bool) *TemplateCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TemplateCreate) SetCreatedAt(v time.Time) *TemplateCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TemplateCreate) SetNillableCreatedAt(v *time.Time) *TemplateCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TemplateCreate) SetUpdatedAt(v time.Time) *TemplateCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TemplateCreate) SetNillableUpdatedAt(v *time.Time) *TemplateCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TemplateCreate) SetID(v uuid.UUID) *TemplateCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *TemplateCreate) SetNillableID(v *uuid.UUID) *TemplateCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the TemplateMutation object of the builder.
func (_c *TemplateCreate) Mutation() *TemplateMutation {
	return _c.mutation
}

// Save creates the Template in the database.
func (_c *TemplateCreate) Save(ctx context.Context) (*Template, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TemplateCreate) SaveX(ctx context.Context) *Template {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TemplateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TemplateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TemplateCreate) defaults() {
	if _, ok := _c.mutation.Category(); !ok {
		v := template.DefaultCategory
		_c.mutation.SetCategory(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := template.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.MimeType(); !ok {
		v := template.DefaultMimeType
		_c.mutation.SetMimeType(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := template.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := template.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := template.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := template.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TemplateCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Template.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := template.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Template.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Channel(); !ok {
		return &ValidationError{Name: "channel", err: errors.New(`ent: missing required field "Template.channel"`)}
	}
	if v, ok := _c.mutation.Channel(); ok {
		if err := template.ChannelValidator(v); err != nil {
			return &ValidationError{Name: "channel", err: fmt.Errorf(`ent: validator failed for field "Template.channel": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "Template.category"`)}
	}
	if v, ok := _c.mutation.Category(); ok {
		if err := template.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Template.category": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FilePath(); !ok {
		return &ValidationError{Name: "file_path", err: errors.New(`ent: missing required field "Template.file_path"`)}
	}
	if v, ok := _c.mutation.FilePath(); ok {
		if err := template.FilePathValidator(v); err != nil {
			return &ValidationError{Name: "file_path", err: fmt.Errorf(`ent: validator failed for field "Template.file_path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MimeType(); !ok {
		return &ValidationError{Name: "mime_type", err: errors.New(`ent: missing required field "Template.mime_type"`)}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "Template.is_active"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Template.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Template.updated_at"`)}
	}
	return nil
}

func (_c *TemplateCreate) sqlSave(ctx context.Context) (*Template, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TemplateCreate) createSpec() (*Template, *sqlgraph.CreateSpec) {
	var (
		_node = &Template{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(template.Table, sqlgraph.NewFieldSpec(template.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(template.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Channel(); ok {
		_spec.SetField(template.FieldChannel, field.TypeString, value)
		_node.Channel = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(template.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(template.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	if value, ok := _c.mutation.FilePath(); ok {
		_spec.SetField(template.FieldFilePath, field.TypeString, value)
		_node.FilePath = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(template.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Variables(); ok {
		_spec.SetField(template.FieldVariables, field.TypeJSON, value)
		_node.Variables = value
	}
	if value, ok := _c.mutation.MimeType(); ok {
		_spec.SetField(template.FieldMimeType, field.TypeString, value)
		_node.MimeType = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(template.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(template.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(template.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Template.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TemplateUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *TemplateCreate) OnConflict(opts ...sql.ConflictOption) *TemplateUpsertOne {
	_c.conflict = opts
	return &TemplateUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Template.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TemplateCreate) OnConflictColumns(columns ...string) *TemplateUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TemplateUpsertOne{
		create: _c,
	}
}

type (
	// TemplateUpsertOne is the builder for "upsert"-ing
	//  one Template node.
	TemplateUpsertOne struct {
		create *TemplateCreate
	}

	// TemplateUpsert is the "OnConflict" setter.
	TemplateUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *TemplateUpsert) SetName(v string) *TemplateUpsert {
	u.Set(template.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TemplateUpsert) UpdateName() *TemplateUpsert {
	u.SetExcluded(template.FieldName)
	return u
}

// SetChannel sets the "channel" field.
func (u *TemplateUpsert) SetChannel(v string) *TemplateUpsert {
	u.Set(template.FieldChannel, v)
	return u
}

// UpdateChannel sets the "channel" field to the value that was provided on create.
func (u *TemplateUpsert) UpdateChannel() *TemplateUpsert {
	u.SetExcluded(template.FieldChannel)
	return u
}

// SetCategory sets the "category" field.
func (u *TemplateUpsert) SetCategory(v string) *TemplateUpsert {
	u.Set(template.FieldCategory, v)
	return u
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *TemplateUpsert) UpdateCategory() *TemplateUpsert {
	u.SetExcluded(template.FieldCategory)
	return u
}

// SetTags sets the "tags" field.
func (u *TemplateUpsert) SetTags(v []string) *TemplateUpsert {
	u.Set(template.FieldTags, v)
	return u
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *TemplateUpsert) UpdateTags() *TemplateUpsert {
	u.SetExcluded(template.FieldTags)
	return u
}

// ClearTags clears the value of the "tags" field.
func (u *TemplateUpsert) ClearTags() *TemplateUpsert {
	u.SetNull(template.FieldTags)
	return u
}

// SetFilePath sets the "file_path" field.
func (u *TemplateUpsert) SetFilePath(v string) *TemplateUpsert {
	u.Set(template.FieldFilePath, v)
	return u
}

// UpdateFilePath sets the "file_path" field to the value that was provided on create.
func (u *TemplateUpsert) UpdateFilePath() *TemplateUpsert {
	u.SetExcluded(template.FieldFilePath)
	return u
}

// SetDescription sets the "description" field.
func (u *TemplateUpsert) SetDescription(v string) *TemplateUpsert {
	u.Set(template.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *TemplateUpsert) UpdateDescription() *TemplateUpsert {
	u.SetExcluded(template.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *TemplateUpsert) ClearDescription() *TemplateUpsert {
	u.SetNull(template.FieldDescription)
	return u
}

// SetVariables sets the "variables" field.
func (u *TemplateUpsert) SetVariables(v []string) *TemplateUpsert {
	u.Set(template.FieldVariables, v)
	return u
}

// UpdateVariables sets the "variables" field to the value that was provided on create.
func (u *TemplateUpsert) UpdateVariables() *TemplateUpsert {
	u.SetExcluded(template.FieldVariables)
	return u
}

// ClearVariables clears the value of the "variables" field.
func (u *TemplateUpsert) ClearVariables() *TemplateUpsert {
	u.SetNull(template.FieldVariables)
	return u
}

// SetMimeType sets the "mime_type" field.
func (u *TemplateUpsert) SetMimeType(v string) *TemplateUpsert {
	u.Set(template.FieldMimeType, v)
	return u
}

// UpdateMimeType sets the "mime_type" field to the value that was provided on create.
func (u *TemplateUpsert) UpdateMimeType() *TemplateUpsert {
	u.SetExcluded(template.FieldMimeType)
	return u
}

// SetIsActive sets the "is_active" field.
func (u *TemplateUpsert) SetIsActive(v bool) *TemplateUpsert {
	u.Set(template.FieldIsActive, v)
	return u
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *TemplateUpsert) UpdateIsActive() *TemplateUpsert {
	u.SetExcluded(template.FieldIsActive)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TemplateUpsert) SetUpdatedAt(v time.Time) *TemplateUpsert {
	u.Set(template.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TemplateUpsert) UpdateUpdatedAt() *TemplateUpsert {
	u.SetExcluded(template.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Template.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(template.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TemplateUpsertOne) UpdateNewValues() *TemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(template.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(template.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Template.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TemplateUpsertOne) Ignore() *TemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TemplateUpsertOne) DoNothing() *TemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TemplateCreate.OnConflict
// documentation for more info.
func (u *TemplateUpsertOne) Update(set func(*TemplateUpsert)) *TemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TemplateUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *TemplateUpsertOne) SetName(v string) *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TemplateUpsertOne) UpdateName() *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateName()
	})
}

// SetChannel sets the "channel" field.
func (u *TemplateUpsertOne) SetChannel(v string) *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.SetChannel(v)
	})
}

// UpdateChannel sets the "channel" field to the value that was provided on create.
func (u *TemplateUpsertOne) UpdateChannel() *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateChannel()
	})
}

// SetCategory sets the "category" field.
func (u *TemplateUpsertOne) SetCategory(v string) *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *TemplateUpsertOne) UpdateCategory() *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateCategory()
	})
}

// SetTags sets the "tags" field.
func (u *TemplateUpsertOne) SetTags(v []string) *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.SetTags(v)
	})
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *TemplateUpsertOne) UpdateTags() *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateTags()
	})
}

// ClearTags clears the value of the "tags" field.
func (u *TemplateUpsertOne) ClearTags() *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.ClearTags()
	})
}

// SetFilePath sets the "file_path" field.
func (u *TemplateUpsertOne) SetFilePath(v string) *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.SetFilePath(v)
	})
}

// UpdateFilePath sets the "file_path" field to the value that was provided on create.
func (u *TemplateUpsertOne) UpdateFilePath() *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateFilePath()
	})
}

// SetDescription sets the "description" field.
func (u *TemplateUpsertOne) SetDescription(v string) *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *TemplateUpsertOne) UpdateDescription() *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *TemplateUpsertOne) ClearDescription() *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.ClearDescription()
	})
}

// SetVariables sets the "variables" field.
func (u *TemplateUpsertOne) SetVariables(v []string) *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.SetVariables(v)
	})
}

// UpdateVariables sets the "variables" field to the value that was provided on create.
func (u *TemplateUpsertOne) UpdateVariables() *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateVariables()
	})
}

// ClearVariables clears the value of the "variables" field.
func (u *TemplateUpsertOne) ClearVariables() *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.ClearVariables()
	})
}

// SetMimeType sets the "mime_type" field.
func (u *TemplateUpsertOne) SetMimeType(v string) *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.SetMimeType(v)
	})
}

// UpdateMimeType sets the "mime_type" field to the value that was provided on create.
func (u *TemplateUpsertOne) UpdateMimeType() *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateMimeType()
	})
}

// SetIsActive sets the "is_active" field.
func (u *TemplateUpsertOne) SetIsActive(v bool) *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *TemplateUpsertOne) UpdateIsActive() *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateIsActive()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TemplateUpsertOne) SetUpdatedAt(v time.Time) *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TemplateUpsertOne) UpdateUpdatedAt() *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *TemplateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TemplateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TemplateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TemplateUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: TemplateUpsertOne.ID is not supported by MySQL driver. Use TemplateUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TemplateUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TemplateCreateBulk is the builder for creating many Template entities in bulk.
type TemplateCreateBulk struct {
	config
	err      error
	builders []*TemplateCreate
	conflict []sql.ConflictOption
}

// Save creates the Template entities in the database.
func (_c *TemplateCreateBulk) Save(ctx context.Context) ([]*Template, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Template, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TemplateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TemplateCreateBulk) SaveX(ctx context.Context) []*Template {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TemplateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TemplateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Template.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TemplateUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *TemplateCreateBulk) OnConflict(opts ...sql.ConflictOption) *TemplateUpsertBulk {
	_c.conflict = opts
	return &TemplateUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Template.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TemplateCreateBulk) OnConflictColumns(columns ...string) *TemplateUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TemplateUpsertBulk{
		create: _c,
	}
}

// TemplateUpsertBulk is the builder for "upsert"-ing
// a bulk of Template nodes.
type TemplateUpsertBulk struct {
	create *TemplateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Template.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(template.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TemplateUpsertBulk) UpdateNewValues() *TemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(template.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(template.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Template.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TemplateUpsertBulk) Ignore() *TemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TemplateUpsertBulk) DoNothing() *TemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TemplateCreateBulk.OnConflict
// documentation for more info.
func (u *TemplateUpsertBulk) Update(set func(*TemplateUpsert)) *TemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TemplateUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *TemplateUpsertBulk) SetName(v string) *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TemplateUpsertBulk) UpdateName() *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateName()
	})
}

// SetChannel sets the "channel" field.
func (u *TemplateUpsertBulk) SetChannel(v string) *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.SetChannel(v)
	})
}

// UpdateChannel sets the "channel" field to the value that was provided on create.
func (u *TemplateUpsertBulk) UpdateChannel() *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateChannel()
	})
}

// SetCategory sets the "category" field.
func (u *TemplateUpsertBulk) SetCategory(v string) *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *TemplateUpsertBulk) UpdateCategory() *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateCategory()
	})
}

// SetTags sets the "tags" field.
func (u *TemplateUpsertBulk) SetTags(v []string) *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.SetTags(v)
	})
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *TemplateUpsertBulk) UpdateTags() *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateTags()
	})
}

// ClearTags clears the value of the "tags" field.
func (u *TemplateUpsertBulk) ClearTags() *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.ClearTags()
	})
}

// SetFilePath sets the "file_path" field.
func (u *TemplateUpsertBulk) SetFilePath(v string) *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.SetFilePath(v)
	})
}

// UpdateFilePath sets the "file_path" field to the value that was provided on create.
func (u *TemplateUpsertBulk) UpdateFilePath() *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateFilePath()
	})
}

// SetDescription sets the "description" field.
func (u *TemplateUpsertBulk) SetDescription(v string) *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *TemplateUpsertBulk) UpdateDescription() *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *TemplateUpsertBulk) ClearDescription() *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.ClearDescription()
	})
}

// SetVariables sets the "variables" field.
func (u *TemplateUpsertBulk) SetVariables(v []string) *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.SetVariables(v)
	})
}

// UpdateVariables sets the "variables" field to the value that was provided on create.
func (u *TemplateUpsertBulk) UpdateVariables() *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateVariables()
	})
}

// ClearVariables clears the value of the "variables" field.
func (u *TemplateUpsertBulk) ClearVariables() *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.ClearVariables()
	})
}

// SetMimeType sets the "mime_type" field.
func (u *TemplateUpsertBulk) SetMimeType(v string) *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.SetMimeType(v)
	})
}

// UpdateMimeType sets the "mime_type" field to the value that was provided on create.
func (u *TemplateUpsertBulk) UpdateMimeType() *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateMimeType()
	})
}

// SetIsActive sets the "is_active" field.
func (u *TemplateUpsertBulk) SetIsActive(v bool) *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *TemplateUpsertBulk) UpdateIsActive() *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateIsActive()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TemplateUpsertBulk) SetUpdatedAt(v time.Time) *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TemplateUpsertBulk) UpdateUpdatedAt() *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *TemplateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TemplateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TemplateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TemplateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
