// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/notifications-api/internal/ent/whatsappconversation"
	"github.com/bengobox/notifications-api/internal/ent/whatsappmessage"
	"github.com/google/uuid"
)

// WhatsAppConversationCreate is the builder for creating a WhatsAppConversation entity.
type WhatsAppConversationCreate struct {
	config
	mutation *WhatsAppConversationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (_c *WhatsAppConversationCreate) SetTenantID(v uuid.UUID) *WhatsAppConversationCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetPhoneNumberID sets the "phone_number_id" field.
func (_c *WhatsAppConversationCreate) SetPhoneNumberID(v string) *WhatsAppConversationCreate {
	_c.mutation.SetPhoneNumberID(v)
	return _c
}

// SetCustomerWaID sets the "customer_wa_id" field.
func (_c *WhatsAppConversationCreate) SetCustomerWaID(v string) *WhatsAppConversationCreate {
	_c.mutation.SetCustomerWaID(v)
	return _c
}

// SetCustomerName sets the "customer_name" field.
func (_c *WhatsAppConversationCreate) SetCustomerName(v string) *WhatsAppConversationCreate {
	_c.mutation.SetCustomerName(v)
	return _c
}

// SetNillableCustomerName sets the "customer_name" field if the given value is not nil.
func (_c *WhatsAppConversationCreate) SetNillableCustomerName(v *string) *WhatsAppConversationCreate {
	if v != nil {
		_c.SetCustomerName(*v)
	}
	return _c
}

// SetLastMessageAt sets the "last_message_at" field.
func (_c *WhatsAppConversationCreate) SetLastMessageAt(v time.Time) *WhatsAppConversationCreate {
	_c.mutation.SetLastMessageAt(v)
	return _c
}

// SetNillableLastMessageAt sets the "last_message_at" field if the given value is not nil.
func (_c *WhatsAppConversationCreate) SetNillableLastMessageAt(v *time.Time) *WhatsAppConversationCreate {
	if v != nil {
		_c.SetLastMessageAt(*v)
	}
	return _c
}

// SetLastMessagePreview sets the "last_message_preview" field.
func (_c *WhatsAppConversationCreate) SetLastMessagePreview(v string) *WhatsAppConversationCreate {
	_c.mutation.SetLastMessagePreview(v)
	return _c
}

// SetNillableLastMessagePreview sets the "last_message_preview" field if the given value is not nil.
func (_c *WhatsAppConversationCreate) SetNillableLastMessagePreview(v *string) *WhatsAppConversationCreate {
	if v != nil {
		_c.SetLastMessagePreview(*v)
	}
	return _c
}

// SetLastInboundAt sets the "last_inbound_at" field.
func (_c *WhatsAppConversationCreate) SetLastInboundAt(v time.Time) *WhatsAppConversationCreate {
	_c.mutation.SetLastInboundAt(v)
	return _c
}

// SetNillableLastInboundAt sets the "last_inbound_at" field if the given value is not nil.
func (_c *WhatsAppConversationCreate) SetNillableLastInboundAt(v *time.Time) *WhatsAppConversationCreate {
	if v != nil {
		_c.SetLastInboundAt(*v)
	}
	return _c
}

// SetUnreadCount sets the "unread_count" field.
func (_c *WhatsAppConversationCreate) SetUnreadCount(v int) *WhatsAppConversationCreate {
	_c.mutation.SetUnreadCount(v)
	return _c
}

// SetNillableUnreadCount sets the "unread_count" field if the given value is not nil.
func (_c *WhatsAppConversationCreate) SetNillableUnreadCount(v *int) *WhatsAppConversationCreate {
	if v != nil {
		_c.SetUnreadCount(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *WhatsAppConversationCreate) SetCreatedAt(v time.Time) *WhatsAppConversationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WhatsAppConversationCreate) SetNillableCreatedAt(v *time.Time) *WhatsAppConversationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *WhatsAppConversationCreate) SetUpdatedAt(v time.Time) *WhatsAppConversationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *WhatsAppConversationCreate) SetNillableUpdatedAt(v *time.Time) *WhatsAppConversationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *WhatsAppConversationCreate) SetID(v uuid.UUID) *WhatsAppConversationCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *WhatsAppConversationCreate) SetNillableID(v *uuid.UUID) *WhatsAppConversationCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddMessageIDs adds the "messages" edge to the WhatsAppMessage entity by IDs.
func (_c *WhatsAppConversationCreate) AddMessageIDs(ids ...uuid.UUID) *WhatsAppConversationCreate {
	_c.mutation.AddMessageIDs(ids...)
	return _c
}

// AddMessages adds the "messages" edges to the WhatsAppMessage entity.
func (_c *WhatsAppConversationCreate) AddMessages(v ...*WhatsAppMessage) *WhatsAppConversationCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMessageIDs(ids...)
}

// Mutation returns the WhatsAppConversationMutation object of the builder.
func (_c *WhatsAppConversationCreate) Mutation() *WhatsAppConversationMutation {
	return _c.mutation
}

// Save creates the WhatsAppConversation in the database.
func (_c *WhatsAppConversationCreate) Save(ctx context.Context) (*WhatsAppConversation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WhatsAppConversationCreate) SaveX(ctx context.Context) *WhatsAppConversation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WhatsAppConversationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WhatsAppConversationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WhatsAppConversationCreate) defaults() {
	if _, ok := _c.mutation.LastMessageAt(); !ok {
		v := whatsappconversation.DefaultLastMessageAt()
		_c.mutation.SetLastMessageAt(v)
	}
	if _, ok := _c.mutation.UnreadCount(); !ok {
		v := whatsappconversation.DefaultUnreadCount
		_c.mutation.SetUnreadCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := whatsappconversation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := whatsappconversation.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := whatsappconversation.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WhatsAppConversationCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "WhatsAppConversation.tenant_id"`)}
	}
	if _, ok := _c.mutation.PhoneNumberID(); !ok {
		return &ValidationError{Name: "phone_number_id", err: errors.New(`ent: missing required field "WhatsAppConversation.phone_number_id"`)}
	}
	if v, ok := _c.mutation.PhoneNumberID(); ok {
		if err := whatsappconversation.PhoneNumberIDValidator(v); err != nil {
			return &ValidationError{Name: "phone_number_id", err: fmt.Errorf(`ent: validator failed for field "WhatsAppConversation.phone_number_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CustomerWaID(); !ok {
		return &ValidationError{Name: "customer_wa_id", err: errors.New(`ent: missing required field "WhatsAppConversation.customer_wa_id"`)}
	}
	if v, ok := _c.mutation.CustomerWaID(); ok {
		if err := whatsappconversation.CustomerWaIDValidator(v); err != nil {
			return &ValidationError{Name: "customer_wa_id", err: fmt.Errorf(`ent: validator failed for field "WhatsAppConversation.customer_wa_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastMessageAt(); !ok {
		return &ValidationError{Name: "last_message_at", err: errors.New(`ent: missing required field "WhatsAppConversation.last_message_at"`)}
	}
	if _, ok := _c.mutation.UnreadCount(); !ok {
		return &ValidationError{Name: "unread_count", err: errors.New(`ent: missing required field "WhatsAppConversation.unread_count"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "WhatsAppConversation.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "WhatsAppConversation.updated_at"`)}
	}
	return nil
}

func (_c *WhatsAppConversationCreate) sqlSave(ctx context.Context) (*WhatsAppConversation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WhatsAppConversationCreate) createSpec() (*WhatsAppConversation, *sqlgraph.CreateSpec) {
	var (
		_node = &WhatsAppConversation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(whatsappconversation.Table, sqlgraph.NewFieldSpec(whatsappconversation.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(whatsappconversation.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.PhoneNumberID(); ok {
		_spec.SetField(whatsappconversation.FieldPhoneNumberID, field.TypeString, value)
		_node.PhoneNumberID = value
	}
	if value, ok := _c.mutation.CustomerWaID(); ok {
		_spec.SetField(whatsappconversation.FieldCustomerWaID, field.TypeString, value)
		_node.CustomerWaID = value
	}
	if value, ok := _c.mutation.CustomerName(); ok {
		_spec.SetField(whatsappconversation.FieldCustomerName, field.TypeString, value)
		_node.CustomerName = value
	}
	if value, ok := _c.mutation.LastMessageAt(); ok {
		_spec.SetField(whatsappconversation.FieldLastMessageAt, field.TypeTime, value)
		_node.LastMessageAt = value
	}
	if value, ok := _c.mutation.LastMessagePreview(); ok {
		_spec.SetField(whatsappconversation.FieldLastMessagePreview, field.TypeString, value)
		_node.LastMessagePreview = value
	}
	if value, ok := _c.mutation.LastInboundAt(); ok {
		_spec.SetField(whatsappconversation.FieldLastInboundAt, field.TypeTime, value)
		_node.LastInboundAt = &value
	}
	if value, ok := _c.mutation.UnreadCount(); ok {
		_spec.SetField(whatsappconversation.FieldUnreadCount, field.TypeInt, value)
		_node.UnreadCount = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(whatsappconversation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(whatsappconversation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   whatsappconversation.MessagesTable,
			Columns: []string{whatsappconversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(whatsappmessage.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WhatsAppConversation.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WhatsAppConversationUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *WhatsAppConversationCreate) OnConflict(opts ...sql.ConflictOption) *WhatsAppConversationUpsertOne {
	_c.conflict = opts
	return &WhatsAppConversationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WhatsAppConversation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WhatsAppConversationCreate) OnConflictColumns(columns ...string) *WhatsAppConversationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WhatsAppConversationUpsertOne{
		create: _c,
	}
}

type (
	// WhatsAppConversationUpsertOne is the builder for "upsert"-ing
	//  one WhatsAppConversation node.
	WhatsAppConversationUpsertOne struct {
		create *WhatsAppConversationCreate
	}

	// WhatsAppConversationUpsert is the "OnConflict" setter.
	WhatsAppConversationUpsert struct {
		*sql.UpdateSet
	}
)

// SetTenantID sets the "tenant_id" field.
func (u *WhatsAppConversationUpsert) SetTenantID(v uuid.UUID) *WhatsAppConversationUpsert {
	u.Set(whatsappconversation.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *WhatsAppConversationUpsert) UpdateTenantID() *WhatsAppConversationUpsert {
	u.SetExcluded(whatsappconversation.FieldTenantID)
	return u
}

// SetPhoneNumberID sets the "phone_number_id" field.
func (u *WhatsAppConversationUpsert) SetPhoneNumberID(v string) *WhatsAppConversationUpsert {
	u.Set(whatsappconversation.FieldPhoneNumberID, v)
	return u
}

// UpdatePhoneNumberID sets the "phone_number_id" field to the value that was provided on create.
func (u *WhatsAppConversationUpsert) UpdatePhoneNumberID() *WhatsAppConversationUpsert {
	u.SetExcluded(whatsappconversation.FieldPhoneNumberID)
	return u
}

// SetCustomerWaID sets the "customer_wa_id" field.
func (u *WhatsAppConversationUpsert) SetCustomerWaID(v string) *WhatsAppConversationUpsert {
	u.Set(whatsappconversation.FieldCustomerWaID, v)
	return u
}

// UpdateCustomerWaID sets the "customer_wa_id" field to the value that was provided on create.
func (u *WhatsAppConversationUpsert) UpdateCustomerWaID() *WhatsAppConversationUpsert {
	u.SetExcluded(whatsappconversation.FieldCustomerWaID)
	return u
}

// SetCustomerName sets the "customer_name" field.
func (u *WhatsAppConversationUpsert) SetCustomerName(v string) *WhatsAppConversationUpsert {
	u.Set(whatsappconversation.FieldCustomerName, v)
	return u
}

// UpdateCustomerName sets the "customer_name" field to the value that was provided on create.
func (u *WhatsAppConversationUpsert) UpdateCustomerName() *WhatsAppConversationUpsert {
	u.SetExcluded(whatsappconversation.FieldCustomerName)
	return u
}

// ClearCustomerName clears the value of the "customer_name" field.
func (u *WhatsAppConversationUpsert) ClearCustomerName() *WhatsAppConversationUpsert {
	u.SetNull(whatsappconversation.FieldCustomerName)
	return u
}

// SetLastMessageAt sets the "last_message_at" field.
func (u *WhatsAppConversationUpsert) SetLastMessageAt(v time.Time) *WhatsAppConversationUpsert {
	u.Set(whatsappconversation.FieldLastMessageAt, v)
	return u
}

// UpdateLastMessageAt sets the "last_message_at" field to the value that was provided on create.
func (u *WhatsAppConversationUpsert) UpdateLastMessageAt() *WhatsAppConversationUpsert {
	u.SetExcluded(whatsappconversation.FieldLastMessageAt)
	return u
}

// SetLastMessagePreview sets the "last_message_preview" field.
func (u *WhatsAppConversationUpsert) SetLastMessagePreview(v string) *WhatsAppConversationUpsert {
	u.Set(whatsappconversation.FieldLastMessagePreview, v)
	return u
}

// UpdateLastMessagePreview sets the "last_message_preview" field to the value that was provided on create.
func (u *WhatsAppConversationUpsert) UpdateLastMessagePreview() *WhatsAppConversationUpsert {
	u.SetExcluded(whatsappconversation.FieldLastMessagePreview)
	return u
}

// ClearLastMessagePreview clears the value of the "last_message_preview" field.
func (u *WhatsAppConversationUpsert) ClearLastMessagePreview() *WhatsAppConversationUpsert {
	u.SetNull(whatsappconversation.FieldLastMessagePreview)
	return u
}

// SetLastInboundAt sets the "last_inbound_at" field.
func (u *WhatsAppConversationUpsert) SetLastInboundAt(v time.Time) *WhatsAppConversationUpsert {
	u.Set(whatsappconversation.FieldLastInboundAt, v)
	return u
}

// UpdateLastInboundAt sets the "last_inbound_at" field to the value that was provided on create.
func (u *WhatsAppConversationUpsert) UpdateLastInboundAt() *WhatsAppConversationUpsert {
	u.SetExcluded(whatsappconversation.FieldLastInboundAt)
	return u
}

// ClearLastInboundAt clears the value of the "last_inbound_at" field.
func (u *WhatsAppConversationUpsert) ClearLastInboundAt() *WhatsAppConversationUpsert {
	u.SetNull(whatsappconversation.FieldLastInboundAt)
	return u
}

// SetUnreadCount sets the "unread_count" field.
func (u *WhatsAppConversationUpsert) SetUnreadCount(v int) *WhatsAppConversationUpsert {
	u.Set(whatsappconversation.FieldUnreadCount, v)
	return u
}

// UpdateUnreadCount sets the "unread_count" field to the value that was provided on create.
func (u *WhatsAppConversationUpsert) UpdateUnreadCount() *WhatsAppConversationUpsert {
	u.SetExcluded(whatsappconversation.FieldUnreadCount)
	return u
}

// AddUnreadCount adds v to the "unread_count" field.
func (u *WhatsAppConversationUpsert) AddUnreadCount(v int) *WhatsAppConversationUpsert {
	u.Add(whatsappconversation.FieldUnreadCount, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WhatsAppConversationUpsert) SetUpdatedAt(v time.Time) *WhatsAppConversationUpsert {
	u.Set(whatsappconversation.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WhatsAppConversationUpsert) UpdateUpdatedAt() *WhatsAppConversationUpsert {
	u.SetExcluded(whatsappconversation.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.WhatsAppConversation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(whatsappconversation.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *WhatsAppConversationUpsertOne) UpdateNewValues() *WhatsAppConversationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(whatsappconversation.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(whatsappconversation.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WhatsAppConversation.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *WhatsAppConversationUpsertOne) Ignore() *WhatsAppConversationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WhatsAppConversationUpsertOne) DoNothing() *WhatsAppConversationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WhatsAppConversationCreate.OnConflict
// documentation for more info.
func (u *WhatsAppConversationUpsertOne) Update(set func(*WhatsAppConversationUpsert)) *WhatsAppConversationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WhatsAppConversationUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *WhatsAppConversationUpsertOne) SetTenantID(v uuid.UUID) *WhatsAppConversationUpsertOne {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *WhatsAppConversationUpsertOne) UpdateTenantID() *WhatsAppConversationUpsertOne {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.UpdateTenantID()
	})
}

// SetPhoneNumberID sets the "phone_number_id" field.
func (u *WhatsAppConversationUpsertOne) SetPhoneNumberID(v string) *WhatsAppConversationUpsertOne {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.SetPhoneNumberID(v)
	})
}

// UpdatePhoneNumberID sets the "phone_number_id" field to the value that was provided on create.
func (u *WhatsAppConversationUpsertOne) UpdatePhoneNumberID() *WhatsAppConversationUpsertOne {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.UpdatePhoneNumberID()
	})
}

// SetCustomerWaID sets the "customer_wa_id" field.
func (u *WhatsAppConversationUpsertOne) SetCustomerWaID(v string) *WhatsAppConversationUpsertOne {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.SetCustomerWaID(v)
	})
}

// UpdateCustomerWaID sets the "customer_wa_id" field to the value that was provided on create.
func (u *WhatsAppConversationUpsertOne) UpdateCustomerWaID() *WhatsAppConversationUpsertOne {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.UpdateCustomerWaID()
	})
}

// SetCustomerName sets the "customer_name" field.
func (u *WhatsAppConversationUpsertOne) SetCustomerName(v string) *WhatsAppConversationUpsertOne {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.SetCustomerName(v)
	})
}

// UpdateCustomerName sets the "customer_name" field to the value that was provided on create.
func (u *WhatsAppConversationUpsertOne) UpdateCustomerName() *WhatsAppConversationUpsertOne {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.UpdateCustomerName()
	})
}

// ClearCustomerName clears the value of the "customer_name" field.
func (u *WhatsAppConversationUpsertOne) ClearCustomerName() *WhatsAppConversationUpsertOne {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.ClearCustomerName()
	})
}

// SetLastMessageAt sets the "last_message_at" field.
func (u *WhatsAppConversationUpsertOne) SetLastMessageAt(v time.Time) *WhatsAppConversationUpsertOne {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.SetLastMessageAt(v)
	})
}

// UpdateLastMessageAt sets the "last_message_at" field to the value that was provided on create.
func (u *WhatsAppConversationUpsertOne) UpdateLastMessageAt() *WhatsAppConversationUpsertOne {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.UpdateLastMessageAt()
	})
}

// SetLastMessagePreview sets the "last_message_preview" field.
func (u *WhatsAppConversationUpsertOne) SetLastMessagePreview(v string) *WhatsAppConversationUpsertOne {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.SetLastMessagePreview(v)
	})
}

// UpdateLastMessagePreview sets the "last_message_preview" field to the value that was provided on create.
func (u *WhatsAppConversationUpsertOne) UpdateLastMessagePreview() *WhatsAppConversationUpsertOne {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.UpdateLastMessagePreview()
	})
}

// ClearLastMessagePreview clears the value of the "last_message_preview" field.
func (u *WhatsAppConversationUpsertOne) ClearLastMessagePreview() *WhatsAppConversationUpsertOne {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.ClearLastMessagePreview()
	})
}

// SetLastInboundAt sets the "last_inbound_at" field.
func (u *WhatsAppConversationUpsertOne) SetLastInboundAt(v time.Time) *WhatsAppConversationUpsertOne {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.SetLastInboundAt(v)
	})
}

// UpdateLastInboundAt sets the "last_inbound_at" field to the value that was provided on create.
func (u *WhatsAppConversationUpsertOne) UpdateLastInboundAt() *WhatsAppConversationUpsertOne {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.UpdateLastInboundAt()
	})
}

// ClearLastInboundAt clears the value of the "last_inbound_at" field.
func (u *WhatsAppConversationUpsertOne) ClearLastInboundAt() *WhatsAppConversationUpsertOne {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.ClearLastInboundAt()
	})
}

// SetUnreadCount sets the "unread_count" field.
func (u *WhatsAppConversationUpsertOne) SetUnreadCount(v int) *WhatsAppConversationUpsertOne {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.SetUnreadCount(v)
	})
}

// AddUnreadCount adds v to the "unread_count" field.
func (u *WhatsAppConversationUpsertOne) AddUnreadCount(v int) *WhatsAppConversationUpsertOne {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.AddUnreadCount(v)
	})
}

// UpdateUnreadCount sets the "unread_count" field to the value that was provided on create.
func (u *WhatsAppConversationUpsertOne) UpdateUnreadCount() *WhatsAppConversationUpsertOne {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.UpdateUnreadCount()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WhatsAppConversationUpsertOne) SetUpdatedAt(v time.Time) *WhatsAppConversationUpsertOne {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WhatsAppConversationUpsertOne) UpdateUpdatedAt() *WhatsAppConversationUpsertOne {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *WhatsAppConversationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WhatsAppConversationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WhatsAppConversationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *WhatsAppConversationUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: WhatsAppConversationUpsertOne.ID is not supported by MySQL driver. Use WhatsAppConversationUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *WhatsAppConversationUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// WhatsAppConversationCreateBulk is the builder for creating many WhatsAppConversation entities in bulk.
type WhatsAppConversationCreateBulk struct {
	config
	err      error
	builders []*WhatsAppConversationCreate
	conflict []sql.ConflictOption
}

// Save creates the WhatsAppConversation entities in the database.
func (_c *WhatsAppConversationCreateBulk) Save(ctx context.Context) ([]*WhatsAppConversation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WhatsAppConversation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WhatsAppConversationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WhatsAppConversationCreateBulk) SaveX(ctx context.Context) []*WhatsAppConversation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WhatsAppConversationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WhatsAppConversationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WhatsAppConversation.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WhatsAppConversationUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *WhatsAppConversationCreateBulk) OnConflict(opts ...sql.ConflictOption) *WhatsAppConversationUpsertBulk {
	_c.conflict = opts
	return &WhatsAppConversationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WhatsAppConversation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WhatsAppConversationCreateBulk) OnConflictColumns(columns ...string) *WhatsAppConversationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WhatsAppConversationUpsertBulk{
		create: _c,
	}
}

// WhatsAppConversationUpsertBulk is the builder for "upsert"-ing
// a bulk of WhatsAppConversation nodes.
type WhatsAppConversationUpsertBulk struct {
	create *WhatsAppConversationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.WhatsAppConversation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(whatsappconversation.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *WhatsAppConversationUpsertBulk) UpdateNewValues() *WhatsAppConversationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(whatsappconversation.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(whatsappconversation.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WhatsAppConversation.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *WhatsAppConversationUpsertBulk) Ignore() *WhatsAppConversationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WhatsAppConversationUpsertBulk) DoNothing() *WhatsAppConversationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WhatsAppConversationCreateBulk.OnConflict
// documentation for more info.
func (u *WhatsAppConversationUpsertBulk) Update(set func(*WhatsAppConversationUpsert)) *WhatsAppConversationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WhatsAppConversationUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *WhatsAppConversationUpsertBulk) SetTenantID(v uuid.UUID) *WhatsAppConversationUpsertBulk {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *WhatsAppConversationUpsertBulk) UpdateTenantID() *WhatsAppConversationUpsertBulk {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.UpdateTenantID()
	})
}

// SetPhoneNumberID sets the "phone_number_id" field.
func (u *WhatsAppConversationUpsertBulk) SetPhoneNumberID(v string) *WhatsAppConversationUpsertBulk {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.SetPhoneNumberID(v)
	})
}

// UpdatePhoneNumberID sets the "phone_number_id" field to the value that was provided on create.
func (u *WhatsAppConversationUpsertBulk) UpdatePhoneNumberID() *WhatsAppConversationUpsertBulk {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.UpdatePhoneNumberID()
	})
}

// SetCustomerWaID sets the "customer_wa_id" field.
func (u *WhatsAppConversationUpsertBulk) SetCustomerWaID(v string) *WhatsAppConversationUpsertBulk {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.SetCustomerWaID(v)
	})
}

// UpdateCustomerWaID sets the "customer_wa_id" field to the value that was provided on create.
func (u *WhatsAppConversationUpsertBulk) UpdateCustomerWaID() *WhatsAppConversationUpsertBulk {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.UpdateCustomerWaID()
	})
}

// SetCustomerName sets the "customer_name" field.
func (u *WhatsAppConversationUpsertBulk) SetCustomerName(v string) *WhatsAppConversationUpsertBulk {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.SetCustomerName(v)
	})
}

// UpdateCustomerName sets the "customer_name" field to the value that was provided on create.
func (u *WhatsAppConversationUpsertBulk) UpdateCustomerName() *WhatsAppConversationUpsertBulk {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.UpdateCustomerName()
	})
}

// ClearCustomerName clears the value of the "customer_name" field.
func (u *WhatsAppConversationUpsertBulk) ClearCustomerName() *WhatsAppConversationUpsertBulk {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.ClearCustomerName()
	})
}

// SetLastMessageAt sets the "last_message_at" field.
func (u *WhatsAppConversationUpsertBulk) SetLastMessageAt(v time.Time) *WhatsAppConversationUpsertBulk {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.SetLastMessageAt(v)
	})
}

// UpdateLastMessageAt sets the "last_message_at" field to the value that was provided on create.
func (u *WhatsAppConversationUpsertBulk) UpdateLastMessageAt() *WhatsAppConversationUpsertBulk {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.UpdateLastMessageAt()
	})
}

// SetLastMessagePreview sets the "last_message_preview" field.
func (u *WhatsAppConversationUpsertBulk) SetLastMessagePreview(v string) *WhatsAppConversationUpsertBulk {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.SetLastMessagePreview(v)
	})
}

// UpdateLastMessagePreview sets the "last_message_preview" field to the value that was provided on create.
func (u *WhatsAppConversationUpsertBulk) UpdateLastMessagePreview() *WhatsAppConversationUpsertBulk {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.UpdateLastMessagePreview()
	})
}

// ClearLastMessagePreview clears the value of the "last_message_preview" field.
func (u *WhatsAppConversationUpsertBulk) ClearLastMessagePreview() *WhatsAppConversationUpsertBulk {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.ClearLastMessagePreview()
	})
}

// SetLastInboundAt sets the "last_inbound_at" field.
func (u *WhatsAppConversationUpsertBulk) SetLastInboundAt(v time.Time) *WhatsAppConversationUpsertBulk {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.SetLastInboundAt(v)
	})
}

// UpdateLastInboundAt sets the "last_inbound_at" field to the value that was provided on create.
func (u *WhatsAppConversationUpsertBulk) UpdateLastInboundAt() *WhatsAppConversationUpsertBulk {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.UpdateLastInboundAt()
	})
}

// ClearLastInboundAt clears the value of the "last_inbound_at" field.
func (u *WhatsAppConversationUpsertBulk) ClearLastInboundAt() *WhatsAppConversationUpsertBulk {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.ClearLastInboundAt()
	})
}

// SetUnreadCount sets the "unread_count" field.
func (u *WhatsAppConversationUpsertBulk) SetUnreadCount(v int) *WhatsAppConversationUpsertBulk {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.SetUnreadCount(v)
	})
}

// AddUnreadCount adds v to the "unread_count" field.
func (u *WhatsAppConversationUpsertBulk) AddUnreadCount(v int) *WhatsAppConversationUpsertBulk {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.AddUnreadCount(v)
	})
}

// UpdateUnreadCount sets the "unread_count" field to the value that was provided on create.
func (u *WhatsAppConversationUpsertBulk) UpdateUnreadCount() *WhatsAppConversationUpsertBulk {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.UpdateUnreadCount()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WhatsAppConversationUpsertBulk) SetUpdatedAt(v time.Time) *WhatsAppConversationUpsertBulk {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WhatsAppConversationUpsertBulk) UpdateUpdatedAt() *WhatsAppConversationUpsertBulk {
	return u.Update(func(s *WhatsAppConversationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *WhatsAppConversationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the WhatsAppConversationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WhatsAppConversationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WhatsAppConversationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
