// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/notifications-api/internal/ent/whatsappconversation"
	"github.com/bengobox/notifications-api/internal/ent/whatsappmessage"
	"github.com/google/uuid"
)

// WhatsAppMessageCreate is the builder for creating a WhatsAppMessage entity.
type WhatsAppMessageCreate struct {
	config
	mutation *WhatsAppMessageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetConversationID sets the "conversation_id" field.
func (_c *WhatsAppMessageCreate) SetConversationID(v uuid.UUID) *WhatsAppMessageCreate {
	_c.mutation.SetConversationID(v)
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *WhatsAppMessageCreate) SetTenantID(v uuid.UUID) *WhatsAppMessageCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetDirection sets the "direction" field.
func (_c *WhatsAppMessageCreate) SetDirection(v whatsappmessage.Direction) *WhatsAppMessageCreate {
	_c.mutation.SetDirection(v)
	return _c
}

// SetMessageType sets the "message_type" field.
func (_c *WhatsAppMessageCreate) SetMessageType(v string) *WhatsAppMessageCreate {
	_c.mutation.SetMessageType(v)
	return _c
}

// SetNillableMessageType sets the "message_type" field if the given value is not nil.
func (_c *WhatsAppMessageCreate) SetNillableMessageType(v *string) *WhatsAppMessageCreate {
	if v != nil {
		_c.SetMessageType(*v)
	}
	return _c
}

// SetBody sets the "body" field.
func (_c *WhatsAppMessageCreate) SetBody(v string) *WhatsAppMessageCreate {
	_c.mutation.SetBody(v)
	return _c
}

// SetWaMessageID sets the "wa_message_id" field.
func (_c *WhatsAppMessageCreate) SetWaMessageID(v string) *WhatsAppMessageCreate {
	_c.mutation.SetWaMessageID(v)
	return _c
}

// SetNillableWaMessageID sets the "wa_message_id" field if the given value is not nil.
func (_c *WhatsAppMessageCreate) SetNillableWaMessageID(v *string) *WhatsAppMessageCreate {
	if v != nil {
		_c.SetWaMessageID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *WhatsAppMessageCreate) SetStatus(v string) *WhatsAppMessageCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *WhatsAppMessageCreate) SetNillableStatus(v *string) *WhatsAppMessageCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSentByUserID sets the "sent_by_user_id" field.
func (_c *WhatsAppMessageCreate) SetSentByUserID(v uuid.UUID) *WhatsAppMessageCreate {
	_c.mutation.SetSentByUserID(v)
	return _c
}

// SetNillableSentByUserID sets the "sent_by_user_id" field if the given value is not nil.
func (_c *WhatsAppMessageCreate) SetNillableSentByUserID(v *uuid.UUID) *WhatsAppMessageCreate {
	if v != nil {
		_c.SetSentByUserID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *WhatsAppMessageCreate) SetCreatedAt(v time.Time) *WhatsAppMessageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WhatsAppMessageCreate) SetNillableCreatedAt(v *time.Time) *WhatsAppMessageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *WhatsAppMessageCreate) SetID(v uuid.UUID) *WhatsAppMessageCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *WhatsAppMessageCreate) SetNillableID(v *uuid.UUID) *WhatsAppMessageCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetConversation sets the "conversation" edge to the WhatsAppConversation entity.
func (_c *WhatsAppMessageCreate) SetConversation(v *WhatsAppConversation) *WhatsAppMessageCreate {
	return _c.SetConversationID(v.ID)
}

// Mutation returns the WhatsAppMessageMutation object of the builder.
func (_c *WhatsAppMessageCreate) Mutation() *WhatsAppMessageMutation {
	return _c.mutation
}

// Save creates the WhatsAppMessage in the database.
func (_c *WhatsAppMessageCreate) Save(ctx context.Context) (*WhatsAppMessage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WhatsAppMessageCreate) SaveX(ctx context.Context) *WhatsAppMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WhatsAppMessageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WhatsAppMessageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WhatsAppMessageCreate) defaults() {
	if _, ok := _c.mutation.MessageType(); !ok {
		v := whatsappmessage.DefaultMessageType
		_c.mutation.SetMessageType(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := whatsappmessage.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := whatsappmessage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := whatsappmessage.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WhatsAppMessageCreate) check() error {
	if _, ok := _c.mutation.ConversationID(); !ok {
		return &ValidationError{Name: "conversation_id", err: errors.New(`ent: missing required field "WhatsAppMessage.conversation_id"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "WhatsAppMessage.tenant_id"`)}
	}
	if _, ok := _c.mutation.Direction(); !ok {
		return &ValidationError{Name: "direction", err: errors.New(`ent: missing required field "WhatsAppMessage.direction"`)}
	}
	if v, ok := _c.mutation.Direction(); ok {
		if err := whatsappmessage.DirectionValidator(v); err != nil {
			return &ValidationError{Name: "direction", err: fmt.Errorf(`ent: validator failed for field "WhatsAppMessage.direction": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MessageType(); !ok {
		return &ValidationError{Name: "message_type", err: errors.New(`ent: missing required field "WhatsAppMessage.message_type"`)}
	}
	if _, ok := _c.mutation.Body(); !ok {
		return &ValidationError{Name: "body", err: errors.New(`ent: missing required field "WhatsAppMessage.body"`)}
	}
	if v, ok := _c.mutation.Body(); ok {
		if err := whatsappmessage.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "WhatsAppMessage.body": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "WhatsAppMessage.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "WhatsAppMessage.created_at"`)}
	}
	if len(_c.mutation.ConversationIDs()) == 0 {
		return &ValidationError{Name: "conversation", err: errors.New(`ent: missing required edge "WhatsAppMessage.conversation"`)}
	}
	return nil
}

func (_c *WhatsAppMessageCreate) sqlSave(ctx context.Context) (*WhatsAppMessage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WhatsAppMessageCreate) createSpec() (*WhatsAppMessage, *sqlgraph.CreateSpec) {
	var (
		_node = &WhatsAppMessage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(whatsappmessage.Table, sqlgraph.NewFieldSpec(whatsappmessage.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(whatsappmessage.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.Direction(); ok {
		_spec.SetField(whatsappmessage.FieldDirection, field.TypeEnum, value)
		_node.Direction = value
	}
	if value, ok := _c.mutation.MessageType(); ok {
		_spec.SetField(whatsappmessage.FieldMessageType, field.TypeString, value)
		_node.MessageType = value
	}
	if value, ok := _c.mutation.Body(); ok {
		_spec.SetField(whatsappmessage.FieldBody, field.TypeString, value)
		_node.Body = value
	}
	if value, ok := _c.mutation.WaMessageID(); ok {
		_spec.SetField(whatsappmessage.FieldWaMessageID, field.TypeString, value)
		_node.WaMessageID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(whatsappmessage.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.SentByUserID(); ok {
		_spec.SetField(whatsappmessage.FieldSentByUserID, field.TypeUUID, value)
		_node.SentByUserID = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(whatsappmessage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ConversationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   whatsappmessage.ConversationTable,
			Columns: []string{whatsappmessage.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(whatsappconversation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ConversationID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WhatsAppMessage.Create().
//		SetConversationID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WhatsAppMessageUpsert) {
//			SetConversationID(v+v).
//		}).
//		Exec(ctx)
func (_c *WhatsAppMessageCreate) OnConflict(opts ...sql.ConflictOption) *WhatsAppMessageUpsertOne {
	_c.conflict = opts
	return &WhatsAppMessageUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WhatsAppMessage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WhatsAppMessageCreate) OnConflictColumns(columns ...string) *WhatsAppMessageUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WhatsAppMessageUpsertOne{
		create: _c,
	}
}

type (
	// WhatsAppMessageUpsertOne is the builder for "upsert"-ing
	//  one WhatsAppMessage node.
	WhatsAppMessageUpsertOne struct {
		create *WhatsAppMessageCreate
	}

	// WhatsAppMessageUpsert is the "OnConflict" setter.
	WhatsAppMessageUpsert struct {
		*sql.UpdateSet
	}
)

// SetConversationID sets the "conversation_id" field.
func (u *WhatsAppMessageUpsert) SetConversationID(v uuid.UUID) *WhatsAppMessageUpsert {
	u.Set(whatsappmessage.FieldConversationID, v)
	return u
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *WhatsAppMessageUpsert) UpdateConversationID() *WhatsAppMessageUpsert {
	u.SetExcluded(whatsappmessage.FieldConversationID)
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *WhatsAppMessageUpsert) SetTenantID(v uuid.UUID) *WhatsAppMessageUpsert {
	u.Set(whatsappmessage.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *WhatsAppMessageUpsert) UpdateTenantID() *WhatsAppMessageUpsert {
	u.SetExcluded(whatsappmessage.FieldTenantID)
	return u
}

// SetDirection sets the "direction" field.
func (u *WhatsAppMessageUpsert) SetDirection(v whatsappmessage.Direction) *WhatsAppMessageUpsert {
	u.Set(whatsappmessage.FieldDirection, v)
	return u
}

// UpdateDirection sets the "direction" field to the value that was provided on create.
func (u *WhatsAppMessageUpsert) UpdateDirection() *WhatsAppMessageUpsert {
	u.SetExcluded(whatsappmessage.FieldDirection)
	return u
}

// SetMessageType sets the "message_type" field.
func (u *WhatsAppMessageUpsert) SetMessageType(v string) *WhatsAppMessageUpsert {
	u.Set(whatsappmessage.FieldMessageType, v)
	return u
}

// UpdateMessageType sets the "message_type" field to the value that was provided on create.
func (u *WhatsAppMessageUpsert) UpdateMessageType() *WhatsAppMessageUpsert {
	u.SetExcluded(whatsappmessage.FieldMessageType)
	return u
}

// SetBody sets the "body" field.
func (u *WhatsAppMessageUpsert) SetBody(v string) *WhatsAppMessageUpsert {
	u.Set(whatsappmessage.FieldBody, v)
	return u
}

// UpdateBody sets the "body" field to the value that was provided on create.
func (u *WhatsAppMessageUpsert) UpdateBody() *WhatsAppMessageUpsert {
	u.SetExcluded(whatsappmessage.FieldBody)
	return u
}

// SetWaMessageID sets the "wa_message_id" field.
func (u *WhatsAppMessageUpsert) SetWaMessageID(v string) *WhatsAppMessageUpsert {
	u.Set(whatsappmessage.FieldWaMessageID, v)
	return u
}

// UpdateWaMessageID sets the "wa_message_id" field to the value that was provided on create.
func (u *WhatsAppMessageUpsert) UpdateWaMessageID() *WhatsAppMessageUpsert {
	u.SetExcluded(whatsappmessage.FieldWaMessageID)
	return u
}

// ClearWaMessageID clears the value of the "wa_message_id" field.
func (u *WhatsAppMessageUpsert) ClearWaMessageID() *WhatsAppMessageUpsert {
	u.SetNull(whatsappmessage.FieldWaMessageID)
	return u
}

// SetStatus sets the "status" field.
func (u *WhatsAppMessageUpsert) SetStatus(v string) *WhatsAppMessageUpsert {
	u.Set(whatsappmessage.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *WhatsAppMessageUpsert) UpdateStatus() *WhatsAppMessageUpsert {
	u.SetExcluded(whatsappmessage.FieldStatus)
	return u
}

// SetSentByUserID sets the "sent_by_user_id" field.
func (u *WhatsAppMessageUpsert) SetSentByUserID(v uuid.UUID) *WhatsAppMessageUpsert {
	u.Set(whatsappmessage.FieldSentByUserID, v)
	return u
}

// UpdateSentByUserID sets the "sent_by_user_id" field to the value that was provided on create.
func (u *WhatsAppMessageUpsert) UpdateSentByUserID() *WhatsAppMessageUpsert {
	u.SetExcluded(whatsappmessage.FieldSentByUserID)
	return u
}

// ClearSentByUserID clears the value of the "sent_by_user_id" field.
func (u *WhatsAppMessageUpsert) ClearSentByUserID() *WhatsAppMessageUpsert {
	u.SetNull(whatsappmessage.FieldSentByUserID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.WhatsAppMessage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(whatsappmessage.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *WhatsAppMessageUpsertOne) UpdateNewValues() *WhatsAppMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(whatsappmessage.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(whatsappmessage.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WhatsAppMessage.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *WhatsAppMessageUpsertOne) Ignore() *WhatsAppMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WhatsAppMessageUpsertOne) DoNothing() *WhatsAppMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WhatsAppMessageCreate.OnConflict
// documentation for more info.
func (u *WhatsAppMessageUpsertOne) Update(set func(*WhatsAppMessageUpsert)) *WhatsAppMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WhatsAppMessageUpsert{UpdateSet: update})
	}))
	return u
}

// SetConversationID sets the "conversation_id" field.
func (u *WhatsAppMessageUpsertOne) SetConversationID(v uuid.UUID) *WhatsAppMessageUpsertOne {
	return u.Update(func(s *WhatsAppMessageUpsert) {
		s.SetConversationID(v)
	})
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *WhatsAppMessageUpsertOne) UpdateConversationID() *WhatsAppMessageUpsertOne {
	return u.Update(func(s *WhatsAppMessageUpsert) {
		s.UpdateConversationID()
	})
}

// SetTenantID sets the "tenant_id" field.
func (u *WhatsAppMessageUpsertOne) SetTenantID(v uuid.UUID) *WhatsAppMessageUpsertOne {
	return u.Update(func(s *WhatsAppMessageUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *WhatsAppMessageUpsertOne) UpdateTenantID() *WhatsAppMessageUpsertOne {
	return u.Update(func(s *WhatsAppMessageUpsert) {
		s.UpdateTenantID()
	})
}

// SetDirection sets the "direction" field.
func (u *WhatsAppMessageUpsertOne) SetDirection(v whatsappmessage.Direction) *WhatsAppMessageUpsertOne {
	return u.Update(func(s *WhatsAppMessageUpsert) {
		s.SetDirection(v)
	})
}

// UpdateDirection sets the "direction" field to the value that was provided on create.
func (u *WhatsAppMessageUpsertOne) UpdateDirection() *WhatsAppMessageUpsertOne {
	return u.Update(func(s *WhatsAppMessageUpsert) {
		s.UpdateDirection()
	})
}

// SetMessageType sets the "message_type" field.
func (u *WhatsAppMessageUpsertOne) SetMessageType(v string) *WhatsAppMessageUpsertOne {
	return u.Update(func(s *WhatsAppMessageUpsert) {
		s.SetMessageType(v)
	})
}

// UpdateMessageType sets the "message_type" field to the value that was provided on create.
func (u *WhatsAppMessageUpsertOne) UpdateMessageType() *WhatsAppMessageUpsertOne {
	return u.Update(func(s *WhatsAppMessageUpsert) {
		s.UpdateMessageType()
	})
}

// SetBody sets the "body" field.
func (u *WhatsAppMessageUpsertOne) SetBody(v string) *WhatsAppMessageUpsertOne {
	return u.Update(func(s *WhatsAppMessageUpsert) {
		s.SetBody(v)
	})
}

// UpdateBody sets the "body" field to the value that was provided on create.
func (u *WhatsAppMessageUpsertOne) UpdateBody() *WhatsAppMessageUpsertOne {
	return u.Update(func(s *WhatsAppMessageUpsert) {
		s.UpdateBody()
	})
}

// SetWaMessageID sets the "wa_message_id" field.
func (u *WhatsAppMessageUpsertOne) SetWaMessageID(v string) *WhatsAppMessageUpsertOne {
	return u.Update(func(s *WhatsAppMessageUpsert) {
		s.SetWaMessageID(v)
	})
}

// UpdateWaMessageID sets the "wa_message_id" field to the value that was provided on create.
func (u *WhatsAppMessageUpsertOne) UpdateWaMessageID() *WhatsAppMessageUpsertOne {
	return u.Update(func(s *WhatsAppMessageUpsert) {
		s.UpdateWaMessageID()
	})
}

// ClearWaMessageID clears the value of the "wa_message_id" field.
func (u *WhatsAppMessageUpsertOne) ClearWaMessageID() *WhatsAppMessageUpsertOne {
	return u.Update(func(s *WhatsAppMessageUpsert) {
		s.ClearWaMessageID()
	})
}

// SetStatus sets the "status" field.
func (u *WhatsAppMessageUpsertOne) SetStatus(v string) *WhatsAppMessageUpsertOne {
	return u.Update(func(s *WhatsAppMessageUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *WhatsAppMessageUpsertOne) UpdateStatus() *WhatsAppMessageUpsertOne {
	return u.Update(func(s *WhatsAppMessageUpsert) {
		s.UpdateStatus()
	})
}

// SetSentByUserID sets the "sent_by_user_id" field.
func (u *WhatsAppMessageUpsertOne) SetSentByUserID(v uuid.UUID) *WhatsAppMessageUpsertOne {
	return u.Update(func(s *WhatsAppMessageUpsert) {
		s.SetSentByUserID(v)
	})
}

// UpdateSentByUserID sets the "sent_by_user_id" field to the value that was provided on create.
func (u *WhatsAppMessageUpsertOne) UpdateSentByUserID() *WhatsAppMessageUpsertOne {
	return u.Update(func(s *WhatsAppMessageUpsert) {
		s.UpdateSentByUserID()
	})
}

// ClearSentByUserID clears the value of the "sent_by_user_id" field.
func (u *WhatsAppMessageUpsertOne) ClearSentByUserID() *WhatsAppMessageUpsertOne {
	return u.Update(func(s *WhatsAppMessageUpsert) {
		s.ClearSentByUserID()
	})
}

// Exec executes the query.
func (u *WhatsAppMessageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WhatsAppMessageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WhatsAppMessageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *WhatsAppMessageUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: WhatsAppMessageUpsertOne.ID is not supported by MySQL driver. Use WhatsAppMessageUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *WhatsAppMessageUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// WhatsAppMessageCreateBulk is the builder for creating many WhatsAppMessage entities in bulk.
type WhatsAppMessageCreateBulk struct {
	config
	err      error
	builders []*WhatsAppMessageCreate
	conflict []sql.ConflictOption
}

// Save creates the WhatsAppMessage entities in the database.
func (_c *WhatsAppMessageCreateBulk) Save(ctx context.Context) ([]*WhatsAppMessage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WhatsAppMessage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WhatsAppMessageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WhatsAppMessageCreateBulk) SaveX(ctx context.Context) []*WhatsAppMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WhatsAppMessageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WhatsAppMessageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WhatsAppMessage.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WhatsAppMessageUpsert) {
//			SetConversationID(v+v).
//		}).
//		Exec(ctx)
func (_c *WhatsAppMessageCreateBulk) OnConflict(opts ...sql.ConflictOption) *WhatsAppMessageUpsertBulk {
	_c.conflict = opts
	return &WhatsAppMessageUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WhatsAppMessage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WhatsAppMessageCreateBulk) OnConflictColumns(columns ...string) *WhatsAppMessageUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WhatsAppMessageUpsertBulk{
		create: _c,
	}
}

// WhatsAppMessageUpsertBulk is the builder for "upsert"-ing
// a bulk of WhatsAppMessage nodes.
type WhatsAppMessageUpsertBulk struct {
	create *WhatsAppMessageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.WhatsAppMessage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(whatsappmessage.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *WhatsAppMessageUpsertBulk) UpdateNewValues() *WhatsAppMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(whatsappmessage.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(whatsappmessage.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WhatsAppMessage.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *WhatsAppMessageUpsertBulk) Ignore() *WhatsAppMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WhatsAppMessageUpsertBulk) DoNothing() *WhatsAppMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WhatsAppMessageCreateBulk.OnConflict
// documentation for more info.
func (u *WhatsAppMessageUpsertBulk) Update(set func(*WhatsAppMessageUpsert)) *WhatsAppMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WhatsAppMessageUpsert{UpdateSet: update})
	}))
	return u
}

// SetConversationID sets the "conversation_id" field.
func (u *WhatsAppMessageUpsertBulk) SetConversationID(v uuid.UUID) *WhatsAppMessageUpsertBulk {
	return u.Update(func(s *WhatsAppMessageUpsert) {
		s.SetConversationID(v)
	})
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *WhatsAppMessageUpsertBulk) UpdateConversationID() *WhatsAppMessageUpsertBulk {
	return u.Update(func(s *WhatsAppMessageUpsert) {
		s.UpdateConversationID()
	})
}

// SetTenantID sets the "tenant_id" field.
func (u *WhatsAppMessageUpsertBulk) SetTenantID(v uuid.UUID) *WhatsAppMessageUpsertBulk {
	return u.Update(func(s *WhatsAppMessageUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *WhatsAppMessageUpsertBulk) UpdateTenantID() *WhatsAppMessageUpsertBulk {
	return u.Update(func(s *WhatsAppMessageUpsert) {
		s.UpdateTenantID()
	})
}

// SetDirection sets the "direction" field.
func (u *WhatsAppMessageUpsertBulk) SetDirection(v whatsappmessage.Direction) *WhatsAppMessageUpsertBulk {
	return u.Update(func(s *WhatsAppMessageUpsert) {
		s.SetDirection(v)
	})
}

// UpdateDirection sets the "direction" field to the value that was provided on create.
func (u *WhatsAppMessageUpsertBulk) UpdateDirection() *WhatsAppMessageUpsertBulk {
	return u.Update(func(s *WhatsAppMessageUpsert) {
		s.UpdateDirection()
	})
}

// SetMessageType sets the "message_type" field.
func (u *WhatsAppMessageUpsertBulk) SetMessageType(v string) *WhatsAppMessageUpsertBulk {
	return u.Update(func(s *WhatsAppMessageUpsert) {
		s.SetMessageType(v)
	})
}

// UpdateMessageType sets the "message_type" field to the value that was provided on create.
func (u *WhatsAppMessageUpsertBulk) UpdateMessageType() *WhatsAppMessageUpsertBulk {
	return u.Update(func(s *WhatsAppMessageUpsert) {
		s.UpdateMessageType()
	})
}

// SetBody sets the "body" field.
func (u *WhatsAppMessageUpsertBulk) SetBody(v string) *WhatsAppMessageUpsertBulk {
	return u.Update(func(s *WhatsAppMessageUpsert) {
		s.SetBody(v)
	})
}

// UpdateBody sets the "body" field to the value that was provided on create.
func (u *WhatsAppMessageUpsertBulk) UpdateBody() *WhatsAppMessageUpsertBulk {
	return u.Update(func(s *WhatsAppMessageUpsert) {
		s.UpdateBody()
	})
}

// SetWaMessageID sets the "wa_message_id" field.
func (u *WhatsAppMessageUpsertBulk) SetWaMessageID(v string) *WhatsAppMessageUpsertBulk {
	return u.Update(func(s *WhatsAppMessageUpsert) {
		s.SetWaMessageID(v)
	})
}

// UpdateWaMessageID sets the "wa_message_id" field to the value that was provided on create.
func (u *WhatsAppMessageUpsertBulk) UpdateWaMessageID() *WhatsAppMessageUpsertBulk {
	return u.Update(func(s *WhatsAppMessageUpsert) {
		s.UpdateWaMessageID()
	})
}

// ClearWaMessageID clears the value of the "wa_message_id" field.
func (u *WhatsAppMessageUpsertBulk) ClearWaMessageID() *WhatsAppMessageUpsertBulk {
	return u.Update(func(s *WhatsAppMessageUpsert) {
		s.ClearWaMessageID()
	})
}

// SetStatus sets the "status" field.
func (u *WhatsAppMessageUpsertBulk) SetStatus(v string) *WhatsAppMessageUpsertBulk {
	return u.Update(func(s *WhatsAppMessageUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *WhatsAppMessageUpsertBulk) UpdateStatus() *WhatsAppMessageUpsertBulk {
	return u.Update(func(s *WhatsAppMessageUpsert) {
		s.UpdateStatus()
	})
}

// SetSentByUserID sets the "sent_by_user_id" field.
func (u *WhatsAppMessageUpsertBulk) SetSentByUserID(v uuid.UUID) *WhatsAppMessageUpsertBulk {
	return u.Update(func(s *WhatsAppMessageUpsert) {
		s.SetSentByUserID(v)
	})
}

// UpdateSentByUserID sets the "sent_by_user_id" field to the value that was provided on create.
func (u *WhatsAppMessageUpsertBulk) UpdateSentByUserID() *WhatsAppMessageUpsertBulk {
	return u.Update(func(s *WhatsAppMessageUpsert) {
		s.UpdateSentByUserID()
	})
}

// ClearSentByUserID clears the value of the "sent_by_user_id" field.
func (u *WhatsAppMessageUpsertBulk) ClearSentByUserID() *WhatsAppMessageUpsertBulk {
	return u.Update(func(s *WhatsAppMessageUpsert) {
		s.ClearSentByUserID()
	})
}

// Exec executes the query.
func (u *WhatsAppMessageUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the WhatsAppMessageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WhatsAppMessageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WhatsAppMessageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
