// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Announcement is the predicate function for announcement builders.
type Announcement func(*sql.Selector)

// Backup is the predicate function for backup builders.
type Backup func(*sql.Selector)

// BackupSetting is the predicate function for backupsetting builders.
type BackupSetting func(*sql.Selector)

// Broadcast is the predicate function for broadcast builders.
type Broadcast func(*sql.Selector)

// BroadcastRecipient is the predicate function for broadcastrecipient builders.
type BroadcastRecipient func(*sql.Selector)

// CreditTransaction is the predicate function for credittransaction builders.
type CreditTransaction func(*sql.Selector)

// DeliveryLog is the predicate function for deliverylog builders.
type DeliveryLog func(*sql.Selector)

// DeviceToken is the predicate function for devicetoken builders.
type DeviceToken func(*sql.Selector)

// NotificationPermission is the predicate function for notificationpermission builders.
type NotificationPermission func(*sql.Selector)

// NotificationRole is the predicate function for notificationrole builders.
type NotificationRole func(*sql.Selector)

// NotificationRolePermission is the predicate function for notificationrolepermission builders.
type NotificationRolePermission func(*sql.Selector)

// Occasion is the predicate function for occasion builders.
type Occasion func(*sql.Selector)

// OutboxEvent is the predicate function for outboxevent builders.
type OutboxEvent func(*sql.Selector)

// Permission is the predicate function for permission builders.
type Permission func(*sql.Selector)

// PlatformBilling is the predicate function for platformbilling builders.
type PlatformBilling func(*sql.Selector)

// ProviderSetting is the predicate function for providersetting builders.
type ProviderSetting func(*sql.Selector)

// RateLimitConfig is the predicate function for ratelimitconfig builders.
type RateLimitConfig func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// ServiceConfig is the predicate function for serviceconfig builders.
type ServiceConfig func(*sql.Selector)

// Suppression is the predicate function for suppression builders.
type Suppression func(*sql.Selector)

// Template is the predicate function for template builders.
type Template func(*sql.Selector)

// Tenant is the predicate function for tenant builders.
type Tenant func(*sql.Selector)

// TenantCredit is the predicate function for tenantcredit builders.
type TenantCredit func(*sql.Selector)

// TenantWhatsAppSubscription is the predicate function for tenantwhatsappsubscription builders.
type TenantWhatsAppSubscription func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserRoleAssignment is the predicate function for userroleassignment builders.
type UserRoleAssignment func(*sql.Selector)

// WhatsAppConversation is the predicate function for whatsappconversation builders.
type WhatsAppConversation func(*sql.Selector)

// WhatsAppMessage is the predicate function for whatsappmessage builders.
type WhatsAppMessage func(*sql.Selector)

// WhatsAppPlan is the predicate function for whatsappplan builders.
type WhatsAppPlan func(*sql.Selector)
