// Code generated by ent, DO NOT EDIT.

package broadcast

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/notifications-api/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uuid.UUID) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldEQ(FieldTenantID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldEQ(FieldTitle, v))
}

// SendAt applies equality check predicate on the "send_at" field. It's identical to SendAtEQ.
func SendAt(v time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldEQ(FieldSendAt, v))
}

// OccasionID applies equality check predicate on the "occasion_id" field. It's identical to OccasionIDEQ.
func OccasionID(v uuid.UUID) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldEQ(FieldOccasionID, v))
}

// OccasionYear applies equality check predicate on the "occasion_year" field. It's identical to OccasionYearEQ.
func OccasionYear(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldEQ(FieldOccasionYear, v))
}

// RequestedBy applies equality check predicate on the "requested_by" field. It's identical to RequestedByEQ.
func RequestedBy(v string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldEQ(FieldRequestedBy, v))
}

// ApprovedBy applies equality check predicate on the "approved_by" field. It's identical to ApprovedByEQ.
func ApprovedBy(v string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldEQ(FieldApprovedBy, v))
}

// ApprovedAt applies equality check predicate on the "approved_at" field. It's identical to ApprovedAtEQ.
func ApprovedAt(v time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldEQ(FieldApprovedAt, v))
}

// TargetCount applies equality check predicate on the "target_count" field. It's identical to TargetCountEQ.
func TargetCount(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldEQ(FieldTargetCount, v))
}

// SentCount applies equality check predicate on the "sent_count" field. It's identical to SentCountEQ.
func SentCount(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldEQ(FieldSentCount, v))
}

// FailedCount applies equality check predicate on the "failed_count" field. It's identical to FailedCountEQ.
func FailedCount(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldEQ(FieldFailedCount, v))
}

// SkippedCount applies equality check predicate on the "skipped_count" field. It's identical to SkippedCountEQ.
func SkippedCount(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldEQ(FieldSkippedCount, v))
}

// SuppressedCount applies equality check predicate on the "suppressed_count" field. It's identical to SuppressedCountEQ.
func SuppressedCount(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldEQ(FieldSuppressedCount, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldEQ(FieldCompletedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldEQ(FieldUpdatedAt, v))
}

// ScopeEQ applies the EQ predicate on the "scope" field.
func ScopeEQ(v Scope) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldEQ(FieldScope, v))
}

// ScopeNEQ applies the NEQ predicate on the "scope" field.
func ScopeNEQ(v Scope) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNEQ(FieldScope, v))
}

// ScopeIn applies the In predicate on the "scope" field.
func ScopeIn(vs ...Scope) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldIn(FieldScope, vs...))
}

// ScopeNotIn applies the NotIn predicate on the "scope" field.
func ScopeNotIn(vs ...Scope) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNotIn(FieldScope, vs...))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uuid.UUID) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uuid.UUID) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uuid.UUID) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uuid.UUID) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uuid.UUID) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uuid.UUID) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uuid.UUID) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uuid.UUID) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.Broadcast {
	return predicate.Broadcast(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNotNull(FieldTenantID))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v Kind) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v Kind) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...Kind) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...Kind) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNotIn(FieldKind, vs...))
}

// ClassEQ applies the EQ predicate on the "class" field.
func ClassEQ(v Class) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldEQ(FieldClass, v))
}

// ClassNEQ applies the NEQ predicate on the "class" field.
func ClassNEQ(v Class) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNEQ(FieldClass, v))
}

// ClassIn applies the In predicate on the "class" field.
func ClassIn(vs ...Class) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldIn(FieldClass, vs...))
}

// ClassNotIn applies the NotIn predicate on the "class" field.
func ClassNotIn(vs ...Class) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNotIn(FieldClass, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNotIn(FieldStatus, vs...))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldContainsFold(FieldTitle, v))
}

// SendAtEQ applies the EQ predicate on the "send_at" field.
func SendAtEQ(v time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldEQ(FieldSendAt, v))
}

// SendAtNEQ applies the NEQ predicate on the "send_at" field.
func SendAtNEQ(v time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNEQ(FieldSendAt, v))
}

// SendAtIn applies the In predicate on the "send_at" field.
func SendAtIn(vs ...time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldIn(FieldSendAt, vs...))
}

// SendAtNotIn applies the NotIn predicate on the "send_at" field.
func SendAtNotIn(vs ...time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNotIn(FieldSendAt, vs...))
}

// SendAtGT applies the GT predicate on the "send_at" field.
func SendAtGT(v time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldGT(FieldSendAt, v))
}

// SendAtGTE applies the GTE predicate on the "send_at" field.
func SendAtGTE(v time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldGTE(FieldSendAt, v))
}

// SendAtLT applies the LT predicate on the "send_at" field.
func SendAtLT(v time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldLT(FieldSendAt, v))
}

// SendAtLTE applies the LTE predicate on the "send_at" field.
func SendAtLTE(v time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldLTE(FieldSendAt, v))
}

// SendAtIsNil applies the IsNil predicate on the "send_at" field.
func SendAtIsNil() predicate.Broadcast {
	return predicate.Broadcast(sql.FieldIsNull(FieldSendAt))
}

// SendAtNotNil applies the NotNil predicate on the "send_at" field.
func SendAtNotNil() predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNotNull(FieldSendAt))
}

// OccasionIDEQ applies the EQ predicate on the "occasion_id" field.
func OccasionIDEQ(v uuid.UUID) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldEQ(FieldOccasionID, v))
}

// OccasionIDNEQ applies the NEQ predicate on the "occasion_id" field.
func OccasionIDNEQ(v uuid.UUID) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNEQ(FieldOccasionID, v))
}

// OccasionIDIn applies the In predicate on the "occasion_id" field.
func OccasionIDIn(vs ...uuid.UUID) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldIn(FieldOccasionID, vs...))
}

// OccasionIDNotIn applies the NotIn predicate on the "occasion_id" field.
func OccasionIDNotIn(vs ...uuid.UUID) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNotIn(FieldOccasionID, vs...))
}

// OccasionIDGT applies the GT predicate on the "occasion_id" field.
func OccasionIDGT(v uuid.UUID) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldGT(FieldOccasionID, v))
}

// OccasionIDGTE applies the GTE predicate on the "occasion_id" field.
func OccasionIDGTE(v uuid.UUID) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldGTE(FieldOccasionID, v))
}

// OccasionIDLT applies the LT predicate on the "occasion_id" field.
func OccasionIDLT(v uuid.UUID) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldLT(FieldOccasionID, v))
}

// OccasionIDLTE applies the LTE predicate on the "occasion_id" field.
func OccasionIDLTE(v uuid.UUID) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldLTE(FieldOccasionID, v))
}

// OccasionIDIsNil applies the IsNil predicate on the "occasion_id" field.
func OccasionIDIsNil() predicate.Broadcast {
	return predicate.Broadcast(sql.FieldIsNull(FieldOccasionID))
}

// OccasionIDNotNil applies the NotNil predicate on the "occasion_id" field.
func OccasionIDNotNil() predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNotNull(FieldOccasionID))
}

// OccasionYearEQ applies the EQ predicate on the "occasion_year" field.
func OccasionYearEQ(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldEQ(FieldOccasionYear, v))
}

// OccasionYearNEQ applies the NEQ predicate on the "occasion_year" field.
func OccasionYearNEQ(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNEQ(FieldOccasionYear, v))
}

// OccasionYearIn applies the In predicate on the "occasion_year" field.
func OccasionYearIn(vs ...int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldIn(FieldOccasionYear, vs...))
}

// OccasionYearNotIn applies the NotIn predicate on the "occasion_year" field.
func OccasionYearNotIn(vs ...int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNotIn(FieldOccasionYear, vs...))
}

// OccasionYearGT applies the GT predicate on the "occasion_year" field.
func OccasionYearGT(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldGT(FieldOccasionYear, v))
}

// OccasionYearGTE applies the GTE predicate on the "occasion_year" field.
func OccasionYearGTE(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldGTE(FieldOccasionYear, v))
}

// OccasionYearLT applies the LT predicate on the "occasion_year" field.
func OccasionYearLT(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldLT(FieldOccasionYear, v))
}

// OccasionYearLTE applies the LTE predicate on the "occasion_year" field.
func OccasionYearLTE(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldLTE(FieldOccasionYear, v))
}

// OccasionYearIsNil applies the IsNil predicate on the "occasion_year" field.
func OccasionYearIsNil() predicate.Broadcast {
	return predicate.Broadcast(sql.FieldIsNull(FieldOccasionYear))
}

// OccasionYearNotNil applies the NotNil predicate on the "occasion_year" field.
func OccasionYearNotNil() predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNotNull(FieldOccasionYear))
}

// RequestedByEQ applies the EQ predicate on the "requested_by" field.
func RequestedByEQ(v string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldEQ(FieldRequestedBy, v))
}

// RequestedByNEQ applies the NEQ predicate on the "requested_by" field.
func RequestedByNEQ(v string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNEQ(FieldRequestedBy, v))
}

// RequestedByIn applies the In predicate on the "requested_by" field.
func RequestedByIn(vs ...string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldIn(FieldRequestedBy, vs...))
}

// RequestedByNotIn applies the NotIn predicate on the "requested_by" field.
func RequestedByNotIn(vs ...string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNotIn(FieldRequestedBy, vs...))
}

// RequestedByGT applies the GT predicate on the "requested_by" field.
func RequestedByGT(v string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldGT(FieldRequestedBy, v))
}

// RequestedByGTE applies the GTE predicate on the "requested_by" field.
func RequestedByGTE(v string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldGTE(FieldRequestedBy, v))
}

// RequestedByLT applies the LT predicate on the "requested_by" field.
func RequestedByLT(v string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldLT(FieldRequestedBy, v))
}

// RequestedByLTE applies the LTE predicate on the "requested_by" field.
func RequestedByLTE(v string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldLTE(FieldRequestedBy, v))
}

// RequestedByContains applies the Contains predicate on the "requested_by" field.
func RequestedByContains(v string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldContains(FieldRequestedBy, v))
}

// RequestedByHasPrefix applies the HasPrefix predicate on the "requested_by" field.
func RequestedByHasPrefix(v string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldHasPrefix(FieldRequestedBy, v))
}

// RequestedByHasSuffix applies the HasSuffix predicate on the "requested_by" field.
func RequestedByHasSuffix(v string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldHasSuffix(FieldRequestedBy, v))
}

// RequestedByIsNil applies the IsNil predicate on the "requested_by" field.
func RequestedByIsNil() predicate.Broadcast {
	return predicate.Broadcast(sql.FieldIsNull(FieldRequestedBy))
}

// RequestedByNotNil applies the NotNil predicate on the "requested_by" field.
func RequestedByNotNil() predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNotNull(FieldRequestedBy))
}

// RequestedByEqualFold applies the EqualFold predicate on the "requested_by" field.
func RequestedByEqualFold(v string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldEqualFold(FieldRequestedBy, v))
}

// RequestedByContainsFold applies the ContainsFold predicate on the "requested_by" field.
func RequestedByContainsFold(v string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldContainsFold(FieldRequestedBy, v))
}

// ApprovedByEQ applies the EQ predicate on the "approved_by" field.
func ApprovedByEQ(v string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldEQ(FieldApprovedBy, v))
}

// ApprovedByNEQ applies the NEQ predicate on the "approved_by" field.
func ApprovedByNEQ(v string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNEQ(FieldApprovedBy, v))
}

// ApprovedByIn applies the In predicate on the "approved_by" field.
func ApprovedByIn(vs ...string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldIn(FieldApprovedBy, vs...))
}

// ApprovedByNotIn applies the NotIn predicate on the "approved_by" field.
func ApprovedByNotIn(vs ...string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNotIn(FieldApprovedBy, vs...))
}

// ApprovedByGT applies the GT predicate on the "approved_by" field.
func ApprovedByGT(v string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldGT(FieldApprovedBy, v))
}

// ApprovedByGTE applies the GTE predicate on the "approved_by" field.
func ApprovedByGTE(v string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldGTE(FieldApprovedBy, v))
}

// ApprovedByLT applies the LT predicate on the "approved_by" field.
func ApprovedByLT(v string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldLT(FieldApprovedBy, v))
}

// ApprovedByLTE applies the LTE predicate on the "approved_by" field.
func ApprovedByLTE(v string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldLTE(FieldApprovedBy, v))
}

// ApprovedByContains applies the Contains predicate on the "approved_by" field.
func ApprovedByContains(v string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldContains(FieldApprovedBy, v))
}

// ApprovedByHasPrefix applies the HasPrefix predicate on the "approved_by" field.
func ApprovedByHasPrefix(v string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldHasPrefix(FieldApprovedBy, v))
}

// ApprovedByHasSuffix applies the HasSuffix predicate on the "approved_by" field.
func ApprovedByHasSuffix(v string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldHasSuffix(FieldApprovedBy, v))
}

// ApprovedByIsNil applies the IsNil predicate on the "approved_by" field.
func ApprovedByIsNil() predicate.Broadcast {
	return predicate.Broadcast(sql.FieldIsNull(FieldApprovedBy))
}

// ApprovedByNotNil applies the NotNil predicate on the "approved_by" field.
func ApprovedByNotNil() predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNotNull(FieldApprovedBy))
}

// ApprovedByEqualFold applies the EqualFold predicate on the "approved_by" field.
func ApprovedByEqualFold(v string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldEqualFold(FieldApprovedBy, v))
}

// ApprovedByContainsFold applies the ContainsFold predicate on the "approved_by" field.
func ApprovedByContainsFold(v string) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldContainsFold(FieldApprovedBy, v))
}

// ApprovedAtEQ applies the EQ predicate on the "approved_at" field.
func ApprovedAtEQ(v time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldEQ(FieldApprovedAt, v))
}

// ApprovedAtNEQ applies the NEQ predicate on the "approved_at" field.
func ApprovedAtNEQ(v time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNEQ(FieldApprovedAt, v))
}

// ApprovedAtIn applies the In predicate on the "approved_at" field.
func ApprovedAtIn(vs ...time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldIn(FieldApprovedAt, vs...))
}

// ApprovedAtNotIn applies the NotIn predicate on the "approved_at" field.
func ApprovedAtNotIn(vs ...time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNotIn(FieldApprovedAt, vs...))
}

// ApprovedAtGT applies the GT predicate on the "approved_at" field.
func ApprovedAtGT(v time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldGT(FieldApprovedAt, v))
}

// ApprovedAtGTE applies the GTE predicate on the "approved_at" field.
func ApprovedAtGTE(v time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldGTE(FieldApprovedAt, v))
}

// ApprovedAtLT applies the LT predicate on the "approved_at" field.
func ApprovedAtLT(v time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldLT(FieldApprovedAt, v))
}

// ApprovedAtLTE applies the LTE predicate on the "approved_at" field.
func ApprovedAtLTE(v time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldLTE(FieldApprovedAt, v))
}

// ApprovedAtIsNil applies the IsNil predicate on the "approved_at" field.
func ApprovedAtIsNil() predicate.Broadcast {
	return predicate.Broadcast(sql.FieldIsNull(FieldApprovedAt))
}

// ApprovedAtNotNil applies the NotNil predicate on the "approved_at" field.
func ApprovedAtNotNil() predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNotNull(FieldApprovedAt))
}

// TargetCountEQ applies the EQ predicate on the "target_count" field.
func TargetCountEQ(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldEQ(FieldTargetCount, v))
}

// TargetCountNEQ applies the NEQ predicate on the "target_count" field.
func TargetCountNEQ(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNEQ(FieldTargetCount, v))
}

// TargetCountIn applies the In predicate on the "target_count" field.
func TargetCountIn(vs ...int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldIn(FieldTargetCount, vs...))
}

// TargetCountNotIn applies the NotIn predicate on the "target_count" field.
func TargetCountNotIn(vs ...int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNotIn(FieldTargetCount, vs...))
}

// TargetCountGT applies the GT predicate on the "target_count" field.
func TargetCountGT(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldGT(FieldTargetCount, v))
}

// TargetCountGTE applies the GTE predicate on the "target_count" field.
func TargetCountGTE(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldGTE(FieldTargetCount, v))
}

// TargetCountLT applies the LT predicate on the "target_count" field.
func TargetCountLT(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldLT(FieldTargetCount, v))
}

// TargetCountLTE applies the LTE predicate on the "target_count" field.
func TargetCountLTE(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldLTE(FieldTargetCount, v))
}

// SentCountEQ applies the EQ predicate on the "sent_count" field.
func SentCountEQ(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldEQ(FieldSentCount, v))
}

// SentCountNEQ applies the NEQ predicate on the "sent_count" field.
func SentCountNEQ(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNEQ(FieldSentCount, v))
}

// SentCountIn applies the In predicate on the "sent_count" field.
func SentCountIn(vs ...int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldIn(FieldSentCount, vs...))
}

// SentCountNotIn applies the NotIn predicate on the "sent_count" field.
func SentCountNotIn(vs ...int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNotIn(FieldSentCount, vs...))
}

// SentCountGT applies the GT predicate on the "sent_count" field.
func SentCountGT(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldGT(FieldSentCount, v))
}

// SentCountGTE applies the GTE predicate on the "sent_count" field.
func SentCountGTE(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldGTE(FieldSentCount, v))
}

// SentCountLT applies the LT predicate on the "sent_count" field.
func SentCountLT(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldLT(FieldSentCount, v))
}

// SentCountLTE applies the LTE predicate on the "sent_count" field.
func SentCountLTE(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldLTE(FieldSentCount, v))
}

// FailedCountEQ applies the EQ predicate on the "failed_count" field.
func FailedCountEQ(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldEQ(FieldFailedCount, v))
}

// FailedCountNEQ applies the NEQ predicate on the "failed_count" field.
func FailedCountNEQ(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNEQ(FieldFailedCount, v))
}

// FailedCountIn applies the In predicate on the "failed_count" field.
func FailedCountIn(vs ...int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldIn(FieldFailedCount, vs...))
}

// FailedCountNotIn applies the NotIn predicate on the "failed_count" field.
func FailedCountNotIn(vs ...int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNotIn(FieldFailedCount, vs...))
}

// FailedCountGT applies the GT predicate on the "failed_count" field.
func FailedCountGT(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldGT(FieldFailedCount, v))
}

// FailedCountGTE applies the GTE predicate on the "failed_count" field.
func FailedCountGTE(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldGTE(FieldFailedCount, v))
}

// FailedCountLT applies the LT predicate on the "failed_count" field.
func FailedCountLT(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldLT(FieldFailedCount, v))
}

// FailedCountLTE applies the LTE predicate on the "failed_count" field.
func FailedCountLTE(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldLTE(FieldFailedCount, v))
}

// SkippedCountEQ applies the EQ predicate on the "skipped_count" field.
func SkippedCountEQ(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldEQ(FieldSkippedCount, v))
}

// SkippedCountNEQ applies the NEQ predicate on the "skipped_count" field.
func SkippedCountNEQ(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNEQ(FieldSkippedCount, v))
}

// SkippedCountIn applies the In predicate on the "skipped_count" field.
func SkippedCountIn(vs ...int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldIn(FieldSkippedCount, vs...))
}

// SkippedCountNotIn applies the NotIn predicate on the "skipped_count" field.
func SkippedCountNotIn(vs ...int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNotIn(FieldSkippedCount, vs...))
}

// SkippedCountGT applies the GT predicate on the "skipped_count" field.
func SkippedCountGT(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldGT(FieldSkippedCount, v))
}

// SkippedCountGTE applies the GTE predicate on the "skipped_count" field.
func SkippedCountGTE(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldGTE(FieldSkippedCount, v))
}

// SkippedCountLT applies the LT predicate on the "skipped_count" field.
func SkippedCountLT(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldLT(FieldSkippedCount, v))
}

// SkippedCountLTE applies the LTE predicate on the "skipped_count" field.
func SkippedCountLTE(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldLTE(FieldSkippedCount, v))
}

// SuppressedCountEQ applies the EQ predicate on the "suppressed_count" field.
func SuppressedCountEQ(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldEQ(FieldSuppressedCount, v))
}

// SuppressedCountNEQ applies the NEQ predicate on the "suppressed_count" field.
func SuppressedCountNEQ(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNEQ(FieldSuppressedCount, v))
}

// SuppressedCountIn applies the In predicate on the "suppressed_count" field.
func SuppressedCountIn(vs ...int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldIn(FieldSuppressedCount, vs...))
}

// SuppressedCountNotIn applies the NotIn predicate on the "suppressed_count" field.
func SuppressedCountNotIn(vs ...int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNotIn(FieldSuppressedCount, vs...))
}

// SuppressedCountGT applies the GT predicate on the "suppressed_count" field.
func SuppressedCountGT(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldGT(FieldSuppressedCount, v))
}

// SuppressedCountGTE applies the GTE predicate on the "suppressed_count" field.
func SuppressedCountGTE(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldGTE(FieldSuppressedCount, v))
}

// SuppressedCountLT applies the LT predicate on the "suppressed_count" field.
func SuppressedCountLT(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldLT(FieldSuppressedCount, v))
}

// SuppressedCountLTE applies the LTE predicate on the "suppressed_count" field.
func SuppressedCountLTE(v int) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldLTE(FieldSuppressedCount, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.Broadcast {
	return predicate.Broadcast(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNotNull(FieldMetadata))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.Broadcast {
	return predicate.Broadcast(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNotNull(FieldCompletedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Broadcast {
	return predicate.Broadcast(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Broadcast) predicate.Broadcast {
	return predicate.Broadcast(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Broadcast) predicate.Broadcast {
	return predicate.Broadcast(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Broadcast) predicate.Broadcast {
	return predicate.Broadcast(sql.NotPredicates(p))
}
