// Code generated by ent, DO NOT EDIT.

package whatsappconversation

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the whatsappconversation type in the database.
	Label = "whats_app_conversation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldPhoneNumberID holds the string denoting the phone_number_id field in the database.
	FieldPhoneNumberID = "phone_number_id"
	// FieldCustomerWaID holds the string denoting the customer_wa_id field in the database.
	FieldCustomerWaID = "customer_wa_id"
	// FieldCustomerName holds the string denoting the customer_name field in the database.
	FieldCustomerName = "customer_name"
	// FieldLastMessageAt holds the string denoting the last_message_at field in the database.
	FieldLastMessageAt = "last_message_at"
	// FieldLastMessagePreview holds the string denoting the last_message_preview field in the database.
	FieldLastMessagePreview = "last_message_preview"
	// FieldLastInboundAt holds the string denoting the last_inbound_at field in the database.
	FieldLastInboundAt = "last_inbound_at"
	// FieldUnreadCount holds the string denoting the unread_count field in the database.
	FieldUnreadCount = "unread_count"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeMessages holds the string denoting the messages edge name in mutations.
	EdgeMessages = "messages"
	// Table holds the table name of the whatsappconversation in the database.
	Table = "whats_app_conversations"
	// MessagesTable is the table that holds the messages relation/edge.
	MessagesTable = "whats_app_messages"
	// MessagesInverseTable is the table name for the WhatsAppMessage entity.
	// It exists in this package in order to avoid circular dependency with the "whatsappmessage" package.
	MessagesInverseTable = "whats_app_messages"
	// MessagesColumn is the table column denoting the messages relation/edge.
	MessagesColumn = "conversation_id"
)

// Columns holds all SQL columns for whatsappconversation fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldPhoneNumberID,
	FieldCustomerWaID,
	FieldCustomerName,
	FieldLastMessageAt,
	FieldLastMessagePreview,
	FieldLastInboundAt,
	FieldUnreadCount,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// PhoneNumberIDValidator is a validator for the "phone_number_id" field. It is called by the builders before save.
	PhoneNumberIDValidator func(string) error
	// CustomerWaIDValidator is a validator for the "customer_wa_id" field. It is called by the builders before save.
	CustomerWaIDValidator func(string) error
	// DefaultLastMessageAt holds the default value on creation for the "last_message_at" field.
	DefaultLastMessageAt func() time.Time
	// DefaultUnreadCount holds the default value on creation for the "unread_count" field.
	DefaultUnreadCount int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the WhatsAppConversation queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByPhoneNumberID orders the results by the phone_number_id field.
func ByPhoneNumberID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhoneNumberID, opts...).ToFunc()
}

// ByCustomerWaID orders the results by the customer_wa_id field.
func ByCustomerWaID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomerWaID, opts...).ToFunc()
}

// ByCustomerName orders the results by the customer_name field.
func ByCustomerName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomerName, opts...).ToFunc()
}

// ByLastMessageAt orders the results by the last_message_at field.
func ByLastMessageAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastMessageAt, opts...).ToFunc()
}

// ByLastMessagePreview orders the results by the last_message_preview field.
func ByLastMessagePreview(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastMessagePreview, opts...).ToFunc()
}

// ByLastInboundAt orders the results by the last_inbound_at field.
func ByLastInboundAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastInboundAt, opts...).ToFunc()
}

// ByUnreadCount orders the results by the unread_count field.
func ByUnreadCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnreadCount, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByMessagesCount orders the results by messages count.
func ByMessagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMessagesStep(), opts...)
	}
}

// ByMessages orders the results by messages terms.
func ByMessages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMessagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newMessagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MessagesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, MessagesTable, MessagesColumn),
	)
}
