package providers

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/bengobox/notifications-api/internal/database"
	"github.com/bengobox/notifications-api/internal/encryption"
	pcfg "github.com/bengobox/notifications-api/internal/providers/config"
	"github.com/bengobox/notifications-api/internal/providers/push"
)

// The platform's Web Push (VAPID) identity: generated by this service the first time push is
// needed and stored as platform provider settings (push/webpush, private key encrypted), so push
// works with no Firebase project. Admins may replace the keys in Platform > Providers > Push.

const (
	webPushProviderName   = "webpush"
	defaultWebPushSubject = "https://codevertexafrica.com"
	webPushCacheTTL       = 10 * time.Minute
)

// WebPushKeys returns the platform VAPID identity, creating it on first use.
func (m *Manager) WebPushKeys(ctx context.Context) (push.WebPushConfig, error) {
	m.vapidMu.Lock()
	defer m.vapidMu.Unlock()
	if m.vapidCache != nil && time.Since(m.vapidAt) < webPushCacheTTL {
		return *m.vapidCache, nil
	}

	cfg, ok := m.loadWebPushKeys(ctx)
	if !ok {
		var err error
		cfg, err = m.provisionWebPushKeys(ctx)
		if err != nil {
			return push.WebPushConfig{}, err
		}
	}
	m.vapidCache = &cfg
	m.vapidAt = time.Now()
	return cfg, nil
}

func (m *Manager) loadWebPushKeys(ctx context.Context) (push.WebPushConfig, bool) {
	s, err := pcfg.LoadTenantOnlyProviderSettings(ctx, m.dbCfg, "platform", m.env, "push", webPushProviderName, m.decryptionKey)
	if err != nil {
		return push.WebPushConfig{}, false
	}
	cfg := push.WebPushConfig{
		PublicKey:  strings.TrimSpace(s["vapid_public_key"]),
		PrivateKey: strings.TrimSpace(s["vapid_private_key"]),
		Subject:    firstNonEmpty(strings.TrimSpace(s["subject"]), defaultWebPushSubject),
	}
	return cfg, cfg.PublicKey != "" && cfg.PrivateKey != ""
}

// provisionWebPushKeys generates and stores the key pair. A Postgres advisory lock makes sure two
// pods starting together store ONE pair (a public key from one pair with the private key of
// another would make every push fail signature checks).
func (m *Manager) provisionWebPushKeys(ctx context.Context) (push.WebPushConfig, error) {
	if m.db == nil {
		return push.WebPushConfig{}, fmt.Errorf("webpush: no database to store VAPID keys")
	}
	if len(m.decryptionKey) != 32 {
		return push.WebPushConfig{}, fmt.Errorf("webpush: encryption key unavailable, refusing to store a private key in plain text")
	}
	tx, err := m.db.Begin(ctx)
	if err != nil {
		return push.WebPushConfig{}, fmt.Errorf("webpush: begin: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()
	if _, err := tx.Exec(ctx, `SELECT pg_advisory_xact_lock(hashtext('notifications:webpush-vapid'))`); err != nil {
		return push.WebPushConfig{}, fmt.Errorf("webpush: lock: %w", err)
	}
	// Another pod may have created them while we waited.
	if cfg, ok := m.loadWebPushKeys(ctx); ok {
		return cfg, tx.Commit(ctx)
	}

	public, private, err := push.GenerateVAPIDKeys()
	if err != nil {
		return push.WebPushConfig{}, fmt.Errorf("webpush: generate keys: %w", err)
	}
	encPrivate, err := encryption.Encrypt(private, m.decryptionKey)
	if err != nil {
		return push.WebPushConfig{}, fmt.Errorf("webpush: encrypt key: %w", err)
	}

	client, err := database.NewClient(ctx, m.dbCfg)
	if err != nil {
		return push.WebPushConfig{}, fmt.Errorf("webpush: db client: %w", err)
	}
	defer client.Close()
	rows := []struct {
		key, value, desc string
		secret           bool
	}{
		{"vapid_public_key", public, "Web Push VAPID public key (served to browsers)", false},
		{"vapid_private_key", encPrivate, "Web Push VAPID private key", true},
		{"subject", defaultWebPushSubject, "Web Push sender contact", false},
	}
	for _, r := range rows {
		if _, err := client.ProviderSetting.Create().
			SetTenantID("platform").
			SetChannel("push").SetProvider(webPushProviderName).
			SetProviderType("push").SetProviderName(webPushProviderName).
			SetKey(r.key).SetValue(r.value).SetDescription(r.desc).
			SetIsEncrypted(r.secret).SetIsSecret(r.secret).
			SetIsPlatform(true).SetEnvironment("production").
			Save(ctx); err != nil {
			return push.WebPushConfig{}, fmt.Errorf("webpush: store %s: %w", r.key, err)
		}
	}
	if err := tx.Commit(ctx); err != nil {
		return push.WebPushConfig{}, fmt.Errorf("webpush: commit: %w", err)
	}
	return push.WebPushConfig{PublicKey: public, PrivateKey: private, Subject: defaultWebPushSubject}, nil
}
